crafting changes
Darkrp-community/OpenKeep pull request #1000
Opened 2024-10-22 04:27 UTC by cornercube

## About The Pull Request
bows need to have a bowstring made first before stringing the bow, and you need a knife to actually carve the wood into shape
regular bow is made from a short log and a bow string
recurve bow needs sinew and horn, from butchery and trolls respectively, and a bowstring
longbow needs a long log and a bowstring
bowstring is made from fiber, for now, though catgut would be a nice addition later on

you can make uncolored tunics now, but only the town weaver has the skill necessary
its a secret taught by the weavers guild
town weaver is differentiated from pilgrim weaver, more broadly
town weaver has less knives, medicine, and sneaking, but he knows how to make tunics and he knows how to make the town tunic

## Why It's Good For The Game
immersion

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-10-22 04:39 UTC, sanshoom commented
Hello PR#1000

2024-10-22 05:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "bowstring"
A bowstring shouldn't take **carpentry** to make, change the skill to either sewing (for ropemaking) or crafting please. Ropes are already made with crafting, after all.

2024-10-22 05:09 UTC, ThePainkiller commented
You got something wrong though

Longbow should be the one crafted with Sinew, as it literally states on its item description that it is made from animal sinew, whereas recurve is just a lesser damage bow.

Higher damage = need animal kills to make (also, again, it's right there on the bow's description)

2024-10-22 05:13 UTC, cornercube commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "bowstring"
fixed

2024-10-22 05:15 UTC, cornercube commented
recurve bows are usually of composite design
it deals lower damage purely as a game balance, since it charges faster and has less stamina drain

longbow fixed

2024-10-22 22:00 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +/datum/crafting_recipe/roguetown/handmadebow
Uhm, you make an entire subcategory called "bowyer" and you didn't refactor these three recipes under it so that it requires carpentry and a knife...

2024-10-22 22:09 UTC, ThePainkiller requested changes
"Fixed", the greatest contributor lie told after `[x] "You tested this on a local server."`

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	/obj/item/natural/bowstring = 1,
```suggestion
	/obj/item/alch/sinew = 1,
```
Stop lying to me when you say "fixed".

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree/small = 2, /obj/item/alch/sinew = 1, /obj/item/alch/horn = 1, /obj/item/natural/bowstring = 2)
```suggestion
	reqs = list(/obj/item/grown/log/tree/small = 1, /obj/item/natural/bowstring = 1)
```
Less damage, less craftdiff bow shouldn't take more materials and monster drops.

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	craftdiff = 2
```suggestion
	craftdiff = 1
```

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	craftdiff = 1
```suggestion
	craftdiff = 2
```

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	/obj/item/natural/bowstring = 1)
```suggestion
	/obj/item/natural/bowstring = 2)
```

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +/datum/crafting_recipe/roguetown/handmadebow
```suggestion
/datum/crafting_recipe/roguetown/bowyer/handmadebow
```

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +/datum/crafting_recipe/roguetown/recurve
```suggestion
/datum/crafting_recipe/roguetown/bowyer/recurve
```

2024-10-22 22:09 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +/datum/crafting_recipe/roguetown/longbow
```suggestion
/datum/crafting_recipe/roguetown/bowyer/longbow
```

2024-10-22 22:46 UTC, Optimism333 commented
> "Fixed", the greatest contributor lie told after `[x] "You tested this on a local server."`

Let's try to be civil with our contributors on the git, please.

2024-10-22 22:48 UTC, ThePainkiller commented
> > "Fixed", the greatest contributor lie told after `[x] "You tested this on a local server."`
> 
> Let's try to be civil with our contributors on the git, please.

It's joke,,,,,dont get angy pwease,,,,,,

2024-10-23 01:37 UTC, cornercube commented on code/modules/roguetown/roguecrafting/items.dm
> +	craftdiff = 2
recurve bow is a composite bow, it should have more than one material in its construction by definition

2024-10-23 03:34 UTC, ThePainkiller requested changes
I don't know how to say this any more politely so I will be very thorough:

Craftdiff is based on damage multipliers of the bows. Not their "uniqueness" or "compositeness". Balance over realism.

Leave them as they originally were, in tiers of difficulty, for balances purposes.

And **do not** revert changes by a maintainer, when a maintainer is telling you that these values won't fly.

2024-10-23 03:34 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	craftdiff = 1
```suggestion
	craftdiff = 2
```

2024-10-23 03:34 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	craftdiff = 2
```suggestion
	craftdiff = 1
```

2024-10-23 03:36 UTC, ThePainkiller requested changes

2024-10-23 03:36 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree/small = 1, /obj/item/natural/bowstring = 1, /obj/item/alch/sinew = 1, /obj/item/alch/horn = 1 )
```suggestion
	reqs = list(/obj/item/grown/log/tree/small = 1, /obj/item/natural/bowstring = 1)
```

2024-10-23 04:33 UTC, cornercube commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree/small = 1, /obj/item/natural/bowstring = 1, /obj/item/alch/sinew = 1, /obj/item/alch/horn = 1 )
the sinew and the horn are needed for it to be a composite bow
and it is supposed to be harder to make than the regular bow, the reduced damage is just so that it wont be a a direct upgrade over the regular bow, but it is otherwise rare and hard to find

2024-10-23 05:29 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree/small = 1, /obj/item/natural/bowstring = 1, /obj/item/alch/sinew = 1, /obj/item/alch/horn = 1 )
The sinew and horn are pointlessly overcomplicating the recipe for a bow that deals 0.9 times the damage of a normal bow, making it not only harder to craft (requiring more carpentry levels) but also requiring materials exclusively obtained through killing literal TROLLS is ridiculous. Why would you risk killing a troll for a bow that does less damage than a starter, normal bow most ranged classes start with? Just because it spends like 5 less stamina per shot?
I understand it's nice to give troll horns any other use than exclusively exporting them or making potions with them, but this is definitely not the item to be looking at just because it has "composite" on its name and because they were historically made with bone and sinew
It's a matter of choosing balance over realism, and balance must always come on top, for the sake of making the game enjoyable and not exploitable or needlessly difficult

2024-10-23 05:50 UTC, cornercube commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree/small = 1, /obj/item/natural/bowstring = 1, /obj/item/alch/sinew = 1, /obj/item/alch/horn = 1 )
the recipe is meant to be hard to make in the first place, it is not a commonplace weapon 
0.9 damage is so that isnt a straight upgrade over the regular bow
but if the issue is that its slightly weaker therefore it cant be rarer, then i will add a non-crafting way to get it that is straightforward like just actually spawning with them

2024-11-27 05:25 UTC, closed without merging