Lonely Priest Seeking Choir
Darkrp-community/OpenKeep pull request #1020
Opened 2024-10-27 17:05 UTC by NPC1314

## About The Pull Request

Not entirely happy with where Temple is at, Priest gets bullied a little too easily. 

* Priest polearm skilled replaced with mace , given the bell ringer mace (they didnt even have a staff before, ringer is more unique and also fits on hip slot.)
* Aasimar and Dwarf priests gets to try the new Priest helmet I made. It got antimagic included so they don't need the null magic ring any more, Astrata got them covered as long as they wear their hat like theyre meant to.
* New Priest hat lets you toggle the mask to show your name and descriptors without taking off your insignia. Also get a tiny bit of armor. The magic defense makes you immune from other Astratans using their fire spell on you
* Priest dying triggers a single Bad Omen (doesnt repeat like the Ruler one, needs testing a few rounds just to make sure its not buggy, but worked fine in local)
* The Astra fire spell slightly bufffed by having 2 sec longer burntime, but slightly lower range and longer cooldown. Until fire damage is fixed this has to do.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-10-27 17:08 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/church/priest.dm
> +	beltr = /obj/item/rogueweapon/mace/church
Two things, first this spawns on the map and shouldn't be duplicated. 

Second, the Priest DOES have a staff and this is the path, feel free to check it out. /obj/item/rogueweapon/woodstaff/aries

2024-10-27 17:10 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/church/priest.dm
> +	beltr = /obj/item/rogueweapon/mace/church
ugh,I'll just put it in their hand instead then, no point having their staff laying about

2024-10-27 19:13 UTC, BadAtThisGame302 requested changes
Don't keep the bell ringer, it spawns next to the bell on every map, same as the staff. Please, this is duping.

2024-10-27 19:14 UTC, NPC1314 commented
> Don't keep the bell ringer, it spawns next to the bell on every map, same as the staff. Please, this is duping.

relax, just forgot to delet. The mapped staff will go as soon as this goes into testing too, dont worry be happy.

2024-10-28 02:55 UTC, Optimism333 reviewed
![image](https://github.com/user-attachments/assets/f4eb9cc1-63c9-44cc-985a-df40378d4f25)

Slight mistake, you added a second line of polearms skill here.

2024-10-29 22:50 UTC, Optimism333 approved these changes

2024-10-29 22:59 UTC, merged