Additions, rebalances and new roles
Darkrp-community/OpenKeep pull request #1118
Opened 2024-11-16 07:01 UTC by Dorodomki

## About The Pull Request

adds the valorian swordfighter a warrior style merc for valoria, adds the tiefling crimson marauder, a new skirmisher type fighter that may need rebalance since is totally new, adds updated descriptions and tutorials for the mercenary roles, reworks them to be 4 types of mercenary instead of 1-2-3 by adjusting their gear and skills on something more static instead of randomized skills, they are behind from a rare adventurer but they can keep themselves alive and have a fair gear, now covered in every possible area on a fairer way, being light armors on arms and neck and nerfed steel gear wich only garrison and rare adventurers should get, not dirty mercenaries who don't use the wide range of iron armors ingame and are able to upgrade to steel via gaming, except for our friend the zybantu mercenary who used to spawn with a longsword of 30 damage, full steel armor and heavy gloves for protection in every area, now gets most of his armor nerfed to fit alongside the other mercenaries who had their steel privilege removed except from steel helmets since they look cool and play mercenary can't be worse than a warrior adventurer 

the pr needs more testing and even more balance by the proper maintainers, im just a player and dev trowing my grain of " lets make this a bit more fair since is a mess!"

in other subject this pr also removes tieflings and drows from the garrison/maker's guild, voted by the players in exchange for these races being able to roll legendary smith/mason and be more grounded to the game lore of "tolerated species" instead of be inserted in roles where they shouldn't be normally, they would have to be hired ingame as workers or in the case of tieflings they are more of a "Savage band" of mercenaries that lift the suspiction of everyone (including the PTSD of Aasimars seeing again bronze devils after a millenia)

## Why It's Good For The Game

more content, more roles, more identity for the Tieflings and Drows

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-11-16 08:06 UTC, BadAtThisGame302 requested changes

2024-11-16 08:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/serfs/blacksmith.dm
> +	allowed_sexes = list(MALE, FEMALE)
Don't need to add this.

2024-11-16 08:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/serfs/blacksmith.dm
> +	allowed_sexes = list(MALE, FEMALE)
Ditto.

2024-11-16 08:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
> +	tutorial = "A cutthroat from the western countries, you've Mastered the Art of Swordfighting alongside Polearms and Shields to storm enemy positions."
Don't capitalise Mastered, Art, Swordfighting, Polearms, Shields.

2024-11-16 08:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
> +	tutorial = "A mercenary from hailing from the wild frontier steppes. There are three things you value most; saigas, freedom, and coin They Use a Bow for quick attacks alongside a Saber for Close enc
Don't capitilise Bow, Saber, Close.

Also change saber to sabre.

2024-11-16 08:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
> +	name = "Grenzelhoftter Greatswordsman"
Two t's in Grenzelhofter.

2024-11-16 08:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
> +	tutorial = "A mercenary from the Grenzelhoft Empire's Mercenary Guild. Their only care is coin, and the procurement of coin, they use a Heavy Iron Zweihander as Main Weapon, aim well every devastati
Don't capitalise Heavy, Iron, Zweihander, Main, Weapon.

2024-11-16 16:02 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
> +	name = "Grenzelhoftter Greatswordsman"
is german and added it just due to that since it sounds cool

2024-11-16 18:28 UTC, sanshoom commented
Is there anyway to change the Zybantine mercs and other related Zybantine classes to have a brighter shade of red for their clothing and keffiyeh?

2024-11-16 19:11 UTC, anything86 commented
Limiting a dodge class to +1 Speed when it's exclusive to a race that only gets +1 Speed racial is a headscratcher. Garrison fencer has potentially 2 speed more than Crimson Marauder, with a better, synergistic weapon. Valorian Swordsman is perhaps a worse offender since, even putting dodge aside, it has nothing to set itself apart or above the Crimson Marauder. Should maybe look into these things.

2024-11-16 19:24 UTC, lavillastrangiato commented on code/game/objects/items/rogueweapons/shields.dm
> +	name = "Desert Rider shield"
probably change it to "desert rider shield", all-lowercase, so it remains in line with the general lowercase item names

2024-11-16 19:26 UTC, lavillastrangiato commented on code/game/objects/items/rogueweapons/shields.dm
> +	desc = "A iron reinforced shield that covers the entire chest, a design of the ziggurat popular on the desert mercenaries."
try "A shield of Zybantine design, reinforced with iron and made to protect the upper body."

2024-11-16 19:27 UTC, lavillastrangiato commented on code/modules/clothing/rogueclothes/armor.dm
> +	name = "Jinete's Linothorax"
"jinete's linothorax"

2024-11-16 19:33 UTC, lavillastrangiato commented on code/modules/clothing/rogueclothes/armor.dm
> +	desc = "An equipment styled in the shape of the skirmisher tiefling nomads of the Crimsonlands, a modified version of the ancestral craft of the original tiefling equipment of the Apotheosis war. Mo
try "A stained leather cuirass bearing the snarling face of a demon. The tiefling nomads of the Crimsonlands shape this armor to hearken to that which their ancestors wore."

2024-11-19 18:00 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/grenzelhoft.dm
> +	tutorial = "A mercenary from the Grenzelhoft Empire's Mercenary Guild. Their only care is coin, and the procurement of coin, they use a heavy iron zweihander as main weapon, aim well every devastati
as a* main weapon and aim well...

2024-11-19 18:04 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
> +	tutorial = "A mercenary from hailing from the wild frontier steppes. There are three things you value most; saigas, freedom, and coin They Use a bow for quick attacks alongside a sabre for close enc
Don't capitalize They and Use.

2024-11-19 18:06 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
> +	tutorial = "A cutthroat from the western countries, you've Mastered the art of swordfighting alongside polearms and shields to storm enemy positions."
Don't capitalize Mastered.

2024-11-21 12:11 UTC, NPC1314 commented on code/modules/clothing/rogueclothes/armor.dm
> +	slot_flags = ITEM_SLOT_ARMOR
check the parent var before adding please

2024-11-21 12:13 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
> +		H.change_stat("constitution", 1)//so they get 3 stat points like anyone else
4, with the weight of STR this if 5 points bonus too, though other merc classes more extreme

2024-11-21 12:14 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
> -		H.merctype = 1
why is this deleted and what does it do?

2024-11-21 20:22 UTC, ThePainkiller commented
To be honest these sound like such long titles, sometimes less is more

2024-11-22 08:16 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/valorian.dm
> +	name = "Valorian Swordfighter"
change do just "Duelist"

2024-11-22 08:16 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
> +	name = "Steppesman Archer"
back to just "Steppesman"

2024-11-22 08:17 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/boltslinger.dm
> +	name = "Boltslinger Sharpshooter"
Back to "Boltslinger"

2024-11-23 14:16 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
> -		H.merctype = 1
it limits mercenary slots, removed from every mercenary so they can be repeated even if an admin gives more slots for the role since the mercenary role is 4 guys

2024-11-23 14:17 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/other/merc_classes/valorian.dm
> +	name = "Valorian Swordfighter"
he isn't a duelist but a valorian warrior in lore and code, duelist classes aren't planned for the valorian humen but for the elf, wich i ain't coding soon

2024-11-23 14:17 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
> +	name = "Steppesman Archer"
is a description for new people to know what does every role and giving them some flavour

2024-11-23 14:19 UTC, Dorodomki commented
> Grenzelhofter Greatswordsman should just be Landsknecht anyways, leaning so hard on the theme the name works better and less clumsy.
> 
> Crimson Marauder is not perfect but it works, maybe theres a better name for them though? Take it up on discord.
> 
> Moved from TM since the sword conflicts with the general weapon fix PR that got higher priority. Got several other things to attend to in this PR before it can be merged in any case.


The Grenzelhoffter Greatswordsman is the new name given by people in discord since it sounds more german, landsknecht is too normal? not my taste for it

2024-11-29 08:44 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/zybantine.dm
> +		H.change_stat("constitution", 1)//so they get 3 stat points like anyone else
Comment is wrong, fix it.

2024-11-29 12:30 UTC, NPC1314 commented
Names still coal, needs fix.

2024-11-29 15:13 UTC, Dorodomki commented
> Names still coal, needs fix.

@NPC1314 

wich ones? the grenzelhoft was chosen by pop and the other explain the class a bit

2024-11-30 10:56 UTC, NPC1314 commented
I guess the only truly abominable one is the boltslinger sharpshooter one, though all of them are too wordy and long IMO

2024-11-30 23:26 UTC, NPC1314 approved these changes

2024-11-30 23:26 UTC, merged