Reorganizes Crafting Recipes
Darkrp-community/OpenKeep pull request #1119
Opened 2024-11-17 03:01 UTC by lavillastrangiato

## About The Pull Request

See title. I also edited a few crafting recipes, mostly increasing the skill level. Overall, carpentry and masonry becomes more valuable to have, but not too much.

## Why It's Good For The Game

Mostly for organization purposes, but just generally makes things make more sense.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-11-17 08:05 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/carpentry.dm
> +	craftdiff = 3
Recurve bow, due to its lower damage multiplier, is meant to be a lvl 1 carpentry recipe, not a lvl 3

2024-11-17 08:22 UTC, ThePainkiller requested changes

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 1
```suggestion
	craftdiff = 0
```

No. Please, don't.

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 1
```suggestion
	craftdiff = 0
```
I beg you. Not the floors.

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 2
```suggestion
	craftdiff = 1
```
Please don't. Leave level 2 for the decorated stone walls, if we're getting craftable ones, but don't make masonry impossible to level.

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 2
```suggestion
	craftdiff = 1
```

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 1
```suggestion
	craftdiff = 2
```

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 2
```suggestion
	craftdiff = 1
```

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 2
```suggestion
	craftdiff = 1
```

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/carpentry.dm
> +// Admittedly not too sure why some of these recipes require carpentry skill for steel stuff. You'd have to ask Dromkii.
I asked him to have these require carpentry to make so that they cannot receive smithing modifiers and don't break balance all over the place. Explained a million times for people to stop contributing weapons and armor, yet nobody listens.

2024-11-17 08:22 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/carpentry.dm
> +	craftdiff = 1
```suggestion
	craftdiff = 0
```
Ditto with this one, a fishing rod is so simple to make even a peasant should be able to craft one without much effort. It's just cordage on a stick.

2024-11-17 08:30 UTC, lavillastrangiato commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	craftdiff = 1
I didn't change this one.

2024-11-17 08:31 UTC, lavillastrangiato commented on code/modules/roguetown/roguecrafting/carpentry.dm
> +	craftdiff = 1
Will be done.

2024-11-17 15:52 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	craftdiff = 1
Two craftdiff on composter, also no skillcraft to carpentry.

2024-11-17 17:59 UTC, lavillastrangiato commented on code/modules/roguetown/roguecrafting/structure.dm
> +	craftdiff = 1
It was never meant to be either.

2024-11-19 11:07 UTC, NPC1314 approved these changes

2024-11-19 11:09 UTC, merged