WOKE Stonekeep (Unisex Ruler and "Consort" Role)
Darkrp-community/OpenKeep pull request #1162
Opened 2024-11-26 05:01 UTC by lavillastrangiato

## About The Pull Request

- The role of "King" is now unisex, with "Queen" being its female title. Queen receives everything the King does, like a typical ruler-queen would, it's just the same role.
- The role of "Queen" has been changed to "Consort" and has become unisex as well. Male consorts get the male ruler's outfit sans Serpent's crown/sceptre/cloak/null magic ring.
- In order to not kill a bunch of people's characters, because wow you guys sure do love your elf queens, "King"/Ruler role can now be elves and half-elves. Use this wisely. Or don't, I'm not your community manager.
- "Queen"/Consort can now no longer ready up as Ruler, but they can latejoin. You get access to the vault and the replacement crown if you have the master key or the vault key anyway, so you could be ruler if you really wanted to (Hand can still ready as ruler).
- Slightly rewrites the Ruler/Consort/Hand descriptions.
- Changes the names of some keys and some files for clarity. I didn't fuck with the lord.dm file (yet) because I had a feeling I would miss something and break things.

## Why It's Good For The Game

This is going to be a little long-winded, so bear with me.

In the aftermath of making the game able to start without a ruler and the Hand being able to ready as a "regent", @BadAtThisGame302 suggested that I make Queen a latejoin role. It got me thinking; that would pretty easy to implement, but I'd have to fiddle a bit with the roles. Later, @Cadet00 suggested that the role of Ruler be unisex, and The Role Formerly Known as Queen become something like a "consort", which inspired this PR.

The reason I followed through on it is that we basically have a unisex ruler role anyway, and the only thing separating them is a few skills (which aren't really that consequential), a title (easily editable depending on gender), and some clothing choices. I also heard from a few players that they would have liked the opportunity to play a male consort to a ruling Queen, and to me this seemed like the most logical and fat-trimming way to implement it.

Right now, the way this is coded in its draft state means that you can technically be a ruling couple in a same-sex relationship. I don't really care one way or another, some people like their IC homophobia, some people just wanna have gay sex, I personally think that a consort being the same sex as their ruler is more interesting than gender-locking the roles based on who plays what.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-11-26 09:59 UTC, BadAtThisGame302 requested changes

2024-11-26 09:59 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/nobility/consort.dm
> +- Peasant: A good wholesome peasant spouse. Can cook and swing a pitchfork good. Not so smart or perceptive.
OoOoOooooOoooh you will replace this subclass that doesn't make sense with one from Grenzelhoft oooOoOooOoooOooh

2024-11-26 09:59 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/nobility/consort.dm
> +	else
You really cooked with this. 5 swords if old on the consort is peak... might need a tweak.

2024-11-26 09:59 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/nobility/consort.dm
> +		pants = /obj/item/clothing/under/roguetown/tights/stockings/silk/random
4 swords on the consort nooooo 5 if old honey what are you doing!

2024-11-26 10:07 UTC, lavillastrangiato commented on code/modules/jobs/job_types/roguetown/nobility/consort.dm
> +		pants = /obj/item/clothing/under/roguetown/tights/stockings/silk/random
THAT WAS THERE BEFORE I EDITED IT

2024-11-26 10:40 UTC, BadAtThisGame302 commented
> Honestly Lord / Lady it while at it. 
> 
> King with 2 dudes in his court in a shitty little village is and always was silly

Might need a noble poll again, or even one in announcements for the whole server for that. I made one a while ago but it's outdated and it was inconclusive.

2024-11-26 18:16 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/nobility/consort.dm
> +	title = "Consort"
Lord-Consort/Lady-Consort? Or were we keeping Consort for both genders.

2024-11-26 18:18 UTC, lavillastrangiato commented
@NPC1314 We did poll on that, and people pretty definitively wanted to remain a petty-king/queen.

2024-11-26 18:21 UTC, BadAtThisGame302 commented
> @NPC1314 We did poll on that, and people pretty definitively wanted to remain a petty-king/queen.

![image](https://github.com/user-attachments/assets/0c030f3e-46eb-4b97-95c3-42767f8bd699)

Top one is in #general bottom one is in the noble court.

2024-11-26 18:22 UTC, BadAtThisGame302 commented
But it is 3 months ago so, and things have changed. That's why I suggested a re-do.

2024-11-26 18:25 UTC, lavillastrangiato commented
Jesus Christ I was literally about to correct myself because I remembered it differently.

But I'm not changing it to Lord/Lady because that's dumb.

2024-11-26 18:26 UTC, lavillastrangiato commented on code/modules/jobs/job_types/roguetown/nobility/consort.dm
> +	title = "Consort"
Consort is fine. Just call them Lord/Lady.

2024-11-26 18:35 UTC, NPC1314 commented
I don't feel constrained by a split vote of a handful of guys on discord tbh, go with what inspires you and Ill approve it.
Petty King doesn't even cover it, dude got like 1 servant and 1 retainer, literal hobo, but its your PR, do what you feel is fitting, I do the same nowadays.

2024-11-28 05:46 UTC, lavillastrangiato commented
So, for now, I think what I'm going to do is I am going to make this ready for review as it is. The core of the PR is adding a more varied amount of classes while also leaving things fairly open for interpretation and roleplay.

The Zybantine origin doesn't really add much to the class selection beyond the language gain, so I figured I might as well bite the bullet and remove it. I think if I added something like a language selection to the character setup, then it would do what I wanted with regards to adding background flavour.

2024-11-28 18:06 UTC, Cadet00 commented
> Another option is to turn the Consort class into a more general Noble or Courtier or Councillor or something and let the Ruler marry if they like. Worth thinking on.

I wonder if we could add a way for rulers to choose if they've got a consort or not in their char set up, also I'd ask we maybe do add some race restrictions to consort, mainly Aasimar and Tieflings (drow too maybe... and that one idea of making drow consort a triumph buy would be cool).

2024-11-28 19:50 UTC, lavillastrangiato commented
Consort's already restricted to human, elf, and half-elf...

2024-11-28 20:15 UTC, Cadet00 commented
> Consort's already restricted to human, elf, and half-elf...

I'm blind, I couldn't find it but if it already is then 👍

2024-11-29 09:59 UTC, NPC1314 commented
Being forced to have a same-sex lover against your will feels like a bit of a meme, and a little icky since the ruler don't get a say. Marriages is for show or political all the time and them being loveless has always been commonplace, but a lover/consort isn't like that.

Also with ability to latejoin you get the old classic single ruler marries, then suddenly their consort arrives and starts drama. That kinda works I guess but it could be really annoying with the wrong player combo, the setup is very questionable.

Like I imagine it will go like this:
Player A (ruler) want to do some sort of courting/romance arc with player Bs character (whoever )  but then player C latejoins as consort, expecting to do the old Queen routine or whatever but tied to the Ruler, but turns out theyre a third wheel, gets salty and starts drama to focus back on themselves, ruining things for A and B and anyone participating in the arc. That sort of thing.

Unisex ruler seems good, but the consort concept tied to it not so much, its unclear how to make consort work and not be a meme.

2024-11-29 15:20 UTC, Cadet00 commented
> Being forced to have a same-sex lover against your will feels like a bit of a meme, and a little icky since the ruler don't get a say. Marriages is for show or political all the time and them being loveless has always been commonplace, but a lover/consort isn't like that.
> 
> Also with ability to latejoin you get the old classic single ruler marries, then suddenly their consort arrives and starts drama. That kinda works I guess but it could be really annoying with the wrong player combo, the setup is very questionable.
> 
> Like I imagine it will go like this: Player A (ruler) want to do some sort of courting/romance arc with player Bs character (whoever ) but then player C latejoins as consort, expecting to do the old Queen routine or whatever but tied to the Ruler, but turns out theyre a third wheel, gets salty and starts drama to focus back on themselves, ruining things for A and B and anyone participating in the arc. That sort of thing.
> 
> Unisex ruler seems good, but the consort concept tied to it not so much, its unclear how to make consort work and not be a meme.

Yeah, some players were bringing up not letting consort late join so that it's locked in at round start, it might work esp since then a ruler knows if they're married or not,

2024-11-29 21:45 UTC, lavillastrangiato commented
Sure, I can maybe make it that consort is ready-only, but why is it a "meme" when you're "forced" into a same-sex relationship? Arguably you're "forced" into any other relationship in the current state of things.

The alternative is to code whatever mechanic Shiptest is on when you have to accept an application for someone to join a crew role, but [makes dismissive wanking gesture]

2024-11-30 09:27 UTC, NPC1314 commented
I guess its mostly to do with pivoting the relationship from a possibly political marriage to a more informal/ volontary one, and that has some possibly negative outcomes in various constellations, but it might be worth it for the upsides.

With latejoin disabled for them its possible to hash out some stuff in lobby so that helps a lot.
There is one glaring issue though, we clearly need to modify things so we can have dwarf rulers, but that has to be its own thing since it touches on the heirs etc.

2024-11-30 09:37 UTC, NPC1314 approved these changes

2024-11-30 09:37 UTC, merged