Adds descriptions to utility items and more
Darkrp-community/OpenKeep pull request #119
Opened 2024-06-03 16:09 UTC by BadAtThisGame302

## About The Pull Request

Remakes this PR https://github.com/Darkrp-community/OpenKeep/pull/58 because I fucked it

## Why It's Good For The Game

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-06-09 02:29 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/bait.dm
> +	desc = "Hopefully lickers don't get attracted to this..."
Wonder if with the talks about making "lickers" not so meta'd by people, if this would be good? I don't have an issue with it but it bears question with staff

2024-06-09 02:41 UTC, ThePainkiller requested changes
Some of these descriptions peak so hard.

2024-06-09 02:41 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/natural/wood.dm
> +	desc = "A wooden stake, and it's pointy end!"
```suggestion
	desc = "A wooden stake, and its pointy end!"
```

2024-06-09 02:41 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/needle.dm
> +	desc = "This rough needle can be used to sew cloth and wounds."
```suggestion
	desc = "This rough needle can be used to sew cloth and wounds alike."
```

2024-06-09 02:41 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/ropechainbola.dm
> +	desc = "A heavy steel chain."
Some hint at it being able to be used as cuffs (same for rope above) would be nice tbh

2024-06-09 10:13 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueitems/ropechainbola.dm
> +	desc = "A heavy steel chain."
Used the upstream description

2024-06-09 10:14 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueitems/needle.dm
> +	desc = "This rough needle can be used to sew cloth and wounds."
Done.

2024-06-09 10:14 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueitems/natural/wood.dm
> +	desc = "A wooden stake, and it's pointy end!"
Used the upstream description.

2024-06-09 10:14 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueitems/bait.dm
> +	desc = "Hopefully lickers don't get attracted to this..."
Used the upstream description.

2024-06-09 11:11 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/natural/wood.dm
> +	desc = "A wooden stake, and it's pointy end!"
The upstream description can still have grammatical errors, you know?

2024-06-12 03:00 UTC, Schmorgisborg commented on code/game/objects/structures/maneater.dm
> +	desc = "Green and vivid.. Did I see.. a tendril?"
This will allow players to shift-examine grass and locate man-eaters.
I don't have much of an opinion on that, just a possible oversight I'm bringing up to you.

2024-06-12 03:02 UTC, Schmorgisborg approved these changes
Builds fine, all the grammar proof read well, lots of creative effort.

2024-06-12 15:02 UTC, BadAtThisGame302 commented on code/game/objects/structures/maneater.dm
> +	desc = "Green and vivid.. Did I see.. a tendril?"
It's intended, though I doubt many people examine already.

2024-06-12 20:39 UTC, ThePainkiller commented on code/game/objects/structures/maneater.dm
> +	desc = "Green and vivid.. Did I see.. a tendril?"
I plan to add in the not so far future the option to add extra flavor text to identify these via examine text, locked behind either a perk (to give for ranged oriented classes like Ranger, Rogue, Garrison Archer, Boltslinger) or just through a decent enough PER check.
While not many people examine things in game, this might change with the addition of flavor texts like these, and it will be far more easy to spot maneaters like this once it becomes common knowledge, without having to resort to the "look around" verb, turning it kinda pointless.

2024-06-12 21:16 UTC, BadAtThisGame302 commented on code/game/objects/structures/maneater.dm
> +	desc = "Green and vivid.. Did I see.. a tendril?"
Removed it for now then.

2024-06-12 21:16 UTC, BadAtThisGame302 commented on code/game/objects/structures/maneater.dm
> +	desc = "Green and vivid.. Did I see.. a tendril?"
Removed it for now then.

2024-06-14 18:00 UTC, ThePainkiller requested changes
Polishing the grammar

2024-06-14 18:00 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/magic.dm
> +	desc = "On it's glass depths, you can scry on many unsuspecting beings.."
```suggestion
	desc = "On its glass depths, you can scry on many unsuspecting beings.."
```

2024-06-14 18:00 UTC, ThePainkiller commented on code/game/objects/structures/roguetown/gate.dm
> +	desc = "A steel, strong gate."
```suggestion
	desc = "A strong steel gate."
```
Adjectives follow a very capricious order in english:
Opinion > size > **physical quality** > shape > age > color > origin > **material** > type > purpose

2024-06-15 18:42 UTC, merged