Final part of Stage 1
Darkrp-community/OpenKeep pull request #1254
Opened 2024-12-18 10:07 UTC by Catalaria

# First Part (1/3) of Kaizoku Worldbuilding Content - Stonekeep, by Monochrome9090

*Before I start. I'd like to let an warning for others servers that are not Stonekeep or Warmongers; This project is my baby, don't use my sprites. I don't care about the code, just leave my sprites alone. You can come to my DMs to talk it out and we can settle something.*

> "Even in remote nooks and crannies, wisdom most remote is washed ashore as the tides of the new world subside. Minor powers organize and unite to assert their autonomy against the pressure from Major powers. Heartfelt and the once believed mythological creatures from Fog Islands finally revealed their long-standing partnership, as the unknown disappearance of invading privateers, ships, cargo and the many whys and hows from the past five years become clear - an alliance to keep the major powers at bay, mutual diplomacy unburdened, economy at high, and crisis at low."

---

## This is it, fellows. I've done it.
Even with the many downs and more downs, ditched around and struggling every single second of it, I managed to make content. Of course, it is far too little considering what I've planned for it to be, and with the fact it is largely unfinished, at least it is ready for **TEST MERGING**.

The new races coming on this PR will most likely NOT have more *work* jobs. Part of their balance AND lore is that they are present on Rockhill for fighting duties—either from their family being brought/hired by the Rockhill's lords/the king itself, or by performing demonslaying duties (demons will be brought in the second part of the Kaizoku implementation, and they will become a huge... deadly asset that will surely require at least the presence of Abyssanctum roles to be less deadly to the Playerbase). However, I'm open to the idea for some roles (*Preceptor Sohei*, for example) becoming towner roles instead of adventurers, but that will require balancing for the faction as well.

---

## This PR brings:

### => **Four new races**:
- **Changelings:** (Inspired fully by Japanese/Korean mythology as the Kumiho, Kitsune, Futakuchi-onna and kitsunebi, which the latter will hopefully become actual content about); mask-like faces with stretched lips, predatorial eyes, carnivorous tendencies, small degree of canine traits, and storm-like personalities.
- **Kenku:** (Inspired by Karura, Tengus, and Garudas from Japanese/Buddhist mythology); bird-like people with extremely modular biology in which their wings are an extension of their spine, shoulder blades, or arms (the two latter I plan to make a customizable option). They lost their ability to fly ever since the end of blood apotheosis and have a high capacity to mimic voices.
- **Ogruns:** (Inspired by Onis from Japanese culture and ogres in general); purified orcs who have been brought to the Abyssariad fold ever since the Fishfolk were almost exterminated during the war. Handling the ages with newfound emotions made them incredible struggle artists.
- **Undines:** (Inspired by Kappas, Goblins, and general creatures born out of mischief); tribal folk, allied to Abyssariads but do not belong as one of them. They were enslaved by Grezenholft during the second invasion performed on the Fog Island, but their tribalistic people have been recovered—leaving behind severe hate for humens, which some believe may even be biological.

---

### => **New alternative armors**:
- All Abyssariad guards will receive new armors that portray their ranking, based on a mixture of Japanese-to-Chinese military organization, that better portrays Fog Island's boundaries to ancient-age power structure (China) with a rather late-medieval (Japanese) spin.  
  - *(Town Guard > Ashigaru; Royal Guard > Zamurai; Captain > Court Champion)*
- **Heartfelt Lord**
- **Heartfelt Hand**

---

### => **New bandit role**:
- The **Ronin** as the only bandit role for the Abyssariads, but they have RNG for different weapons as a fate-background on what happened before they reached the island illegally.  
  *(I may allow humans to become Ronins as well, as long there is a way to confirm they are heartfeltean.)*

---

### => **New combat music**:
- Is... is this a reference? *(for bards in case anyone tries it.)*

---

### => **New voices for Abyssariads**:
- Ah come'on. That's CLEARLY a reference. *(I have no regrets.)*

---

### => **Two new mercenaries...?**
- OH NO! THESE ARE JUST CRIMINALS FOR HIRE! The **Pre-Yakuzas**, **Kabuki-maru (Kabuki-monos)** and **Tower-Yakko (Machi Yakko)** are rivals and burakumins with different specializations. If they will fight each other on the streets or work together will depend on the situation—or will they have conflicts with the Abyssariad guards instead?

---

### => **New assets**:
- New clothes and armor influenced by Japanese, Chinese, and Mongolian content. Including even some quite 'underground' types, such as the **Rattan (téng pái)**, which was SURPRISINGLY very effective. *(Hell, Rattan shield can even stop musket bullets, that's an ACTUAL thing.)*
- New weapons, influenced by Ming-Dynasty/Joseon Dynasty and general Japanese weaponry. *(We just don't have a Mongolian bow because we already have them in the code as recurve bow. I still can't understand how these deal less damage since recurve bow is better in general than short bows. It's literally a direct upgrade.)*

---

### => **Abyssor powers for Abyssanctum enthusiasts**:
- I just don't know how to split, or if I even should at this point. I kind of wanted the Abyssanctum Abyssoriates to be different from the Pantheonistic Abyssoriates for the sake of the content I will be making for part two. But Abyssor now has three temporary powers to use.

2024-12-18 10:19 UTC, Catalaria commented
![image](https://github.com/user-attachments/assets/11c943cc-3a11-4b8c-9bcc-edd9234e1699)
I don't get it.

2024-12-18 13:59 UTC, Cre77 commented
the PR that SAVED stonekeep

2024-12-18 15:03 UTC, sanshoom commented
can we get screenshots of the new races? : )

2024-12-18 15:46 UTC, listerla commented on code/__DEFINES/traits.dm
>  	TRAIT_MOB_FIRE_IMMUNE = span_info("I am not easily burned by flames."),
You'll want to move this comma up a line.

2024-12-18 15:48 UTC, listerla commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +/*
Double-commented, meaning there's no close to the comment at the end of the file.

2024-12-18 15:50 UTC, listerla commented on code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
>  		"Aasimar"
Missing a comma here.

2024-12-18 15:52 UTC, listerla commented on code/modules/surgery/organs/tongue.dm
>  		/datum/language/orcish
```suggestion
		/datum/language/orcish,
```

2024-12-18 16:02 UTC, listerla commented
Instances of `CLOTHING_BLACK`, `CLOTHING_RED`, `CLOTHING_PURPLE`, etcetera need to be updated to the changes made here: https://github.com/Darkrp-community/OpenKeep/pull/1036

2024-12-18 16:16 UTC, listerla commented on code/modules/clothing/rogueclothes/storage.dm
> +	new /obj/item/throwing_star/ninja(src)
Can't seem to find `/obj/item/throwing_star/ninja`

2024-12-18 16:23 UTC, listerla commented on code/modules/jobs/job_types/roguetown/peasants/soilson.dm
> +		beltl = /obj/item/rogueweapon/huntingknife/villager
Two beltl objects, one of which doesn't seem to be real (this one.)

2024-12-18 16:23 UTC, listerla commented on code/modules/jobs/job_types/roguetown/temple/acolyte.dm
> +			wrist = /obj/item/clothing/wrists/roguetown/shrinekeeper
```suggestion
			wrists = /obj/item/clothing/wrists/roguetown/shrinekeeper
```

2024-12-18 19:59 UTC, lavillastrangiato commented on code/__DEFINES/traits.dm
Missed a bracket.

2024-12-18 19:59 UTC, lavillastrangiato commented on code/datums/stress/negative_events.dm
"Jeopardous" is a very unusual word to use. Maybe "vicious" or "wretched" might work better in context here.

2024-12-18 19:59 UTC, lavillastrangiato commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/kaizoku/marauder.dm
Should probably be "suffered *in*" or "suffered *under*". "I shall make part in that" should likely be "I shall take part in this" or even "I shall take joy in this".

2024-12-18 19:59 UTC, lavillastrangiato commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/kaizoku/marauder.dm
Grenzelholft > Grenzelhoft
A better way to write the first part of the description would be "Since Grenzelhoft's incursions on the Fog Islands began [...]"

2024-12-18 19:59 UTC, lavillastrangiato commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/kaizoku/marauder.dm
A better way to write this might be "We've suffered under the yoke of humens for ages, and so I hold the banner of my ancestors with all my strength. How long must we suffer war?"

2024-12-18 19:59 UTC, lavillastrangiato commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/kaizoku/marauder.dm
"Pauper", not "paumpers".

2024-12-18 19:59 UTC, lavillastrangiato commented on code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
Might read better as "My honor is forfeit; I have become a tool of cruelty and torture. The swift and merciful death yearned for by my people is no option for me (for this one?). Perhaps one dae my sins will no longer linger."

2024-12-18 21:30 UTC, NPC1314 commented on code/__DEFINES/traits.dm
>  	TRAIT_MOB_FIRE_IMMUNE = span_info("I am not easily burned by flames."),
also lacks a explanation for minced I think?

2024-12-18 21:31 UTC, NPC1314 commented on code/controllers/subsystem/ticker.dm
> +/*
why is this being commented out?

2024-12-18 21:33 UTC, NPC1314 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	gripped_intents = list(/datum/intent/mace/heavy/strike, /datum/intent/mace/heavy/smash)
yep

2024-12-18 21:36 UTC, NPC1314 commented on code/game/objects/items/rogueweapons/melee/special.dm
> +			if(!(H in SStreasury.bank_accounts))
dont think its a good idea to add this back in this PR, rod was changed to only work on the select list of roles for various reasons, its better to leave the system as that for now and not change how it works again on the fly.
Unless there s  a specific reason this is here? It feels like its a copy paste accidental addition?

2024-12-18 21:37 UTC, NPC1314 commented on code/game/turfs/closed/_closed.dm
> +				var/obj/item/offhand = user.get_inactive_held_item()
wuts dis?

2024-12-18 21:40 UTC, NPC1314 commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +
essentially this is just adding the abyssariad bloc before the old one right?
It doesnt change how the old bandit roles are set up yes?

2024-12-18 21:44 UTC, NPC1314 commented on code/modules/clothing/rogueclothes/storage.dm
> +	new /obj/item/throwing_star/ninja(src)
got yeeted I think,, not ever updated to RT code so was kinda busted. Just delete I guess.

2024-12-18 21:53 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/blackoak.dm
> +		"Changeling",
blackoak is the elf class though, not sure the abyssariad races fit here?

2024-12-18 21:54 UTC, NPC1314 commented on code/modules/jobs/job_types/roguetown/other/merc_classes/steppesman.dm
> +		"Aasimar",
not 100% the sea peopels fit the steppeman mongol theme but it could work out!

2024-12-18 22:22 UTC, lavillastrangiato commented on code/datums/components/crafting/crafting.dm
fathom

2024-12-19 05:47 UTC, Catalaria commented on code/modules/jobs/job_types/roguetown/other/merc_classes/blackoak.dm
> +		"Changeling",
Very, very accidental lmao

2024-12-19 05:47 UTC, Catalaria commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +
Quite so, just fixed that one up

2024-12-19 05:48 UTC, Catalaria commented on code/game/turfs/closed/_closed.dm
> +				var/obj/item/offhand = user.get_inactive_held_item()
Something went wrong with the kunai code when merging. I will fix it

2024-12-19 05:48 UTC, Catalaria commented on code/game/turfs/closed/_closed.dm
> +				var/obj/item/offhand = user.get_inactive_held_item()
var/obj/item/offhand = user.get_inactive_held_item()
				if(offhand)
					if(istype(offhand, /obj/item/rogueweapon/huntingknife/kunai))
						myskill += 3
						
						nvm. It's correct.

2024-12-19 05:49 UTC, Catalaria commented on code/controllers/subsystem/ticker.dm
> +/*
Experimental stuff that I forgot to remove. Got it fixed

2024-12-19 05:51 UTC, Catalaria commented on code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
Changed it to "		to_chat(H, "<span class='userdanger'>My honor is forfeit; I have become a tool of cruelty and torture. The swift and merciful death that must be yearned to my victims are no option for me here. Perhaps one dae my sins will no longer linger.</span>")"

Sounds better?

2024-12-19 06:41 UTC, Catalaria commented on code/game/objects/items/rogueweapons/melee/special.dm
> +			if(!(H in SStreasury.bank_accounts))
This is a copy paste accident, yes.

2024-12-23 10:49 UTC, ThePainkiller commented
Once I'm done with christmas I'll give it a play-through and see if all is within balance, otherwise looking good after fixing so many code errors, compiles like a breeze now.

2024-12-31 01:40 UTC, ThePainkiller commented on code/__DEFINES/is_helpers.dm
> +#define isabyssariad(A) (is_species(A, /datum/species/abyssariad))
Just remember that anything that this proc is used for, will also apply for changelings.

2024-12-31 04:18 UTC, Catalaria commented on code/__DEFINES/is_helpers.dm
> +#define isabyssariad(A) (is_species(A, /datum/species/abyssariad))
Yes, that's intended. Dw

2025-01-05 09:40 UTC, ThePainkiller requested changes

2025-01-05 10:02 UTC, Catalaria commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	gripped_intents = list(/datum/intent/dragonslayer/smash, /datum/intent/mace/thrust) //This is practically a mace.
Guts killed a child with a stab attack... that's why I kept the stabby...... his early trauma before the eclipse............. an innocent life taken.............

2025-01-05 10:09 UTC, Catalaria commented on code/__DEFINES/traits.dm
> +	TRAIT_KAIZOKU = "Whether by birth or by learning, I've inherited the Islander ways at cost of the Imperial culture.",
'Instead' is better. Because "my imperial culture' implied one existed to begin with.

2025-01-12 11:27 UTC, ThePainkiller requested changes

2025-01-12 11:27 UTC, ThePainkiller commented on code/modules/mob/living/carbon/human/npc/raider.dm
> +	equipOutfit(new /datum/outfit/job/roguetown/antag/raider/highzamurai/pre_equip)
```suggestion
	equipOutfit(new /datum/outfit/job/roguetown/antag/raider/highzamurai)
```
These no longer exist, are you sure this proc is needed? There is only one `/datum/outfit/job/roguetown/antag/raider/highzamurai` and it doesn't differentiate on the system you used before (tachi, ararebo, etc)

2025-01-23 02:15 UTC, closed without merging