Royal Guard Knighthood (Ser/Dame)
Darkrp-community/OpenKeep pull request #168
Opened 2024-06-12 19:26 UTC by BadAtThisGame302

## About The Pull Request

Gives the Royal Guard the Ser/Dame (because I'm a beast and was the only guy arguing on the Captain PR for it so I did a when you code it moment) honorary like the Captain.

Gives them a better and more luxurious description from a single sentance.

And changes their path from manorguard to royalguard.

## Why It's Good For The Game

Turns the Royal Guard into minature Knights which is based, plus the Captain PR was testmerged for quite afew rounds so people just continue to call Royal Guards with Ser infront of their names. Also gives them a more expanded description to accomodate.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-06-12 20:32 UTC, Schmorgisborg approved these changes
Looks good to me, no compilation errors, and no sneaky additions.
Creative and concise- something we could all do with a little more of.

2024-06-12 22:23 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
> +		var/honorary = "Ser"
Still no idea why — if we're introducing a female title for knight — does the male version have to become a made up gender neutral term. Why not "Sir", as it should befit medieval fantasy, for knights?

2024-06-12 22:24 UTC, ThePainkiller requested changes

2024-06-12 22:24 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
> +	tutorial = "You're an elite member of the Garrison, awarded with a knighthood for your prowess and loyalty. Be a stalwart guardian for the royal family, and serve them until your dying breath."
```suggestion
	tutorial = "You're an elite member of the Garrison, awarded with knighthood for your prowess and loyalty. Be a stalwart guardian for the royal family, and serve them until your dying breath."
```

2024-06-12 22:29 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
> +		var/honorary = "Ser"
I think the title 'Ser' comes from Game of Thrones, which there they are called Sers not Sirs (the knights), so it's a nudge to that medieval sort of fantasy. 

I personally prefer Ser too, it makes it more... homely? It feels like what an uneducated peasant would call an actual Sir Knight.

2024-06-12 22:58 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
> +		var/honorary = "Ser"
Dear god Game of Thrones? I'm gonna be biased on saying this but no wonder it sounded horrible to me, and now I understand **why**.
Peasants, and people on medieval settings would normally use **_"sire"_** instead, which is a literal archaic version of "sir", and more period appropiate. "Ser" sounds like the elder Oblivion beggars muttering on their own version of the english language a misspronunciation of "sir". Yuck.

2024-06-14 03:16 UTC, ThePainkiller requested changes
Since you're, for some reason, also touching `troll.dm`

2024-06-14 03:16 UTC, ThePainkiller commented on code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
>  	remains_type = /obj/item/rogueweapon/battle
```suggestion
	remains_type = /obj/effect/decal/remains/human // Placeholder until Troll remains are sprited.
```

2024-06-14 19:15 UTC, merged