Church, Guard, and code edit
Darkrp-community/OpenKeep pull request #175
Opened 2024-06-13 05:15 UTC by Teragenic

Fixes tabard select color mistype.
Adds one Acolyte slot.
Adjusts torches to avoid it being unable to be relit. Adds a single torch by the Church for ADHD and OCD and symmetry purposes.

2024-06-13 05:16 UTC, Teragenic commented
![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/19d68573-001a-4c80-9e3b-f3c6e6625a73)
Switches unlocked and locked doors.

2024-06-13 05:16 UTC, Teragenic commented
![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/919e49e3-382c-4244-a359-4895d6692695)
![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/2d6063e6-dfee-486d-b989-7b02e6ee42e6)
My testing of that

2024-06-13 05:21 UTC, Teragenic commented
![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/f5e4efb3-fd96-4330-a70c-3778acefa286)
Adds single torch for balance and symmetry of the temple

2024-06-13 05:21 UTC, Teragenic commented
![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/66527fa6-ae64-4f67-a645-b0a0e1caa7e4)
![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/5b2ed008-299c-4a46-b4a2-f3ce13b437c8)

2024-06-13 05:22 UTC, Teragenic commented
Adjusts a torch to be relit during bad Omens.

![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/1b9be8be-7d19-450f-b121-2423e7984d5c)
![image](https://github.com/Darkrp-community/OpenKeep/assets/67575979/89b8b0ac-c253-46b4-995f-660129107fe9)

2024-06-13 05:33 UTC, ThePainkiller requested changes

2024-06-13 05:33 UTC, ThePainkiller commented on code/rt.dm
> +	#define FORCE_MAP "_maps/roguetown.json"
```suggestion
	#define FORCE_MAP "_maps/roguetest.json"
```
You should've undone this change lol

2024-06-14 02:23 UTC, Teragenic commented
I'll update that when I get home :3 my bad.

2024-06-14 02:24 UTC, Teragenic commented
Should be fixed now. My bad

2024-06-14 02:26 UTC, Teragenic commented
Update comment: I also forgot to add the part where I added a bunch of spare Guard Tabards/Jupons/Surcoats to the armory and the Hand's room.

2024-06-14 03:45 UTC, ThePainkiller commented
For future reference: Put the screenshots and proof and such on the **body** of the PR, not on comments, please.
It makes it easier for readability.

2024-06-14 08:25 UTC, Teragenic commented
Firstly, who are you on Discord so I can message and ask about this stuff.
Secondly, sorry first PR on here and it's been a while since I've coded, I've been asking the other devs about this stuff but yeah. I will next time.

2024-06-14 08:33 UTC, ThePainkiller commented
> Firstly, who are you on Discord so I can message and ask about this stuff. 
Hi, it's Nicholas of Ironshard, or #gundamtanaka
> Secondly, sorry first PR on here and it's been a while since I've coded, I've been asking the other devs about this stuff but yeah. I will next time.
No worries! Just take notes so that next time it's a bit more fleshed out properly so it's easy to read and all doccumented, you will get a grasp real fast of how it's done, it's nothing so complicated, I just prefer things to be neat!

And, well, enforcing a standard so that people don't just write meme/salt PR's for the sake of it.

2024-06-15 02:34 UTC, Teragenic commented
Updated title and stuff.

2024-06-15 03:15 UTC, closed without merging