fixes drow accent, changes/fixes word filter
Darkrp-community/OpenKeep pull request #177
Opened 2024-06-13 11:29 UTC by YuiY1997

## About The Pull Request
makes drow accent more phonetically applied instead of word replacement. No more nonbles

Changes word filter to get rid of the "merchantelry" thing and makes saying irl slurs a free frag pass for everyone around you

## Why It's Good For The Game

Makes the french accent generally less meme-y since it was originally made for mimes on /tg/.

Removes unncessary filters that interrupt normal conversation.

Adds filters for netspeak like "cuck" to replace it with lore-friendly versions that mean the same thing.

If people try to say irl slurs, instead of being filtered they scream stuff about being Zizo's servant. This is funny and will hopefully discourage people from using IRL slurs instead of simply filtering it. If they are too uncreative to come up with fictional slurs we will beat them to death with hammers.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-06-13 12:54 UTC, BadAtThisGame302 commented
I'm not really a fan of most of the Drow changes, I got to be honest.

2024-06-13 13:10 UTC, sanshoom commented
“hmm yes, today i will give the race that is known for their cruelty and society built on slaves, a vague german accent.”

what did they mean by this

2024-06-13 14:05 UTC, Teragenic commented
I have one issue. The text is so big for the slurs. Someone who is gonna say those slurs is gonna take up the entirety of the chat box when they spam it.

2024-06-13 14:24 UTC, Stutternov commented
Der Deutsch der Drow ist groß basierend und Deutsch gepillt. Der Drow mag leichen, die spinne, und sterben....

2024-06-13 16:40 UTC, sanshoom commented
why did you turn drows german

2024-06-13 17:44 UTC, YuiY1997 commented
> why did you turn drows german

french also doesn't have the english th sound and so substitute it with Z and S

2024-06-13 17:51 UTC, YuiY1997 commented
> Might just want to outright remove all the slurs from the repo since I think it breaks github's TOS. IIRC TG had their repo shutdown a few years ago over still having slurs remaining in the code.

Asking the dev team about this now

2024-06-14 00:56 UTC, ThePainkiller requested changes

2024-06-14 00:56 UTC, ThePainkiller commented on strings/accent_universal.json
> +		"earth": "Grimoria",
```suggestion
```
Remove this shit, it has been bugging me for so much. I have to say "soil" or "dirt" all the time instead of "consacrated earth" as fucking god intended for that phrase to exist. Nobody refers to the PLANET itself in any way, and Grimoria is a continent inside the whole unnamed world sphere, so it doesn't even stick. Hatred. Gone.

2024-06-14 00:56 UTC, ThePainkiller commented on strings/accent_universal.json
> +		"retarded": "a dullard",
```suggestion
		"retarded": "a natural born idiot",
```
Period appropiate definition (14th century english)

2024-06-14 00:56 UTC, ThePainkiller commented on strings/accent_universal.json
> +		"retard": "dullard",
```suggestion
		"retard": "natural born idiot",
```

2024-06-14 00:56 UTC, ThePainkiller commented on strings/accent_universal.json
> +		" cuck ": "cornuto",
```suggestion
		"cuck": "wittol",
```
Period-appropiate word (c. 1500's)

2024-06-14 17:12 UTC, YuiY1997 commented
Thanks for the suggestions that were true to the period we're trying to have the vibe of

2024-06-14 17:39 UTC, 1N7Slayer reviewed
soul PR tbh

2024-06-14 17:47 UTC, ThePainkiller requested changes

2024-06-14 17:47 UTC, ThePainkiller commented on strings/french_replacement.json
> +		"through": "srough",
```suggestion
		"through": "zrough",
```
For english speakers, this rolls off the tongue more like the intended accent

2024-06-14 17:47 UTC, ThePainkiller commented on strings/french_replacement.json
> +		"throw": "srow",
```suggestion
		"throw": "zrow",
```

2024-06-14 17:47 UTC, ThePainkiller commented on strings/french_replacement.json
> +		"thought": "sought",
```suggestion
		"thought": "zhoght",
```
Gonna be hard to distinguish "thought" and "sought" (as in "sought after") unless we apply accent magic

2024-06-14 17:47 UTC, ThePainkiller commented on strings/french_replacement.json
> +		"with": "wees",
```suggestion
		"with": "weef",
```

2024-06-14 17:47 UTC, ThePainkiller commented on strings/french_replacement.json
>          "wine": "vin"
```suggestion
        "wine": "vine"
```

2024-06-14 17:52 UTC, YuiY1997 commented on strings/french_replacement.json
> +		"through": "srough",
I will keep this one as is to distinguish the difference between unvoiced and voiced th sounds

2024-06-14 17:54 UTC, YuiY1997 commented on strings/french_replacement.json
> +		"throw": "srow",
same as above the voiced/unvoiced th will be kept as is. Otherwise the accent would just seem germanic

2024-06-14 18:14 UTC, ThePainkiller commented on strings/french_replacement.json
> +		"through": "srough",
Yes but there's a difference between ze accent being _"zroo"_ and being _"ssroff"_, hence the z sound making you understand it's under the "th" sphere and not a mixed "s'rough" as in _"it's rough"_

2024-06-14 19:04 UTC, YuiY1997 commented on strings/french_replacement.json
> +		"through": "srough",
if you think it's important for people to be able to understand it I'll add it

2024-06-14 19:16 UTC, SELFHELL commented
The new drow replacements look more memey than the original ones truth be told. Besides that, I'd probably atomize the PR and split up the french/normal accent changes

2024-06-15 13:00 UTC, NPC1314 commented
Not sure what direction dark elf accents should go, if it even remains, but the ee:s strike me as more of a Tief thing, 
v instead of w gives german/grenz vibes, just adding z:s is a bit meh, its not obvious whats right for them, but I get the sense this is not it, needs a bit more cooking IMO

2024-06-16 10:26 UTC, YuiY1997 commented
> Not sure what direction dark elf accents should go, if it even remains, but the ee:s strike me as more of a Tief thing, v instead of w gives german/grenz vibes, just adding z:s is a bit meh, its not obvious whats right for them, but I get the sense this is not it, needs a bit more cooking IMO

Have you maybe thought that the commonality between Tiefling and Drow accents might be because they are both based off of ROMANCE LANGUAGES? There are also no W -> V replacements in the strings, as you can see if you look at them. The only one that seems like this is Vin, and that's JUST the french word for wine.

I have only replaced th with Z and S because French does not do the English th voices and unvoices th sound the same way, and native french speakers when speaking english often substitute unvoiced th sounds with S and voiced TH sounds with Z. Everything else reflected in the strings is simply a difference in the kinds of vowel pronunciation used in French vs english.

2024-06-17 04:15 UTC, Plaguewalker commented
Personally, just mix both and go full french

2024-06-23 23:29 UTC, Stutternov approved these changes

2024-06-23 23:29 UTC, merged