Tweaks Padded Dress Crafting
Darkrp-community/OpenKeep pull request #221
Opened 2024-06-20 12:15 UTC by OctusGit

## About The Pull Request

The padded dress being in sewing and being so cheap to make despite its insane stats and coverage feels like an oversight. It deserves way more work and material to make given it is the clothes of queens and royals. Its now in weaving, needs silk, and actually has a sellprice now.

## Why It's Good For The Game

Outfit of queens and royals being basic sewing is not good and reflective of its protection and quality.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-06-20 17:11 UTC, ThePainkiller commented
If it's the clothing of queens and kings, why is it on the blacksmith's closet?

2024-06-20 17:13 UTC, ThePainkiller requested changes
Silk? Not what things with armor values are made of.

2024-06-20 17:13 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/weaving.dm
> +				/obj/item/natural/silk = 5)
This is **not** royal clothing, and these are **padded** so it makes no sense to replace cloth with silk. At the very least cloth and hide make more sense than this. We **do** want more uses for silk, but this is definitely not one of them.

2024-06-20 23:03 UTC, OctusGit commented on code/modules/roguetown/roguecrafting/weaving.dm
> +				/obj/item/natural/silk = 5)
Ok ive made changes, it now uses hide and has a higher material cost and crafting diff.

2024-06-20 23:08 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/sewing.dm
> +				/obj/item/natural/hide = 4)
4 hides is insane. You do realize this dress was nerfed to the ground and you're making it literally not worth crafting over a leather/hide armor?
In fact, screw it, make it 4 silk 1 hide 2 fibers, since someone already changed the description to it being worn by nobility and the queen wears one, so at LEAST some silk, but for its armor values this is INSANE. Craftdiff is also insane, don't make it past 4 please. Nobody will want to do this shit if you make it so costly for so little return.

2024-06-20 23:11 UTC, OctusGit commented on code/modules/roguetown/roguecrafting/sewing.dm
> +				/obj/item/natural/hide = 4)
Ok thats fine I can do that

2024-06-20 23:33 UTC, ThePainkiller approved these changes

2024-06-22 23:50 UTC, Stutternov approved these changes

2024-06-22 23:50 UTC, merged