Weaponsmith now has same allowed list for races & gives him engineering
Darkrp-community/OpenKeep pull request #232
Opened 2024-06-22 02:22 UTC by Technobug14

## About The Pull Request
It makes no sense the armorer role allows ALL races, but weaponsmith does not. Also gives the weaponsmith engineering which, arguably, he has more use of, since engineering is really only for fortifications and fire arrows/bolts.

## Why It's Good For The Game
Fixes an inconsistency.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-06-22 02:23 UTC, Technobug14 commented
This is a very simple PR. I'd honestly fucking sob if it runtimed or had errors, it certainly shouldn't. It's TWO lines of code.

2024-06-23 00:02 UTC, ThePainkiller requested changes

2024-06-23 00:02 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/serfs/blacksmith.dm
> +		H.mind.adjust_skillrank(/datum/skill/craft/engineering, rand(2,4), TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/craft/engineering, pick(1,1,2), TRUE)
```
Engineering is a skill geared more towards the Mason (construction of levers and mechanisms) than a weaponsmith, and thus they should have at least a MINIMUM level of it to be able to at least make levers and stuff. Besides, with the inclusion on my earlier PR of craftable flints at 0 craftdiff, they CAN level it up even further. Let's not get out of hand.

2024-06-24 03:06 UTC, Technobug14 commented
Added your suggestion, even 1 in engineering should be plenty for the weaponsmith to do what they need.

2024-06-24 04:10 UTC, ThePainkiller approved these changes

2024-06-25 14:21 UTC, Stutternov approved these changes

2024-06-25 14:21 UTC, merged