Gravedigger Nature Healing + Mason + Miner Update
Darkrp-community/OpenKeep pull request #237
Opened 2024-06-22 22:11 UTC by Dorodomki

## About The Pull Request

Adds a new set of sprites for the Shovels, Fixes their allignments and Re Adds the Chopping attack for the Gravediggers + adds them average skill with polearms (they are people who lives using that tool)

 (the chopping attack is the same as an stone axe for balance reasons, iron axe chopping made it be an iron axe as a tool and wasn't fair)

The mason Gets A Drippy Leather Vest, Lamptern, Flint,  hunting Knife to work Better at gathering materials since they are one main building role and not a towner with less tools

The Miner Gets a Lamptern To Illuminate their Ways (be on the mines is his profesion, why they never had a Lamp with them?)

## Why It's Good For The Game

Fixes an issue we had for a long time, adds more sprite quality and adds some fair balances on different jobs

![Captura de pantalla (1789)](https://github.com/Darkrp-community/OpenKeep/assets/128561204/d0aa4c49-2e10-40c8-8c7e-e884a62988f5)

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-06-23 04:19 UTC, ThePainkiller requested changes

2024-06-23 04:19 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/gravedigger.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/polearms, 2, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/combat/polearms, 1, TRUE)
```
Non-combat class.

2024-06-23 04:19 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/serfs/mason.dm
> +	backpack_contents = list(/obj/item/roguekey/mason = 1, /obj/item/flint = 1, /obj/item/rogueweapon/huntingknife = 1, /obj/item/flashlight/flare/torch/lantern)
```suggestion
	backpack_contents = list(/obj/item/roguekey/mason = 1, /obj/item/flint = 1, /obj/item/flashlight/flare/torch/lantern)
```
No free weapon for no particular reason at all. Backpacks also hold up to three items, not four.

2024-06-23 04:19 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/serfs/mason.dm
> +	armor = /obj/item/clothing/suit/roguetown/armor/leather/vest
```suggestion
	armor = /obj/item/clothing/suit/roguetown/armor/workervest
```
Not a combat class. No armor, only towner clothes.

2024-06-23 04:19 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/gravedigger/tools.dm
> +	possible_item_intents = list(/datum/intent/mace/strike/shovel, /datum/intent/axe/chop/stone)
```suggestion
	possible_item_intents = list(/datum/intent/mace/strike/shovel)
```
Chop intent on onehanded only for items that can't be dual handed. Read, hunting knife.

2024-06-23 04:48 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/serfs/mason.dm
> +	backpack_contents = list(/obj/item/roguekey/mason = 1, /obj/item/flint = 1, /obj/item/rogueweapon/huntingknife = 1, /obj/item/flashlight/flare/torch/lantern)
the knife goes for the reason of chop wood, isn't the same as an axe for round start but allows them to collect wood without craft a stone knife 
![Captura de pantalla (1789)](https://github.com/Darkrp-community/OpenKeep/assets/128561204/42a02199-92f4-46fe-9217-a5e9b2a8e3fe)

the backpack can hold the starting items totally fine

2024-06-23 04:57 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/serfs/mason.dm
> +	backpack_contents = list(/obj/item/roguekey/mason = 1, /obj/item/flint = 1, /obj/item/rogueweapon/huntingknife = 1, /obj/item/flashlight/flare/torch/lantern)
They're masons, not carpenters.
They work stone and cogs, not wood.
Still a No on the hunting knife.

2024-06-23 05:09 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/serfs/mason.dm
> +	backpack_contents = list(/obj/item/roguekey/mason = 1, /obj/item/flint = 1, /obj/item/rogueweapon/huntingknife = 1, /obj/item/flashlight/flare/torch/lantern)
i guess i got to map some axes for them to collect wood, dakkatown already has a few

2024-06-23 06:37 UTC, NPC1314 commented
This is mixed in a bit with #216, since it touches the same .dmi files

2024-06-23 06:38 UTC, Dorodomki commented
> This is mixed in a bit with #216, since it touches the same .dmi files

unironically true, the inhands resprite should have been merged a while ago to keep the game updated and allow this to be merged quicker too :sadcat:

2024-06-26 13:32 UTC, Stutternov approved these changes

2024-06-26 13:32 UTC, merged

2024-06-26 14:21 UTC, NPC1314 commented
Check the icondiffbot, inhand shoveldirt in 64.dmi has a flicker issue, needs a hotfix