Eoran Acolytes & Misc Church Changes
Darkrp-community/OpenKeep pull request #257
Opened 2024-06-27 22:26 UTC by SELFHELL

## About The Pull Request

Adds Eora Acolytes to the game and associated spells + sprites.

![Eoran](https://github.com/Darkrp-community/OpenKeep/assets/99771731/c2bfd912-8d03-427d-b260-8f6b3bc3a82f)

Credit to monochrome9090 for all of his work on the sprites

Additionally **SEVERELY** increases the punishment that Churchmen get for breaking their oath of celibacy,
Court Wizards as well, since purity past the age of thirty is the root of their magical skill.

## Why It's Good For The Game

Helps expand upon the church and the roleplay opportunities for people. Also provides more options

Besides expanding on the church, the other changes should help ensure people **dont** be total harlots on church roles or Court Wizard.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-06-28 03:51 UTC, RoboticVodka commented on code/datums/status_effects/rogue/debuff.dm
> +	effectedstats = list("intelligence" = -10)
It is a bit silly to imply having sex makes you stupider than the average peasant. Might wanna bring it to around -5 or even -6 to be in line with the debuff for acolytes and probably bring them down to about average intelligence.

2024-06-28 05:17 UTC, ThePainkiller commented on code/datums/gods/patrons/divine_pantheon.dm
> +	sins = "Sadism, Celibacy, Ruining beauty"
You do understand that "sins" means "what the god/ess" dislikes", right?
And Eora dislikes celibacy, which means their acolytes must have the love fiend perk at least, rather than receive a debuff because they fucked as an acolyte?

2024-06-28 05:19 UTC, DAKKA-WAAAGH commented
I love the additional flavor for the clergy members to enjoy, it's been found lacking for a long while now!

However, forced in-game celibacy isn't exactly desirable, so I'm opposed to it and especially anything that worsens it. I think it should be up to the players whether or not their character spawns in as celibate. Of course, this would take more effort to do and the celibacy should be peeled back for the time being until such an option appears.

I guess an argument could be made for "in-lore" reasons for forced celibacy, but it's been repeatedly stated that the lore is purposefully open and generally free to interpretation. I would love to hear more thoughts on this.

2024-06-28 06:49 UTC, sanshoom commented
These are just my thoughts but it doesn't really make sense to punish Eoran acolytes for having sex, when CELIBACY is literally considered a sin by Eora herself.

2024-06-28 06:53 UTC, NPC1314 commented
Sin punishments should be a thing tbh, but they should reflect the patron. Might be an issue with how Eoran lore specifics are detailed though, Eoran priests can be cool but theres an obvious risk of it sliding into gooning at the expense of priesting.
Needs a bigger discussion to hash it out on discord probably, comments wont cut it, just atomize that part.

2024-06-28 16:37 UTC, SELFHELL commented
> Sin punishments should be a thing tbh, but they should reflect the patron. Might be an issue with how Eoran lore specifics are detailed though, Eoran priests can be cool but theres an obvious risk of it sliding into gooning at the expense of priesting. Needs a bigger discussion to hash it out on discord probably, comments wont cut it, just atomize that part.

Ill take your advice and atomize it, probably shouldnt have put this change in the PR

2024-06-28 20:20 UTC, Stutternov commented
Tbh I don't know if we should reduce the authority of the priest more ti any acolyte being able to do marriages. Priest is already pretty replaceable sadly.

2024-06-28 20:59 UTC, sanshoom commented
Acolytes should encourage love, but they shouldn't be able to have someone married.

2024-06-29 00:42 UTC, SELFHELL commented
> Tbh I don't know if we should reduce the authority of the priest more ti any acolyte being able to do marriages. Priest is already pretty replaceable sadly.

Yeah... fair point

2024-06-29 03:11 UTC, ThePainkiller commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		ADD_TRAIT(target, TRAIT_LIMPDICK, TRAIT_GENERIC)
Why would Eora curse you to not be able to fuck? Shouldn't this be Noc's punishment????

2024-06-29 11:50 UTC, sanshoom commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		ADD_TRAIT(target, TRAIT_LIMPDICK, TRAIT_GENERIC)
Like I said, I reaaaallly think punishing acolytes of EORA for this should be removed.

2024-06-29 20:31 UTC, SELFHELL commented
Alright.. I believe this is ready for a proper TM now

2024-06-29 21:33 UTC, ThePainkiller requested changes

2024-06-29 21:33 UTC, ThePainkiller commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		target.visible_message("<span class='info'>A purple haze shrouds [target]!</span>", "<span class='notice'>I feel much calmer</span>")
```suggestion
		target.visible_message("<span class='info'>A purple haze shrouds [target]!</span>", "<span class='notice'>I feel much calmer.</span>")
```

2024-06-29 21:33 UTC, ThePainkiller commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		target.apply_status_effect(/datum/status_effect/buff/drunk)
Have you tested for **how long** does this give them the debuff?

2024-06-30 00:09 UTC, SELFHELL commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		target.apply_status_effect(/datum/status_effect/buff/drunk)
Yep, the druqks/High Status effect lasts for two minutes, while the less impactful drunk one lasts twelve.

2024-06-30 00:16 UTC, ThePainkiller commented on code/modules/spells/roguetown/acolyte/eora.dm
> +		target.apply_status_effect(/datum/status_effect/buff/drunk)
Fair amount of time, excellent!

2024-06-30 00:17 UTC, ThePainkiller approved these changes

2024-06-30 00:17 UTC, ThePainkiller commented on code/modules/spells/roguetown/acolyte/eora.dm
> +	name = "Eoras Curse"
```suggestion
	name = "Eora's Curse"
```

2024-06-30 18:48 UTC, Stutternov commented
Set for Testmerging.

2024-07-01 11:27 UTC, Stutternov commented
Seems like it's working fine. Fox conflicts for merger.

2024-07-01 21:04 UTC, SELFHELL commented
conflicts? GUH

2024-07-01 21:07 UTC, merged