When the Commoner learns to read, or how I burned books in the village square
Darkrp-community/OpenKeep pull request #283
Opened 2024-06-30 18:53 UTC by BadAtThisGame302

## About The Pull Request

Ports this PR, https://github.com/Blackstone-SS13/BLACKSTONE/pull/1324 allowing people to train their reading.

Also adds more craftable items, like a mortar and pestle, candle, mantrap, rope belt, scrolls and the reading books.

## Why It's Good For The Game

More craftable items plus finally having the ability to learn how to read.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-06-30 22:25 UTC, ThePainkiller requested changes

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage = "unties"
```suggestion
	verbage = "untie"
```

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage_simple = "untie"
```suggestion
	verbage_tp = "unties"
```
I beg you, don't just 1:1 port and localtest your PR's. This is a variable we don't have. I coded the verbage_tp to be the third person version of the verbage, while Blackstone did the opposite.

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage_simple = "untie"
```suggestion
	verbage_tp = "unties"
```

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage = "unties"
```suggestion
	verbage = "untie"
```

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage_simple = "untie"
```suggestion
	verbage_tp = "unties"
```

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage = "unties"
```suggestion
	verbage = "untie"
```

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage = "put together"
```suggestion
	verbage = "put together"
	verbage_tp = "puts together"
```

2024-06-30 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "scroll of parchment (x5)"
```suggestion
	name = "parchment scroll x5"
```
Parenthesis is only reserved for additional items required and only for blacksmithing recipes

2024-06-30 22:28 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "scroll of parchment (x5)"
It's a scroll, not parchment.

2024-06-30 22:28 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/items.dm
> +	verbage = "put together"
Done.

2024-06-30 22:30 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "scroll of parchment (x5)"
Fixed.

2024-06-30 22:33 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "scroll of parchment (x5)"
Parchment and scroll are synonymous, the only difference is that scroll is used when it's rolled up, but it is still a parchment when it unfolds.
material > object is also proper english grammar. If you google "scroll of parchment" you'll also realise most pages use "parchment scroll" or "paper scroll", rather than "<object> of <material>" in this case.

2024-07-03 23:39 UTC, ThePainkiller commented
This change is excellent and sets a solid base ground to work Archivist/Scribe into an actual good position as someone who could print training books for people to train in theoretical use of skills (Experience until level 1, as that'd just be THEORY)
Either that or making the church (as it is historically) the highest level of reading education, theological texts having the highest difficulty level to read.

2024-07-06 21:05 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/literary.dm
> +		var/intbonus = H.STAINT - 10
Remind me add the "boon" mechanic to this one as well once it gets implemented

2024-07-06 21:40 UTC, ThePainkiller requested changes

2024-07-06 21:40 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/literary.dm
> +	exppercycle = 8
```suggestion
	exppercycle = 10
```

2024-07-06 21:40 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/literary.dm
> +	exppercycle = 13
```suggestion
	exppercycle = 25
```

2024-07-06 21:40 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/literary.dm
> +	exppercycle = 20
```suggestion
	exppercycle = 35
```

2024-07-06 21:40 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/literary.dm
> +	exppercycle = 30
```suggestion
	exppercycle = 50
```

2024-07-06 21:40 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/reagent_containers/food/snacks/fat = 2)
```suggestion
	reqs = list(/obj/item/reagent_containers/food/snacks/fat = 1)
```
TWO fat for ONE candle is too steep

2024-07-06 21:40 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	subtype_reqs = TRUE //Unsure if needed for stone knife to work, feel free to remove this if not.
Have you **TESTED** this locally to see if this var is required or not? Because I believe it needs to be FALSE. Can you please localtest and tell?

2024-07-06 21:40 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +/datum/crafting_recipe/roguetown/readingscroll
These might get moved to either church exclusive (privilege of reading texts in ancient languages) or archivist exclusive on the near future, but for now I'll allow it

2024-07-11 00:55 UTC, Stutternov commented
Looks interesting; test this out when you have time and are able, then @ me when it's good for server-side testing.

2024-07-11 13:43 UTC, BadAtThisGame302 commented
> Looks interesting; test this out when you have time and are able, then @ me when it's good for server-side testing.


![image](https://github.com/Darkrp-community/OpenKeep/assets/79063506/732ceda3-76ec-4a1f-8191-9231335382d9)

2024-07-11 13:46 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/items.dm
> +	subtype_reqs = TRUE //Unsure if needed for stone knife to work, feel free to remove this if not.
It works with all the huntingknife subtypes that I tried,.

2024-07-13 16:53 UTC, Stutternov approved these changes

2024-07-13 16:53 UTC, merged