Minor skill and stat tweaks for Prisoner, Dungeoneer
Darkrp-community/OpenKeep pull request #299
Opened 2024-07-02 20:55 UTC by Wesreidau

Prisoner receives Reading, Knives, physical stat tweaks. Better perception and int, reduced strength. Dungeoneer receives Reading.
Both receive tutorials that are more character-neutral.

## About The Pull Request

The Prisoner has the Noble trait by default, yet is illiterate. The Dungeoneer is also illiterate. By allowing the prisoner to read and write, he can engage in sending and receiving letters, reading books, or otherwise behave as a captured noble. By allowing the dungeoneer a reading skill of 1, he can check the prisoner's mail or receive secret requests for ransom and betrayal.

The prisoner formerly had an increased strength of 1, this is changed to -1 due to malnutrition. The prisoner also now has knife skill of 2, so they can find a shiv and try to stick the guard. The prisoner also has his perception increased as it is a mental stat and his physical stat block is very poor.

Additionally the role tutorial has been updated per Rebel0's wishes to provide a broader scope of choices in a character's behavior. The prior text dictated conduct too much to the player and suggested a very one-note character.

## Why It's Good For The Game

By improving the skills and broadening the background of prisoner and dungeoneer we allow a more varied experience for players and permit them to engage in more dynamic stories.

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

2024-07-03 09:38 UTC, ThePainkiller commented
I would suggest while at it, to give prisoners at least minimal athletic skills, to help them run fast should they be able to escape, other than that, this is a very sensible change I have no qualms with

2024-07-03 18:00 UTC, Wesreidau commented
> I would suggest while at it, to give prisoners at least minimal athletic skills, to help them run fast should they be able to escape, other than that, this is a very sensible change I have no qualms with

I am not opposed to this on gameplay grounds, but I am opposed on reason; the prisoner has been stuck indoors for a very long time, so being athletic doesn't suit their physical frailty. I'd make the change if it meant approval, however.

2024-07-03 18:56 UTC, ThePainkiller commented
Oh no it's not a requirement for approval or anything, that was just a suggestion from me to give them an easier time considering their skills are indeed trash, but you raise a solid point there (it's also the reason why they get minus STR, CON and all that, so it tacks) so it's fine as-is

2024-07-03 19:10 UTC, ThePainkiller requested changes

2024-07-03 19:10 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/knives, 2, TRUE) // given Noble trait it was this or sword. N.
```suggestion
		H.mind.adjust_skillrank(/datum/skill/combat/swords, 1, TRUE) // Nobles trained in sword use, but only as an obligation
```
Now this one is that I have an issue with, considering I gave Noble role a 1 in swords (if memory serves)
I suggest leaving 2 for minimal combat classes, a noble might know how to swing a sword but only out of their duties, not on the same level as people that have experience fighting and killing other people

2024-07-03 19:43 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/knives, 2, TRUE) // given Noble trait it was this or sword. N.
I would do both knife and sword. Perhaps 1 knife, 2 sword, so they have an 'upgrade path' if they break out, or keep the knife skill. A lot of mental preparation and pure adrenaline would go into any time the prisoner got their hands on a knife and wanted to use it.

2024-07-03 19:51 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/knives, 2, TRUE) // given Noble trait it was this or sword. N.
If we want to go further on this, the dungeoneer might get 2 crossbow, since the Dakkatown map has him holding a tower outpost and that skill will doubtlessly be needed.

2024-07-03 21:46 UTC, Optimism333 commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/knives, 2, TRUE) // given Noble trait it was this or sword. N.
The sword skill could be randomized a little, perhaps. If the intent of the pr is to push prisoner down the path of nobility while leaving it a bit up in the air to interpret what sort of noble they were. Perhaps they saw their fair share, or perhaps they did in fact swing a sword for nothing more than ceremony.

2024-07-03 21:53 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/knives, 2, TRUE) // given Noble trait it was this or sword. N.
@Optimism333 If you could please look at my rebalance PR, 3 (`Skilled`) is reserved for towner guard (actually skilled fighter), weapon skill 2 (`average`) for combat classes (Warrior et al), and level 1 (`Weak`) for normal people that know _"a sword is a long stick of metal with a sharp point, that if you swing it towards people it hurts them"_.
These nobles fall into the later category and therefore will not get past skill level 1 (Weak). There is no bargaining nor randomizing of skills. Non combat skills get 1 level as a flavor thing more than actual combat utility. No way in Zizo they're getting even a **chance** at lvl 3.
Player interpretation of classes is fine, but this is also a game, with standards for balance, and I can assure you that the only difference is a time sink of hitting training dummies until you get better. Can't have a literal prisoner be at the same level of combat expertise as a town guard.

2024-07-03 22:21 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/knives, 2, TRUE) // given Noble trait it was this or sword. N.
Then 1 knife and 2 sword since they are normal, noble people and the sword is a nobleman's weapon while 1 knife is a normal person's understanding of a knife. I do not follow insisting the prisoner has a non-combat background, they are a noble 'drifter' of sorts and its unlikely they can even get their hands on a blade. The changes to combat stats was per this note.
![image](https://github.com/Darkrp-community/OpenKeep/assets/14954656/343ab443-d9b2-41ce-b668-092cfd77b209)

This is not a -prisoner-. This is a -noble- who is now imprisoned. We have to assume they've got the usual upbringing of the rest of the royals, somehow, and this is a small token to suggest they used to use a nobleman's weapon. It opens a lot of character opportunity to a class currently limited to sitting in a box and being brutalized. Prisoners get to make up their own story and this gives them another direction that story might go; the king grants a trial by combat for their freedom, and the odds aren't wholly impossible.

2024-07-03 22:24 UTC, Optimism333 commented
So as not to clog review space, will also put my other suggestion here. Since many noble roles have riding skill, could give a little to the prisoner for flavor. Perhaps a saiga race for freedom? Could be a neat little detail.

2024-07-03 23:36 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/knives, 2, TRUE) // given Noble trait it was this or sword. N.
I don't know how to break this out politely in any other way possible but skill level 2 on weapons is, and will remain, a no.
We pan balance for generalized scenarios, not for very specific niche scenarios that people may or may not play out 100% of the time.

2024-07-03 23:37 UTC, ThePainkiller commented
> So as not to clog review space, will also put my other suggestion here. Since many noble roles have riding skill, could give a little to the prisoner for flavor. Perhaps a saiga race for freedom? Could be a neat little detail.

I second the minimal riding skills. Most nobles moved by horse more than they walked, so if the prisoner is of noble blood/trait, they should get at least some riding skill.

2024-07-04 02:59 UTC, Wesreidau reviewed
Following feedback regarding the initial tweak

2024-07-04 03:04 UTC, ThePainkiller commented
Update to master branch if possible please, looks good!

2024-07-05 20:17 UTC, Stutternov approved these changes

2024-07-05 20:21 UTC, Stutternov commented
Suggestion was applied; not sure why it's giving a merge block but I'm going to override it given the requested change was put through.

Next time if you agree to the convo just press 'commit suggestion' and it'll change the line, otherwise they have to go and undo their review. Seems like it's handled though and it was done, so merging.

2024-07-05 20:21 UTC, merged