Nitemaiden Tweaks
Darkrp-community/OpenKeep pull request #304
Opened 2024-07-03 17:15 UTC by Max-023

## About The Pull Request
Adds a title for the male characters that is more befitting for them.

## Why It's Good For The Game
Because the big burly men offering shoulder rubs deserve representation.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-07-03 17:21 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +		"Dwarf",
This is unbelievably cursed.

2024-07-03 17:24 UTC, Stutternov commented
fails to compile, L

2024-07-03 17:51 UTC, Max-023 commented
> fails to compile, L

Fixed now, nerd

2024-07-03 19:26 UTC, ThePainkiller requested changes

2024-07-03 19:26 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +	title = "Nitebachelor"
Big yikes on using "bachelor" for a position about gucking.
During early and late medieval times, "bachelor" was reserved for young knights (which were not yet part of any order of chivalry) and young members of artisan or merchantry guilds. It not only feels weird to put this title on a whore, but this is also the equivalent of _"I just turned eighteen so I'm legal"_.
I understand _"maiden"_ is not an apt title for literal prostitutes as it implies virginity, so how about just naming them _"Bathmaids"_ instead? Hell even the job description paints them as _"bathwenches"_.

2024-07-03 19:39 UTC, Max-023 commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +	title = "Nitebachelor"
Maiden was also the term for young women as well, so I'm confused as to why now this is suddenly an issue. Regardless, I can look for terms better suiting the whores that is a bit more subtle.

2024-07-03 21:01 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +	title = "Nitebachelor"
It's not that it's "an issue", maiden literally meant back then "a virgin woman", which is counterintuitive considering they most definitely are not lmao
Like I said, bathmaid or bathwench is fine, think like Kingdom Come Deliverance.

2024-07-04 03:22 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +		"Dwarf",
Oy voold eou leek a sveeedish massaaage?

2024-07-04 03:23 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +	title = "Nitebachelor"
I agree 'maiden' doesn't make sense compared to something like nite-wench or bath-wench. The masculine would be nite-servant or bath-servant, imo.

2024-07-05 10:58 UTC, DAKKA-WAAAGH commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +	title = "Nitebachelor"
Could just call them whores or prostitutes, dunno why it needs to be complicated. It's a brothel, whores work at brothels.

2024-07-19 19:15 UTC, Stutternov commented
Hasn't been updated upon review; re-open if work continues outlined above.

2024-07-19 19:15 UTC, closed without merging