QoL
Darkrp-community/OpenKeep pull request #367
Opened 2024-07-12 20:03 UTC by casualspacestation14enjoyer

## About The Pull Request

## Why It's Good For The Game

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-07-12 21:16 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/roguetown.dm
>  		if(H.dna)
The check right above this is also broken, anyway to fix it?

2024-07-14 09:06 UTC, ThePainkiller requested changes

2024-07-14 09:06 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/dbomb.dm
> +			H.mind.adjust_skillrank(/datum/skill/craft/blacksmithing, 3, TRUE)
This class is unused and legacy, unactive, and even if it were, you're out of your mind by making them "blacksmith but better"

2024-07-14 11:04 UTC, casualspacestation14enjoyer commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/dbomb.dm
> +			H.mind.adjust_skillrank(/datum/skill/craft/blacksmithing, 3, TRUE)
blacksmithing set to 1 and added weaponsmithing

2024-07-14 11:05 UTC, casualspacestation14enjoyer commented on code/modules/cargo/packsrogue/food.dm
> +	name = "Ratkept Onin Cognac"
its small lore about rats being the one that kept it safe in a cellar to save it from being stolen by beggars breaking into it

2024-07-15 16:12 UTC, casualspacestation14enjoyer commented on code/modules/cargo/packsrogue/food.dm
> +	name = "Ratkept Onin Cognac"
it has been written  on the bottle

2024-07-23 05:30 UTC, ThePainkiller submitted a review, later dismissed

2024-07-23 05:30 UTC, ThePainkiller commented on code/game/objects/structures/fluff.dm
> +	var/random_message = pick("you spin the globe!", "You land on Rockhill!", "You land on Zybantine!", "You land on port Ice cube!.", "You land on port Thornvale!", "You land on grenzelhoft!")
```suggestion
	var/random_message = pick("you spin the globe!", "You land on Rockhill!", "You land on Zybantine!", "You land on port Ice cube!.", "You land on port Thornvale!", "You land on Grenzelhoft!")
```

2024-07-24 17:14 UTC, Stutternov approved these changes

2024-07-24 17:14 UTC, merged