DEUS VULT
Darkrp-community/OpenKeep pull request #373
Opened 2024-07-13 19:03 UTC by SELFHELL

## About The Pull Request

Removes Confessors,
Replaces them with Templars. 
There is templars for every religion with acolytes, save for eorans because lore:tm:

![Astratan](https://github.com/user-attachments/assets/b55bf6d3-a22a-49d7-ac8f-61ee7e53674f)
![Nocian](https://github.com/user-attachments/assets/39292b43-d813-4a85-8640-ac76cfa8097c)
![dendorian](https://github.com/user-attachments/assets/99adbcaf-c71a-47ca-a712-845fd43dcc23)
![necran](https://github.com/user-attachments/assets/fb03cc5a-af71-489b-ab52-d163a1aac5ca)

## Why It's Good For The Game

First and foremost, Confessor was an entirely unused role which functioned as a second puritan; a role that is ALREADY extremely unused. No one was playing it, nor will it be missed. 

Second, the church has always SEVERELY lacked any protection/way to enforce the will of the Priest besides the occasional migrant which severely limits their political power within the town. Templars will allow the church to actually exert itself and hopefully make it more then just SS13 Medbay.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-07-13 20:07 UTC, DovaKitty commented
Male Aasimar Templar:
+2 ST
+3 PER
+3 INT
+2 CON
+3 END
-1 SPD
+1 Fortune
2 slots with heavy armor training. This would be a problem.

2024-07-13 20:13 UTC, DovaKitty commented
Also, it looks like this PR replaced confessor's ability to send confessions with templar. Templars don't have the ability to do torture or work for the Puritan (who the confession system is for), so part of this PR should likely be removed.

2024-07-13 20:17 UTC, SELFHELL commented
> 
> To bring them in line with Royal Guard, a statline could be: +2 ST +2 END +1 CON +1 INT -1 SPD

fair enough, they probably dont need int/per

2024-07-13 20:50 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 2, TRUE)
Add maces 2 or 3, which is present elsewhere. Players may prefer a blunt damage weapon for less-than-lethal or armored combat, either for RP or technical reasons.

2024-07-13 20:50 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +
This line is missing C.grant_spells_templar(H) ... because you'll need to add templar spells.

2024-07-13 20:50 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.change_stat("strength", 2)
Other codebases had +2 perception as well. +1 or + 2 etc gives them some talent for spotting ambushes, which suits seasoned crusaders.

2024-07-13 20:50 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	give_bank_account = TRUE
Change this to = FALSE, and we have 'vow of poverty' knights Templar who are immune to the master's rod and so able to far more readily defend the temple against the king; their ultimate role.

2024-07-13 20:50 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		if("Pestra")
Pestra templars getting a needle of pestra would make them excellent battlefield medics and save a lot of lives.

2024-07-13 20:53 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/medicine, 1, TRUE)
Consider medicine 2 or medicine 3 for a Pestra templar.

2024-07-13 20:55 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/nobility/hand.dm
> +	H.verbs |= /mob/living/carbon/human/proc/faith_test
Request of maints, since it was removed with confessor

2024-07-13 20:56 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +
The goal was to NOT give them spells, since that would make them a flat out upgrade to priest/acolyte

2024-07-13 20:57 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		if("Pestra")
Snowflaking special items/stats for each god drastically increases the scope of the PR, not interested in that RN

2024-07-13 20:57 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/medicine, 1, TRUE)
Snowflaking special items/stats for each god drastically increases the scope of the PR, not interested in that RN

2024-07-13 21:06 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/swords, 3, TRUE)
swords at 4,

2024-07-13 21:07 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.change_stat("strength", 2)
removed those stats because they dont really need a damage buff with bows

2024-07-15 20:32 UTC, Dorodomki commented
i see these templars way too powerful for the church, they already have the chances to get clerics, crusaders and even a paladin, some lower quality sidekicks for the puritan would be better fitting this role since 2 knights are way too powerful

2024-07-17 08:05 UTC, Mogelix commented
> i see these templars way too powerful for the church, they already have the chances to get clerics, crusaders and even a paladin, some lower quality sidekicks for the puritan would be better fitting this role since 2 knights are way too powerful
This is anecdotal, but I'd just like to iterate that from my entire personal experience, clerics, crusaders, and paladins rarely show up to help the church, even when they explicitly called for. Sometimes, almost more often, they come and are antagonistic towards the church. Confessor is a relatively very weak role that serves essentially the same purpose as puritan just with a different aesthetic. With drifter removed things are a little more balanced re: this but still. I think there's nothing wrong with the Church having one or two skilled and well-equipped defenders.

The only problem I could see coming from this PR is if templars regularly act too much like town guards, outside of the church chasing antags who've only bothered the town and keep.

2024-07-20 00:57 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 2, TRUE)
I agree. No crossbows. Mace skill instead.

2024-07-20 03:04 UTC, ThePainkiller requested changes

2024-07-20 03:04 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 2, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/combat/axesmaces, 2, TRUE)
```

2024-07-20 03:04 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/swords, 4, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/combat/swords, 3, TRUE)
```
From 1 slot to 2, less rarity less weapon skills. No way equating them to a royal guard.

2024-07-20 03:04 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	ADD_TRAIT(H, TRAIT_MEDIUMARMOR, TRAIT_GENERIC)
Heavy armor training covers medium armor training. No need to include both.

2024-07-28 20:14 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	beltr = /obj/item/rogueweapon/sword/long
Ill disagree with you on this seeing how adventurer paladins get it,

2024-07-28 20:18 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/swords, 4, TRUE)
one slot makes sense for current pop, but RG's have a LOT more skills then these guys in more weapons + CQC skill.

2024-07-28 20:24 UTC, SELFHELL commented
Addressed all the suggestions, this should be good for a merge/TM

2024-07-28 20:29 UTC, SELFHELL commented
Also gonna disable paladin & lower the amount of cleric slots

2024-07-28 21:35 UTC, ThePainkiller commented
> Also gonna disable paladin & lower the amount of cleric slots

Don't disable paladin, as right now they have their own helmets and I'm reworking them on a separate PR.

2024-07-28 21:37 UTC, ThePainkiller commented
Class is still overpowered as fuck with lvl 4 skills, the longsword I can let slide, the rest no.

2024-07-28 21:39 UTC, SELFHELL commented
Alright, ill bring back pally and lower it to level 3. Anything else you want done?

2024-07-28 22:17 UTC, ThePainkiller approved these changes

2024-07-28 22:27 UTC, ThePainkiller commented
Looks perfect so far, let it be know I personally requested Swords back to 4, to make Templars in line with Royal Guard/Captain tier so that the Church has at least one very combat oriented protector.

I'll see about nerfing a bit the wandering clerics because holy fuck.

2024-07-28 22:38 UTC, Stutternov commented
Zo zucking zizased

2024-07-29 22:29 UTC, Optimism333 commented
You gave them a shield but forgot to give them shield skill

2024-07-29 22:30 UTC, SELFHELL commented
Oh shit, good catch.

2024-07-29 22:32 UTC, ThePainkiller commented
Just because they **have** shield skill doesn't mean they **HAVE** to spawn with one, you know?
This is a regular thing with stuff like Zybantu mercs. Templars also have (for some strange reason) Crossbow skill, do you also take this as a sign to give them a free crossbow?
Plus they already spawn with a longsword, good luck getting to use **both** lol

2024-07-30 09:33 UTC, BadAtThisGame302 commented
You should probably give them a bank account, starting with 0 though. They are still a member of the Town and every single town role has an account to my knowledge. Best the Templar is not the only one not.

2024-07-31 00:22 UTC, Wesreidau commented
My logic on no bank account:

First the historical precedent of the real-world inspiration. Templars were the "**Poor** Fellow-Soldiers of the Temple of Solomon", and had no personal money or possessions. What they had was the money given to them by the local chapter to buy arms or provisions. This is the reason for their tax exemptions as well as their _extreme trustworthiness_ in handling someone else's money, leading to their eventual role as bankers, administrators and mediators between kings. You could not bribe them as they had no way to keep the money. Occasions where a Templar did end up with money were scandals that saw them thrown out of the order in disgrace.

Following that precedent, I propose Templars not have a bank account for the same reason. Without the ability to store their own money, they have only what they carry or ask donations for. King wants to donate gold to the Temple? Hand it to a Templar. If he has a bank account an hour later, the Priest will string him up.

The second is a mechanical reason. Templars are supposed to _resist the Crown on behalf of the Temple_. The greatest instrument of power the Crown has is the master's rod, which is a ranged chain-stunner that can render anyone helpless. However, it only works on you if you have a bank account.

Not giving the Templar a bank account has the _roleplaying_ potential of a vow of poverty and the _gameplay_ power of immunity to the master's rod. If it were up to me, none of the Temple roles would have bank accounts. But starting with the Templar in this PR can see how that goes.

Naturally, anyone who'd rather have an account can just use the meister. Unless, of course, people pick up what we're laying down.

2024-07-31 00:30 UTC, Wesreidau reviewed
Offering a change to the job description.

2024-07-31 00:30 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	tutorial = "Templars are warriors who have forsaken wealth and title in lieu of service to the church, due to either zealotry or a past shame. They guard the church and its priest, while keeping a w
```suggestion
	tutorial = "From idealistic noble sons to blood-soaked and remorseful old soldiers, the Templars strive for both martial and moral excellence. Sworn to service in the Temple you protect the faithful, the meek, and the wrongfully accused. You were made strong to protect the weak, and you became righteous to know the wicked. Protect the Temple from those who would profane it in the name of crowns or cults and your life will be well-spent."
```

2024-07-31 00:30 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	tutorial = "Templars are warriors who have forsaken wealth and title in lieu of service to the church, due to either zealotry or a past shame. They guard the church and its priest, while keeping a w
A re-write I did previously. Use if you like.

2024-07-31 00:37 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	tutorial = "Templars are warriors who have forsaken wealth and title in lieu of service to the church, due to either zealotry or a past shame. They guard the church and its priest, while keeping a w
Original is long already, and this one is even LONGER, please remember this shows before selecting "yes this is my background" and will be insanely big text covering the entire screen, which might look bad on certain resolutions.

Sometimes less is more.

2024-07-31 00:40 UTC, Wesreidau commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	tutorial = "Templars are warriors who have forsaken wealth and title in lieu of service to the church, due to either zealotry or a past shame. They guard the church and its priest, while keeping a w
Cut a line.

2024-07-31 01:02 UTC, SELFHELL commented
CONFLICTS. PAIN

2024-07-31 01:02 UTC, BadAtThisGame302 commented
> The second is a mechanical reason. Templars are supposed to _resist the Crown on behalf of the Temple_. The greatest instrument of power the Crown has is the master's rod, which is a ranged chain-stunner that can render anyone helpless. However, it only works on you if you have a bank account.

Seriously? The Crown and Church are meant to work together, nobody is "supposed" to resist anything. They are a town role and a Church role so they should get a bank account as to not "be immune" to the master rod, because... nobody in Town should. 

If you start with this line of thinking then you'll lead the Church to conflict every round. It's really that deep, they are a member of both Church and State and like the Acolyte's below them and the Priest above them, should get a 0 mammon account.

2024-07-31 01:10 UTC, SELFHELL commented
ok I fliped a coin. Heads for bank account, tails for not. It landed on heads

2024-07-31 01:32 UTC, Wesreidau commented
> > The second is a mechanical reason. Templars are supposed to _resist the Crown on behalf of the Temple_. The greatest instrument of power the Crown has is the master's rod, which is a ranged chain-stunner that can render anyone helpless. However, it only works on you if you have a bank account.
> 
> Seriously? The Crown and Church are meant to work together, nobody is "supposed" to resist anything. They are a town role and a Church role so they should get a bank account as to not "be immune" to the master rod, because... nobody in Town should.
> 
> If you start with this line of thinking then you'll lead the Church to conflict every round. It's not really that deep, they are a member of both Church and State and like the Acolyte's below them and the Priest above them, should get a 0 mammon account.

What game are you playing where the crown and church have no disagreements? In that game there's no reason to have templars, just put a garrison trooper in the church.

SS13 is player versus paranoia. The church and the crown are supposed to be wary of one another and each therefore prevents the overstepping of the other. At round start they should be in equilibrium. As events play out, one side or the other gains more power and the other side has to resist it. Templar draw out how long the church can resist the crown being worn by Urist 'The Tyrant' McKing.

So yes, Templar should have no bank account so they start immune to the master rod. It ensures they have a degree more effectiveness against an anti-church king without having to buff their skills and gear against every possible threat. It isn't as if the king doesn't start with full plate, expert swords and a greatsword and can beat a templar 1v1 anyway. Or will have troops enough to do this on his behalf. Its just... one specific element for the roleplaying of a vow of poverty and making the templar the church's to command, not the crown's.

2024-07-31 01:33 UTC, SELFHELL commented on code/modules/jobs/job_types/roguetown/church/templar.dm
> +	tutorial = "Templars are warriors who have forsaken wealth and title in lieu of service to the church, due to either zealotry or a past shame. They guard the church and its priest, while keeping a w
I dislike this flavor text, its far less clear than the original. Ill pass on using it

2024-07-31 21:08 UTC, merged