Puts the addiction amulets on your wrists instead of your neck
Darkrp-community/OpenKeep pull request #424
Opened 2024-07-22 23:08 UTC by BadAtThisGame302

## About The Pull Request

Title

## Why It's Good For The Game

There's way more jobs that have their necks full with other items, thus unable to proc having the amulet, this grants those jobs their amulets, at the cost of the few, wrist full jobs.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-07-22 23:17 UTC, sanshoom commented
holy shit thank you

2024-07-23 03:09 UTC, ThePainkiller requested changes
Always rember the byond manual has handy stuff to prevent double "the" 's

2024-07-23 03:09 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/special.dm
> +				HU.visible_message("<span class='warning'>[HU] electrocutes [H] with [src].</span>")
```suggestion
				HU.visible_message("<span class='warning'>[HU] electrocutes [H] with \the [src].</span>")
```

2024-07-23 03:09 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/special.dm
> +				HU.visible_message("<span class='warning'>[HU] silences [H] with [src].</span>")
```suggestion
				HU.visible_message("<span class='warning'>[HU] silences [H] with \the [src].</span>")
```

2024-07-23 05:10 UTC, ThePainkiller approved these changes

2024-07-23 05:13 UTC, merged