Gives Treasure Hunter 2 speed
Darkrp-community/OpenKeep pull request #462
Opened 2024-08-02 00:36 UTC by NunLeft

Gives Treasure Hunter 2 speed to start.

## About The Pull Request
See title. Does nothing else.

## Why It's Good For The Game
Brings treasure hunter in line with assassin, rogue, archer. and other dodge based classes.
This is still balanced, as Treasure Hunters are ass in combat, cannot train their main weapon past skilled, and don't have nearly the combat potential as archer, rogue, or the allmighty Assassin do.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-08-02 23:41 UTC, ThePainkiller requested changes

2024-08-02 23:41 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
> +		H.change_stat("speed", 2)
```suggestion
		H.change_stat("speed", 1)
```
They don't need as much speed as a rogue, nope

2024-08-03 00:01 UTC, NunLeft commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
> +		H.change_stat("speed", 2)
What if I balance it with how Rogues are balanced, by giving them -1 strength?

2024-08-03 00:07 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
> +		H.change_stat("speed", 2)
You can give them -1 STR if you wish, but that won't make them gain +2 speed in any way.

2024-08-03 00:12 UTC, ThePainkiller approved these changes

2024-08-03 00:14 UTC, merged