crafting additions from other servers
Darkrp-community/OpenKeep pull request #505
Opened 2024-08-11 23:05 UTC by Dorodomki

## About The Pull Request

copies some crafting recipes from other roguetown servers, adds some crafting recipes for copper and bronze (non obtainable yet)

adds a knife for round start towners like fishermen, woodcutters, miners, masons and butlers 

we got too many changes on this PR due to a few merge conflict issues that got solved 

pr tested, played for a good while and recipes being craftable by the respective artisan of it 

## Why It's Good For The Game

gives us a few more uses for different materials and adds some quality of life for towners

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-08-11 23:11 UTC, 1N7Slayer commented
You may want to take a few moments to tidy up item descriptions, as they need to be able to present in-game with proper grammar, capitalization and spelling so as to not be negatively noticeable for immersion's sake.

2024-08-12 05:50 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	name = "Dwarf axe"
Do not capitalise the D.

2024-08-12 05:50 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	desc = "A Dwarf Axe Designed and used by Dwarfs, decorated with runes of Malum and ready to take action against any threat. or tree."
Do not capitalise axe or designed and after "...any threat" put a comma not a dot.

2024-08-12 05:51 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A heavy iron Hammer, a tool used by workers."
Do not capitalise Hammer.

2024-08-12 05:51 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	name = "iron Sledgehammer"
Do not capitalise Sledgehammer.

2024-08-12 05:52 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A heavy Steel warhammer, a weapon designed to make knights run in fear, the best option for a common soldier against a knight."
Do not capitalise Steel.

2024-08-12 05:52 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	name = "Steel Warhammer"
Do not capitalise Steel Warhammer.

2024-08-12 05:54 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +/obj/item/rogueweapon/woodcut/war
Do not /woodcut/ this axe as it is not for woodcutting, I take it with the after being /war.

2024-08-12 05:56 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A two handed club, decorated with a crown of spikes. A Barbaric Design good enough to be used as weapon."
Barbaric Design.

2024-08-12 05:56 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	name = "Copper warclub"
Copper.

2024-08-12 05:56 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "An extremely crude bronze weapon for crude battles, this isn't an Aasimar Weapon Design, yet does the work of killing armored opponents easier."
Weapon Design.

2024-08-12 05:56 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/knives.dm
> +	name = "Small knife"
Small.

2024-08-12 06:02 UTC, BadAtThisGame302 reviewed
I would continue further but it seems every single new additions of yours has random capitalised letters or isn't very good English. Please do a re-read of all and uncapitalise everything but the first letter on the description, maybe run things through grammar checks if you're not sure.

2024-08-12 06:02 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	desc = "An Special 'sword' Of copper, the material isn't the best but is good enough to slash and kill. "
**A** Special... Of.

2024-08-12 06:02 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	name = "Bronze Long Sword"
Bronze Long Sword.

2024-08-12 06:02 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	desc = "An Elaborated Long Sword of Bronze, a rarity on this era except for The Aasimars who are too familiar with them."
Elaborated Long Sword... Bronze... The...

2024-08-12 18:11 UTC, Dorodomki commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +/obj/item/rogueweapon/woodcut/war
is an iron weapon with a special design, stills being the same item but with a different sprite, we got to avoid giving more steel gear to adventurers

2024-08-13 06:02 UTC, BadAtThisGame302 commented on code/game/objects/items/devices/flashlight.dm
> +	name = "Copper lamptern"
Don't capitalise the C, please.

2024-08-13 06:02 UTC, BadAtThisGame302 commented on code/game/objects/items/devices/flashlight.dm
> +	desc = "a simpler and cheaper lamptern"
Capitalise the A.

2024-08-13 06:03 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A two handed club, decorated with a crown of spikes. A Barbaric Design. good enough to be used as weapon."
Barbaric Design.

2024-08-13 06:17 UTC, BadAtThisGame302 reviewed
I'm going to continue to pass through these until you make an effort and properly grammar check/uncapitalise your descriptions fully.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A two handed club, decorated with a crown of spikes. A Barbaric Design. good enough to be used as weapon."
also, meant to be a comma after design.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "An extremely crude bronze weapon for crude battles, this isn't an Aasimar weapon design. yet does the work of killing armored opponents easier."
Comma after design.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A two handed club, decorated with a Spiked sharpened flange head. An Antique Design good enough to continue being used as a weapon against armored enemies."
Spiked... Antique Design.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	name = "Bronze warclub"
Bronze.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	desc = "The bronze Spears Were used by antique Aasimar warriors, this one doesn't have such quality but does the work, use the pointy end for better results."
Spears Were...

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	desc = "Tool, weapon, loyal iron companion of Woodcutters. able to chop mighty trees and fight back threats of the forest."
Woodcutters.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	name = "Footman War Axe."
Footman War Axe.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	desc = "A big armored Axe, Spike and Pick ideal for any militiaman who wants to have a chance against a fancy noble whoreson."
Axe, Spike ... Pick.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	name = "Copper Falx."
Copper Falx.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	desc = "A special 'sword' Of copper, the material isn't the best but is good enough to slash and kill. "
Of.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/armor.dm
> +	name = "Copper Heart Protector"//SHITTY ARMOR SHITTY ARMOR!!
Uncapitalise all three words.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	name = "Bronze Long Sword."
All words.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	desc = "An elaborated long Sword of bronze, a rarity on this era except for the Aasimars who are too familiar with them."
Sword.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
> +	name = "Copper Heart Protector (2)"
Uncapitalise Heart and Protector.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
> +	name = "Copper Skullcap x2"
Uncapitalise Skullcap.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/blacksmith/tools.dm
> +	desc = "a simple and rough copper hammer"
Capitalise the A and out a dot after hammer.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/miner/rogueores.dm
> +	desc = "A bar of alloyed Bronze."
Uncapitalise Bronze.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/miner/tools.dm
> +	desc = "a primitive and rustic pickaxe, good enough to work the stone"
Capitalise the a and put a dot after stone.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/miner/tools.dm
> +	desc = "An Elaborated Pickaxe, its a tool to obtain ores and break stones"
Uncapitalise Elaborated Pickaxe, it's not its and put a dot after stones.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/miner/tools.dm
> +	name = "Bronze pick"
Uncapitalise Bronze.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/miner/tools.dm
> +	name = "Steel pick"
Uncapitalise Steel.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/miner/tools.dm
> +	desc = "An Elaborated Pickaxe of quality, its a great tool to obtain ores and break stones, including break metal armors"
Uncapitalise Elaborated Pickaxe, it's not its and put a dot after armors.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/farmer/tools.dm
> +	desc = "A simple and Rustic copper tool to work on the fields, a poor weapon in emergency too..."
Uncapitalise Rustic

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/farmer/tools.dm
> +	name = "Copper Fork"
Uncapitalise Copper Fork

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/farmer/tools.dm
> +
Why the space here?

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/wrists.dm
> +	name = "Bronze Armbraces"
Uncapitalise both Bronze and Armbraces

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/wrists.dm
> +	name = "Copper Bracers"
Uncapitalise both Copper and Bracers

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	smeltresult = /obj/item/ingot/bronze // No bronze ingots yet//the most expensive way to find bronze now
Please remove the //no bronze ingots yet... seeing as you made bronze ingots.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	desc = "An Ancient Neck protection, simple and solid for ancient warriors, now is used as an luxury accesory while keeps his protection."
Uncapitalise Ancient Neck

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	name = "Bronze Gorget"
Uncapitalise Bronze and Gorget

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	name = "Copper Gorget"
Uncapitalise Copper and Gorget

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	desc = "An Antique and Simple Protection for the neck, is used more as an accesory by the peasant folk, yet is a poor protection is better than nothing."
Uncapitalise Antique... Simple Protection

The correct spelling is accessory.

Remove is after yet and before a as the sentence doesn't make sense.

2024-08-13 06:17 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	desc = "A simple coif made of Cloth, not that good as armor itself but mostly useful to Soften a blow or to keep your head and neck warm."
Uncapitalise Cloth and Soften.

2024-08-14 04:47 UTC, Dorodomki commented on code/modules/clothing/rogueclothes/neck.dm
> +	desc = "A simple coif made of Cloth, not that good as armor itself but mostly useful to Soften a blow or to keep your head and neck warm."
thank you for the help with the grammar

2024-08-14 04:48 UTC, BadAtThisGame302 commented on code/game/objects/items/devices/flashlight.dm
> +	desc = "a simpler and cheaper lamptern"
And put a dot after lamptern.

2024-08-14 04:48 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	desc = "A Dwarf axe designed and used by Dwarfs. decorated with runes of Malum and ready to take action against any threat. or tree."
Dwarves and a comma after, not a dot.

2024-08-14 04:49 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	desc = "A Dwarf axe designed and used by Dwarfs. decorated with runes of Malum and ready to take action against any threat. or tree."
Also remove the dot after threat.

2024-08-14 04:49 UTC, Dorodomki commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	desc = "A Dwarf axe designed and used by Dwarfs. decorated with runes of Malum and ready to take action against any threat. or tree."
:woe :

2024-08-14 04:51 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A two handed club, decorated with a crown of spikes. a barbaric besign, good enough to be used as weapon."
Capitalise the a after the dot.

2024-08-14 04:52 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/blunt.dm
> +	desc = "A two handed club, decorated with a spiked sharpened flange head. an antique design good enough to continue being used as a weapon against armored enemies."
Capitalise the An after the dot.

2024-08-14 04:52 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	desc = "The bronze Spears were used by antique Aasimar warriors, this one doesn't have such quality but does the work, use the pointy end for better results."
Uncapitalise Spears.

2024-08-14 04:53 UTC, BadAtThisGame302 commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	desc = "Tool, weapon, loyal iron companion of woodcutters. able to chop mighty trees and fight back threats of the forest."
Put a comma after woodcutters and not a dot.

2024-08-14 04:55 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/mask.dm
> +	name = "Cloth mask"
Uncapitalise Cloth.

2024-08-14 04:55 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/mask.dm
> +	desc = "a simple cloth mask designed to aid in the concealing of bad odors or used in dirty works like mining or gravedigging."
Capitalise the first A

2024-08-14 04:55 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/mask.dm
> +	name = "Copper mask"
Uncapitalise Copper

2024-08-14 04:55 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/mask.dm
> +	name = "Bronze mask"
Uncapitalise Bronze

2024-08-14 04:55 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/mask.dm
> +	desc = "A heavy Bronze mask that both conceals and protects the face."
Uncapitlise Bronze

2024-08-14 04:56 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	desc = "An antique and simple Protection for the neck, is used more as an accessory by the peasant folk, a poor protection is better than nothing."
Uncapitalise protection

2024-08-14 04:57 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	desc = "An ancient Neck protection, simple and solid for ancient warriors, now is used as an luxury accesory while keeps his protection."
Fix this entire description please, grammar and capitalisation

2024-08-14 04:57 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/neck.dm
> +	name = "Padded coif"
Uncapiotalise Padded

2024-08-14 04:58 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/hats.dm
> +	name = "Copper skull cap"//used by undead npc's and poor guys
Uncapitalise Copper

2024-08-14 04:58 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/hats.dm
> +	name = "Copper Warrior Helmet"//used by undead npc's and antique warriors
Uncapitalise everything here

2024-08-14 04:58 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/hats.dm
> +	desc = "A simple and effective design. the warriors who used gear like this can only be remembered by the Aasimar."
Comma after design

2024-08-14 04:58 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/hats.dm
> +	desc = "An antique design copper helmet. used by ancient warriors before the ages of iron."
Comma after helmet

2024-08-14 04:59 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/hats.dm
> +	desc = "A poor copper helmet. used by barbarians or by militia trainees as a way to keep their skulls protected."
Comma after helmet

2024-08-14 04:59 UTC, BadAtThisGame302 commented on code/modules/clothing/rogueclothes/hats.dm
> +	name = "Bronze Warrior helmet"
Uncapitalise Bronze and Warrior

2024-08-16 00:42 UTC, ThePainkiller requested changes
Balance and grammar is all over the place, this displaces iron and is almost like introducing a literal alternative to iron.

2024-08-17 14:30 UTC, NPC1314 commented
37 commits, 61 files changed, new sprites, sprites deleted, sprites modified, some weapon stat changes, new material? new recipes, loadout changes, description changes, new armors new items, PR description doesn't mention half of it. Its like its designed to be triggering and make it impossible to review, not gonna lie, please split of say resprites to its own PR.

2024-08-21 23:01 UTC, 1N7Slayer commented
I highly suggest you squash your commits. It looks like a very large chain of individual commits - assuming you're webediting. It looks a bit messy.

https://www.git-tower.com/learn/git/faq/git-squash

Scroll down to the 'Merge' section, you don't need to rebase to do this.

2024-09-01 19:17 UTC, Dorodomki commented
gonna start to dismember and upload the pr bit by bit

2024-09-01 19:17 UTC, closed without merging