Lockpicks and Lockpicking
Darkrp-community/OpenKeep pull request #512
Opened 2024-08-13 14:23 UTC by Cre77

## About The Pull Request

**HUGE THANKS TO PAINKILLER/GUNDAMTANAKA!!!** This PR wouldn't be possible without his help. Sounds from a game, sprites by me.

evil update. Adds smithable and purchasable lockpicks and lockpickrings, gives them to Rogues, Assassins, and Graverobbers, gives appropriate roles lockpicking. You can lockpick non-latch doors and lockable containers to open or lock them. 
Skill affects success chance and speed, Perception and, if it's smithed, pick modifier also give a bonus. Picks take damage if you fail, normally breaking in ten failed attempts. It should be nigh impossible to pick locks without skill with a non-masterwork pick. 
Most roles have around 1-2, with only some crime-heavy ones having high enough to go through several doors on a single lockpick.
Sound feedback is extremely low if you're successful, and very audible for failed attempts and broken lockpicks.
Experience gain is on a slightly more generous side, mostly due to picks breaking, failed attempts not giving XP, and picks not being normally available at roundstart or without suppliers.

![image](https://github.com/user-attachments/assets/243c578d-3bd2-4aef-8c25-2869a0e0a0a9)
![image](https://github.com/user-attachments/assets/fe9f6c78-df2d-456c-83dc-f838fb835209)

Tested on doors, iron gates, chests and closets. Lockpick rings correctly store different picks of variable modifiers. Didn't touch pillories yet because someone else is still working on them.

## Why It's Good For The Game

crime's back big baby!!! Spies, thieves and assassins now get a new way of getting into places without liberal application of wooden club. Their targets should no longer feel as safe behind one set of doors, masons will lose less hair over messy break-ins, and guards are made to pay attention to more than just broken windows. This should also let rogues be a bit more desirable in parties, now that they're one of the few capable of lockpicking quickly and efficiently.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-08-13 22:16 UTC, ThePainkiller commented on code/game/objects/structures/crates_lockers/closets.dm
> +		return
Would be good to include a chat message to the user that the door is already unlocked

2024-08-13 23:30 UTC, ThePainkiller requested changes

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 1, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 2, TRUE)
```

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/bard.dm
> +	H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 2, TRUE)
```suggestion
	H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 1, TRUE)
```

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/nobility/nightman.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 3, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 2, TRUE)
```

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/other/merc_classes/underdweller.dm
> +        H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 1, TRUE)
```suggestion
        H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 2, TRUE)
```

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, pick(1,2,3), TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, pick(1,1,2), TRUE)
```

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/beggar.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, pick (1,2,3,4,5), TRUE) // thug lyfe
Y'know what, I'm not even mad, their stats are always random and I expect a beggar to be a master lockpick every now and then, this is kino immersion

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/jester.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 3, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 1, TRUE)
```

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 1, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 2, TRUE)
```
A bit higher to help them escape, otherwise they're fucked.

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/serfs/mason.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 2, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 3, TRUE)
```
I like this idea. Makes mason overall more useful.

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
> +	H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 3, TRUE)
```suggestion
	H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 4, TRUE)
```

2024-08-13 23:30 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/combat/dwarfranger.dm
> +	H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 1, TRUE)
```suggestion
```
No reason for a dwarf ranger to get lockpicking, specially if this distances them from humen/elves rangers in an unfair way. If this goes down to "but dwarven engineering" then we'll have to make lockpicks engineering skill-dependant rather than blacksmithing.

2024-08-13 23:39 UTC, Cre77 commented on code/game/objects/structures/crates_lockers/closets.dm
> +		return
donezo

2024-08-13 23:47 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/jester.dm
> +		H.mind.adjust_skillrank(/datum/skill/misc/lockpicking, 3, TRUE)
Fineeeeeeee

2024-08-14 04:28 UTC, ThePainkiller approved these changes

2024-08-14 04:47 UTC, ThePainkiller commented
Such a variable could be added at a later date, which would also make you gain more exp the better the lock you pick, but that's outside of the scope of this PR and could be added at a later date. This, as a framework for lockpicking, works great as-is for now.

2024-08-14 12:52 UTC, Cre77 commented
i considered making a variable "doorlvl" that mappers could mess with to make doors harder or easier to pick - but like Painkiller said, later. i wanna see how balanced or even used lockpicking is for now, without extra stuff on top

2024-08-15 03:08 UTC, ThePainkiller commented
Lockpicking pillories and windows is a great thing to look forward to 👀

2024-08-15 13:03 UTC, Stutternov approved these changes

2024-08-15 13:03 UTC, merged