goons for the merchant
Darkrp-community/OpenKeep pull request #543
Opened 2024-08-18 05:12 UTC by Dorodomki

## About The Pull Request

adds steveadors to the merchant replacing the grabbers/haulers and makes them latejoineable, they are the watchmen of storages/shop assistants since they can read, only Shop and warehouse access since they aren't the merchant to have such keys

## Why It's Good For The Game

addds more fun to an role that wasn't used a lot 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-08-18 21:22 UTC, beepbopbeepbop commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
> +	tutorial = "Be an Steveador is one of the lowest, yet most needed positions in town, they are expected to aid the Merchant, steward, masons, and blacksmiths in hauling goods and deliveries while the
Spelling mistake at the start

2024-08-19 03:23 UTC, ThePainkiller commented
Bro that drip goes HARD

2024-08-19 03:28 UTC, ThePainkiller requested changes
Balanced, drippy, useful, and a rename hinting at a port, love it

2024-08-19 03:28 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
> +	title = "Steveador"
```suggestion
	title = "Stevedore"
```

2024-08-19 03:28 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
> +	tutorial = "Be an Steveador is one of the lowest, yet most needed positions in town, they are expected to aid the Merchant, steward, masons, and blacksmiths in hauling goods and deliveries while the
```suggestion
	tutorial = "Being a stevedore is one of the lowest yet most needed positions in town, as they are expected to aid the Merchant, Steward, Masons, and Blacksmiths in hauling materials and goods while keeping a guarding eye on the town's warehouses for the safety of the items stashed within."
```

2024-08-19 03:28 UTC, ThePainkiller commented on code/modules/jobs/jobs.dm
> +	"Steveador"
```suggestion
	"Stevedore"
```

2024-08-19 03:28 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/keyrings.dm
> +/obj/item/keyring/steveador
```suggestion
/obj/item/keyring/stevedore
```

2024-08-19 03:28 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
> +		wrists = /obj/item/keyring/steveador
```suggestion
		wrists = /obj/item/keyring/stevedore
```

2024-08-19 08:28 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
>  /datum/job/roguetown/grabber
Please change the datums too.

2024-08-19 08:28 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
>  	display_order = JDO_GRABBER
And the display order.

2024-08-19 08:28 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
>  	flag = GRABBER
And the flag.

2024-08-19 19:52 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
>  	flag = GRABBER
These are all too arbitrary for the sake of refactoring and it might cause issues with saved player preferences, and also require mapping
We can leave it as is

2024-08-19 19:55 UTC, ThePainkiller requested changes

2024-08-19 19:55 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
> +
```suggestion
	..()
```
Copy this proc properly please, you need at least a ..() here

2024-08-19 20:13 UTC, ThePainkiller requested changes

2024-08-19 20:13 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/peasants/grabber.dm
> +		wrists = /obj/item/keyring/steveador
```suggestion
		wrists = /obj/item/keyring/stevedore
```

2024-08-19 20:35 UTC, ThePainkiller commented on code/modules/jobs/jobs.dm
> +	"Stevedore"
No, they should be peasants, leave this back the way it always was. They don't have the education to be a serf.

2024-08-19 20:40 UTC, Dorodomki commented on code/modules/jobs/jobs.dm
> +	"Stevedore"
they get reading 1 and are the serfs of the merchant and the steward mainly, that's the why of the change now, they are a bit more educated and act as shophands if possible too

2024-08-19 23:48 UTC, ThePainkiller commented on code/modules/jobs/jobs.dm
> +	"Stevedore"
Reading 1 is for operating the machines, as stated code wise, same as Soilsons do, and it doesn't justify them being serfs. They're peasants.

2024-08-20 19:22 UTC, ThePainkiller approved these changes
Arr matey, let's roll

2024-08-20 20:16 UTC, merged