Spicebug Fix, Bandits, Butter
Darkrp-community/OpenKeep pull request #562
Opened 2024-08-22 16:05 UTC by NPC1314

## About The Pull Request

Wraps up encountered annoyances in bandit camp.
* Ports fix for spice eye bug from https://github.com/Blackstone-SS13/BLACKSTONE/pull/1398
* Produce last touch I swear (grain a tiny bit less huge but gets significant clickability, new spice had a little too weak colors so tweaked it up)
* Churning butter takes stamina
* Some added bandit tweaks, was good but not quite random enough and some more chances for volfhelms is necessary
(More helmet options at random, bandit hood now a proper helmet though shitty so an option for style or if you dont want to wear the rusty barbute due to vision cone, the rusty halfplate/plate armor fixed to be child of halfplate so medium armor, bandit belt spawns with a simple thorn needle and bandit key, poacher gets axesmaces 1 so they can club a little, all bandits gets unique crafting recipes to make volf helmet like it says in its desc and also bandit hoods so you can always get your drip.)

## Why It's Good For The Game
Probably leaves bandits in a good spot where they can stay a couple weeks before any balancing, fixes a bug and wraps up the started edits.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-08-23 00:51 UTC, ThePainkiller commented
Please make the bandit's equipment assignment a weighted list, it's kind of weird there's equal chances to get a helmet than a hood.

2024-08-24 00:38 UTC, NPC1314 commented
Roight, yeeted the unneeded knowbandit thing, on the other stuff

The ominous hood the bandits get  has a leather coif under it, so its on par with a leather or volf helm in defense, its works fine as helmet for starter bandit, no worries.

The rusted plate armor got 2 issues
One is plate is heavy armor and the concept do be medium armor for the basic bandit "heavy", fullplate is a bit much some scruffy deserter and better for some rare type?
Two the onmobs looked terrible IMO, so, compromised and kept the old one in for future special classes or rewards, and made new sprites for rusted halfplate and tweaked the barbute to look more tolerable.

Reduced bandit slots to 4 and reduced the head price a bit, the incentives for hunting bandits need to be handled elsewhere this just encourages decapping without RP if we ever add the headcollector crap.

Also tacked on the food xp gain, some minor food things and a prelit torch as well as volf fur being a subclass of fur. Should be barely noticeable beyond making it so you need to actually get a volf to make the volf helmet, should something unexpected pop up Ill sort it.

Breaking off the inhand_R stuff for later, got some stuff for it but this is unwieldy as it is, a crime against atom.

2024-08-24 22:57 UTC, ThePainkiller commented on code/modules/antagonists/roguetown/villain/bandit.dm
> +			switch(pick(1,3))
Still asking this to be an actual weighted list. See warrior.dm for how to do one.

2024-08-25 23:05 UTC, ThePainkiller commented
Good to merge now?

2024-08-25 23:09 UTC, ThePainkiller requested changes

2024-08-25 23:09 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/hats.dm
> +	prevent_crits = list(BCLASS_CUT, BCLASS_BLUNT)
```suggestion
	prevent_crits = list(BCLASS_CUT, BCLASS_TWIST)
```
Blunt crit protection is reserved for plate items, never use this for leather tier items.

2024-08-25 23:37 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/hats.dm
> +	prevent_crits = list(BCLASS_CUT, BCLASS_BLUNT)
> Since when was blunt crit protection reserved for plate items? Plenty of armors provide it, including leather tier items and padded gambesons. However, a hood is probably too light to reasonably provide the protection so it is probably for the best for this specific item.

Malum PR. If this is an oversight and leather items still have blunt protection, thanks for letting me know about them.
The overall balance shift was `plate = good against blunt but no stab` / `chain = good against stab but no blunt`, while light armor is a "better than nothing only protects against minor cuts and dislocation.

2024-08-26 07:30 UTC, NPC1314 commented
Updated the hood, but it was leather coif  stats copy pasted , just with no toggle function, so coifs have been missed in the armor crit overhaul most likely.

2024-08-27 19:36 UTC, ThePainkiller commented
People have reported VL's have permanent white eyes when activating their vision and they're not getting them updated, I am assuming this PR is at hand due to the procs it touched

2024-08-27 19:38 UTC, NPC1314 commented
> People have reported VL's have permanent white eyes when activating their vision and they're not getting them updated, I am assuming this PR is at hand due to the procs it touched

Has to be, if I can't figure out a workaround its back to spiceeyes =(

2024-08-27 19:47 UTC, ThePainkiller commented
> Has to be, if I can't figure out a workaround its back to spiceeyes =(

Have you tried touching the proc on the druggy eyes proc themselves instead and run an update eye icons there or something?

2024-09-04 10:31 UTC, NPC1314 commented
Yep no point atomizing this any more. Its all in order.

2024-09-04 16:40 UTC, Stutternov approved these changes

2024-09-04 16:40 UTC, merged