Alchemy System: Those Ones Were Duds But We're For Real Now
Darkrp-community/OpenKeep pull request #618
Opened 2024-08-29 20:56 UTC by lavillastrangiato

## About The Pull Request

- Adds an alchemy system, coded by [Schmorgisborg](https://github.com/Schmorgisborg).
- These include new reagents: magic dust (air, earth, fire, water, and magic), sinew, tailbones, and metal dust (gold, silver, iron) that can be ground from ingots or ore.
- You can brew potions of health, anti-toxin, curing disease (which does not yet exist, sorry), as well as buff pots. We will see how balanced these are. You can make them last longer with a certain kind of dust.
- A cauldron. You brew potions in it.
- A glass vial.
- Gives alchemy skill to feldshers, archivists, and court magicians. Soon:tm:.

Of note is that there are now two (2) mortar items in the game; the old one can grind berries but not ingots/seeds/runes for dust, and the other one can grind ingots/seeds/runes but not berries/possibly other items. I would like to potentially combine these two but we'll see how it goes.

## Why It's Good For The Game

More systems and more modularity to the game.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-08-29 20:58 UTC, sanshoom commented
I am the evil alchemist.

2024-09-04 21:13 UTC, Stutternov approved these changes

2024-09-04 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/cauldron.dm
> +//give xp for /datum/skill/craft/alchemy
![images](https://github.com/user-attachments/assets/859b493c-6ffb-4953-b7c8-298fd4d83ee5)

LVS, where's the exp gain?

2024-09-04 22:25 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/cauldron.dm
> +					potion_result = "fortune!"
_"The cauldron finishes boiling with a faint `fortune!` smell"_

Don't use punctuation signs if it's not gonna be the end of a sentence...it'll look weird

2024-09-04 22:34 UTC, lavillastrangiato commented on code/modules/roguetown/roguecrafting/alchemy/cauldron.dm
> +					potion_result = "fortune!"
changed to FORTUITOUS

2024-09-18 08:23 UTC, ThePainkiller requested changes
Bugfixing after farming rework got fullmerged

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/rogue/swampweed
```suggestion
/obj/item/reagent_containers/food/snacks/produce/rogue/swampweed
```

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/rogue/swampweeddry
```suggestion
/obj/item/reagent_containers/food/snacks/produce/rogue/swampweeddry
```

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/rogue/pipeweed
```suggestion
/obj/item/reagent_containers/food/snacks/produce/rogue/pipeweed
```

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/rogue/pipeweeddry
```suggestion
/obj/item/reagent_containers/food/snacks/produce/rogue/pipeweeddry
```

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/berries
You're redefining this object and will override everything from the original (and this is even the parent unused tg berries, the ones we use are pathed `rogue` and `rogue/poison`), please don't do thissss
Besides this will be overriden by jacksberries and poison jacksberries' `possible_potion` var, so antidotes are virtually uncraftable, you'll have to pick another produce.

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/apple
```suggestion
/obj/item/reagent_containers/food/snacks/produce/apple
```

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/berries/poison
```suggestion
/obj/item/reagent_containers/food/snacks/produce/berries/rogue/poison
```

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/berries
The original parent should be `/obj/item/reagent_containers/foodproduce/berries/rogue` btw

2024-09-18 08:23 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/berries/poison
And again, this is defined already, right on top of the fyritius flower you added the `possible_potion` var to. Though I assume after farming rework got merged, you'll have to find this on another file entirely after updating from master...

2024-09-18 08:28 UTC, ThePainkiller commented
I'll have to un-TM this PR until the reassigning of potion_result vars gets handled properly, on their own item definitions, on their corresponding files, to avoid conflicts, and to make it fully mergeable so it can be part of our systems, pending future additions.

2024-09-18 08:31 UTC, ThePainkiller commented
Going to have to un-TM this PR pending proper re-assigning of `possible_potion` var into the proper item definitions, so that it's neatified and free of conflicts. Once those variables are on their right items and we avoid duplicating every single produce part of this system, we can proceed with a fullmerge. For now, DNM.

2024-09-19 02:17 UTC, lavillastrangiato commented on code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
> +/obj/item/reagent_containers/food/snacks/grown/berries
Not sure what you meant by this one, I separately assigned possible_potion to the poison berries and the regular berries, and they both made their assigned potions fine in testing. Either way, should be resolved.

2024-09-19 07:13 UTC, ThePainkiller requested changes

2024-09-19 07:13 UTC, ThePainkiller commented on code/modules/reagents/reagent_containers/bottle.dm
> +	icon = 'icons/roguetown/items/alchemy.dmi'
```suggestion
	icon = 'icons/roguetown/misc/alchemy.dmi'
```

2024-09-21 04:50 UTC, merged