Copper updates
Darkrp-community/OpenKeep pull request #644
Opened 2024-09-02 23:30 UTC by Dorodomki

## About The Pull Request

adds copper armors, weapon resprites and code fixes to the game, fixes misspells on some things and balances the copper to be copper gear, somewhat certain items were the same as iron, including utility gear like copper lampterns to the game, with this the apprentice smiths/independant towner/pilgrim smiths can make practices and sell cheap gear 

## Why It's Good For The Game

more utility for this shitty material, that's it 

<details><summary>Details</summary>
<p>

![Captura de pantalla (2087)](https://github.com/user-attachments/assets/aeee2450-5fef-4462-add8-239cee31f434)

![Captura de pantalla (2086)](https://github.com/user-attachments/assets/09700e66-73fb-4d6d-a473-61560f8f7f43)

</p>
</details> 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-09-07 05:51 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
> +	createditem_num = 0
If this is meant to create more than one, judging by `createmultiple = TRUE` above, why is this number zero?
If it's meant to craft only one, as evident by `recipe_name = "a mask of copper"`, why is createmultiple TRUE?
Which one is it? Two masks for one bar, or one mask per bar?

2024-09-07 05:52 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/mask.dm
> +	smeltresult = /obj/item/ingot/copper
If this is meant to be crafted on batches, remember making smeltresult `null`.

2024-09-07 05:56 UTC, ThePainkiller requested changes
Good catch on the spears and their stick requirements being dumb. Also, you have a point on making these 0 craftdiff and having less durability than a standard item, considering they can receive modifiers by smiths, so I'm tempted to approve at least copper shit being smithable for the sake of smith apprentices to gain skill levels with.
Overall, the stats for these gears, other than maybe price being a bit lower or durability being lower as well, is pretty good and balanced, I'm pleasantly surprised.
However do address the copper dagger exploit, please.

2024-09-07 05:56 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	desc = "A special 'sword' of copper, the material isn't the best but is good enough to slash and kill. "
```suggestion
	desc = "A special 'sword' of copper, the material isn't the best but is good enough to slash and kill with."
```

2024-09-07 05:56 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	created_item = /obj/item/rogueweapon/copperdagger
Can you go to copperdagger and make its `smeltresult = null` ? It's currently able to be smelted, effectively duplicating copper.

2024-09-07 15:40 UTC, Dorodomki commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
> +	createditem_num = 0
i was making most of copper be 1 gear piece to re smelt and keep improving recipes with it

2024-09-07 15:49 UTC, Dorodomki commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	created_item = /obj/item/rogueweapon/copperdagger
smeltresult = /obj/item/ash it should be giving this instead of copper

2024-09-07 20:59 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	created_item = /obj/item/rogueweapon/copperdagger
You know what, fair, why even have shit quality copper daggers you can sell for like, pennies. Make them ash.

2024-09-07 21:04 UTC, ThePainkiller commented on code/game/objects/items/devices/flashlight.dm
> +/obj/item/flashlight/flare/torch/lantern/copper/afterattack(atom/movable/A, mob/user, proximity)
Afterattack, process and extinguish procs are pointless to have, they should inherit from master, just erase these two, leave the `getonmobprop` one intact tho as that's necessary for the sprite to show correctly

2024-09-07 22:03 UTC, ThePainkiller requested changes
So much unecessary code to trim, so much to be fixed still

2024-09-07 22:03 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	recipe_name = "a great copper sword"
```suggestion
	recipe_name = "a copper greatsword"
```

2024-09-07 22:03 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/farmer/tools.dm
> +	desc = ""
```suggestion
```

2024-09-07 22:03 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/farmer/tools.dm
> +	desc = ""
```suggestion
```

2024-09-07 22:03 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/farmer/tools.dm
> +/datum/intent/pforkdump
You're redefining everything for no reason, it should inherit from parent
Every single line from this one to the end of tools.dm is pointless, erase all of these

2024-09-08 02:54 UTC, Dorodomki commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
> +	createditem_num = 0
i didn't made it that way since it also gives you 1 ingot if you smelt it

copper gear is totally smeltable for profits (more shitty armor or weapons, more practice or just toss it to a goblin unarmored feet)

2024-09-08 03:00 UTC, Dorodomki commented on code/modules/clothing/rogueclothes/wrists.dm
> +	smeltresult = /obj/item/ingot/copper
oo i see

2024-09-08 04:31 UTC, ThePainkiller requested changes

2024-09-08 04:31 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/wrists.dm
> +	smeltresult = /obj/item/ash
```suggestion
	smeltresult = /obj/item/ingot/copper
```
Creates only 1 bracer on recipe, so let it be smelted back

2024-09-09 00:23 UTC, ThePainkiller approved these changes
Feel bad for the poor squires getting copper gear, but all is within reason, we'll see what are the plans on implementing bronze in the near future and if these have to be moved or something, but for now, it's good to have the blacksmith apprentices have something to train with, that they can mostly recycle ad infinitum to also train smelting and helping out the smiths with.

2024-09-09 00:24 UTC, merged