spriting upgrades
Darkrp-community/OpenKeep pull request #65
Opened 2024-05-29 03:38 UTC by Dorodomki

## About The Pull Request

replaces old roguetown sprites by their new versions made by 7sin

## Why It's Good For The Game

adds a visual improvement for the server and gives us a guide in how to make sprites from now on

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-05-30 00:12 UTC, hermaplusplus requested changes
Multiple files have invalid file names. Please replace spaces in filenames with underscores or an otherwise appropriate name.

2024-05-30 00:13 UTC, hermaplusplus commented on icons/roguetown/one handed weapons.dmi
Invalid file name.

2024-05-30 00:13 UTC, hermaplusplus commented on icons/roguetown/two handed weapon one hand.dmi
Invalid file name.

2024-05-30 00:13 UTC, hermaplusplus commented on icons/roguetown/two handed weapons .dmi
Invalid file name.

2024-06-01 00:46 UTC, hermaplusplus reviewed
Invalid filenames no longer present. Please fix the merge conflict.

2024-06-02 17:20 UTC, hermaplusplus requested changes
There is still a merge conflict.

2024-06-02 19:37 UTC, hermaplusplus approved these changes
Conflicts resolved

2024-06-04 16:37 UTC, Dorodomki reviewed
look good

2024-06-06 03:23 UTC, merged