Merchant Updates 1 - slight buff, no sale Guild Tax, Goldface inventory expansion
Darkrp-community/OpenKeep pull request #660
Opened 2024-09-04 16:09 UTC by Cre77

## About The Pull Request

Bit of everything to prop up the Merchant and make it slightly more enjoyable, and needed.
- Old Licenses are gone, and their categories now available roundstart. In the future, I will make background-specific Licenses with new items, and rare old ones that didn't make it into the inventory update.
- Merchant now a little less weak, and starts with more money. In the future this loadout will turn into the "Independent" - with new ones being slightly poorer, but with a free license from the get-go.
- No more Guild tax for merchant sales - it will still affect Imports and Exports of the Stewardry.
- Inventory greatly expanded with a lot of non-unique items. When it comes to things like Weapons and Armor - they are SLIGHTLY cheaper than their sellprice to account for King taxes, pricing RNG, customer mark-ups and lack of quality bonuses from smithies. With the taxes it'd be hard, if not impossible to farm, and if they do - the returns are negligible.
- Most mundane stuff now vastly cheaper, weapons and armor are comparable, sometimes a little more expensive than the old version.
- Added a few randomized color clothing for merchant clothing gacha
## Why It's Good For The Game

Makes Merchant slightly less miserable to play, allows purchase of tools, utility items and armor otherwise inaccessible without smiths. Props them up a little more with roundstart wealth.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-09-04 23:16 UTC, BadAtThisGame302 commented on code/modules/cargo/packsrogue/weapons.dm
> +	name = "Battle Bomb"
Bottle*

2024-09-04 23:17 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
Why remove the -2 strength?

2024-09-05 03:44 UTC, Cre77 commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
Why keep it? Most roles had their maluses removed in recent pssses, and a lot of people felt it left merchants even more helpless.
Thwy can hardly frag even with basic str, anyway.

2024-09-05 03:44 UTC, Cre77 commented on code/modules/cargo/packsrogue/weapons.dm
> +	name = "Battle Bomb"
Holdover from before, I'll change it

2024-09-05 04:37 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/armor.dm
> +	contains = /obj/item/clothing/head/roguetown/helmet/heavy/captain
This is deprecated vampire gear. Unotabainable here for some reason, but it was actually vampire gear...

2024-09-05 04:39 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/armor.dm
> +	name = "Steel Hauberk"
Mmmmmnope, literal steel hauberk and 10 mammon cheaper than buying it from the smiths for no modifiers?
Haubergeon could get a pass, anything that requires more than one bar of steel, however, will not.

2024-09-05 04:39 UTC, Cre77 commented on code/modules/cargo/packsrogue/armor.dm
> +	contains = /obj/item/clothing/head/roguetown/helmet/heavy/captain
Vampires use the skull-looking barbute edit of it, this one is ancient RT gear. Thought it was a funky way of using unused stuff, but I'll swap it out for a bucket helmet

2024-09-05 04:40 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/armor.dm
> +	name = "Brigandine"
I'm not sure about this one either.

2024-09-05 04:42 UTC, Cre77 commented on code/modules/cargo/packsrogue/armor.dm
> +	name = "Steel Hauberk"
:pleadster:
removed

2024-09-05 04:43 UTC, ThePainkiller requested changes

2024-09-05 04:43 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
Because it discourages them from being too much of a frag stat which is something I'm tired of hearing from Merchants. The -2 STR **stays**, or they will be met with even harsher nerfs in the future.

2024-09-05 04:44 UTC, Cre77 commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
this is terrorism

2024-09-05 05:36 UTC, beepbopbeepbop commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
With the -2 strength I have consistently not rolled enough strength to even wield the rapier I spawn with as merchant.

2024-09-05 06:16 UTC, Cre77 commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
Rapier has 	minstr = 6. If you're an elf, at worst you'll get  6 str. If you're old - you won't be able to wield it

2024-09-05 06:19 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
They should not have had a rapier to start with, other than for symbolism. We can compromise at a -1 STR if it'd allow you to minstat as Elf Merchant, but for real, they're not and will not be in any way capable of combat at all.

2024-09-05 06:40 UTC, Cre77 commented on code/modules/jobs/job_types/roguetown/nobility/merchant.dm
> -	H.change_stat("strength", -2)
We can do that, then! Rapier is still peak swag, though, come on. It's about the STATEMENT

2024-09-15 10:40 UTC, BadAtThisGame302 approved these changes
I like this PR alot, alot of items forgotten added for the soul of it. Maybe we can have a luxury wardrobe added to seperate it from the common clothes after this PR's merged. But it's a TM for a few rounds and if all works then it's good to go.

2024-09-15 10:40 UTC, BadAtThisGame302 commented on code/modules/cargo/packsrogue/apparel.dm
> +	cost = 15
Hennin is used by the nobility. Perhaps a little more expensive?

2024-09-15 10:52 UTC, Cre77 commented on code/modules/cargo/packsrogue/apparel.dm
> +	cost = 15
sure

2024-09-15 11:53 UTC, ThePainkiller commented
Please don't decide on testmerges as that's us maintener's realm to decide what gets TM'd and what not, and this doesn't necessitate a TM at all as it's mostly QoL for merchant and some item packs to be added
That being said, a few prices could see corrections as that'd be undercutting the smiths, so I'll provide input on what needs to be addressed before a full merge.

2024-09-15 12:06 UTC, ThePainkiller requested changes

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 18
```suggestion
	cost = 20
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 18
```suggestion
	cost = 20
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 10
```suggestion
	cost = 12
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 12
```suggestion
	cost = 10
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 22
```suggestion
	cost = 30
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	contains = /obj/item/net
```suggestion
	contains = list(/obj/item/net,
			/obj/item/net,
			/obj/item/net)
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 10
```suggestion
	cost = 15
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 36
```suggestion
	cost = 40
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 30
```suggestion
	cost = 20
```

2024-09-15 12:06 UTC, ThePainkiller commented on code/modules/cargo/packsrogue/weapons.dm
> +	cost = 20
```suggestion
	cost = 30
```

2024-09-15 12:18 UTC, ThePainkiller approved these changes

2024-09-15 12:20 UTC, merged

2024-09-16 00:39 UTC, Mogelix commented
Can you readd purchasing the psycross? And purchasing amulets in general. Not a big fan of that change. Gotten a lot of use of having multiple psycrosses.

2024-09-16 03:43 UTC, ThePainkiller commented
Considering psycrosses bar zizo cultists and vampires, highly unlikely that they'll ever be.