Ports Ratwood's Feint Rework, removes Bandit INT malus
Darkrp-community/OpenKeep pull request #706
Opened 2024-09-11 19:11 UTC by Cre77

## About The Pull Request

Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/756, with added status alerts for its respective effects.
Also removes the pretty pointless intelligence malus from bandits, to prevent feint spam being the go-to way to shut them down.

Original PR's changes are as follows, copypasted:
Reworks feint to be based on int difference and to a lesser degree spd difference. Changes the impact of feint intent to instead grant a longer immobilize effect (still barely notable but very hard to test on a local server, its still too quick to tab between two clients and see if I can move)
The actual number changes:

SKILL IMPACT 10% or 15% if feint intent -> always 15%
INT IMPACT Singular check to see if the opponent has more int -> int difference *10
SPD IMPACT None -> 5% per difference
Feint Intent -> Increases Impact of Skill difference -> Increases duration of Immobilize
## Why It's Good For The Game

Gives INT races and characters an angle of viability in melee combat, and offsets intelligence-weak STR characters' power with a weakness to this select intent. Gives a new option for people ganging up on powerful characters that isn't just grab spam.

Never really understood why the bandit intelligence malus was kept around to begin with, aside from flavor.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-09-11 20:47 UTC, ThePainkiller commented
While I agree that bandits' INT malus was too high, I'd still rather keep it at a -1 for their whole savagery and connection to Matthios
Given that they now have a system to actually summon equipment, it's not like having a debuff for crafting affects them that much.

2024-09-11 21:04 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/rmb_intents.dm
> +	duration = 5 SECONDS
On testing alchemy, using the duration in exact deciseconds has proven more reliable in making buffs/debuffs fade away than using pre-built definitions like `X SECONDS/MINUTES`, so I suggest reverting these just to err on the side of caution.

2024-09-11 21:11 UTC, DovaKitty requested changes
Feint is good, moving Bandit to -1 would be okay.

2024-09-11 21:11 UTC, DovaKitty commented on code/modules/antagonists/roguetown/villain/bandit.dm
Feint code looks good. This should be reduced to -1 instead of removed altogether. Bandits know how to read for some reason, but I'd not say they're as intelligence as the average towner.

2024-09-11 21:52 UTC, Cre77 commented on code/game/objects/items/rogueweapons/rmb_intents.dm
> +	duration = 5 SECONDS
changes addressed

2024-09-13 15:23 UTC, NPC1314 commented
Don't see any reason this shouldn't get a test since comments adressed.

2024-09-16 12:57 UTC, NPC1314 approved these changes

2024-09-16 13:00 UTC, merged