Totod Order Emissary from Crusader transformation and Count/Countess honorary
Darkrp-community/OpenKeep pull request #741
Opened 2024-09-17 14:48 UTC by BadAtThisGame302

## About The Pull Request

Gives the Grenzelhoft Count role their own honorary, Count/Countess.

Transforms the Crusader special adventurer to a Totod Order Emissary with a goal to get more funds/equipment/materials from Enigma to the Crusades of Valoria.

## Why It's Good For The Game

Took inspiration from the new Noble PR to add the honorary to the Count and to increase the lore presence in the game and thus transforming the Crusader to an Emissary for the Crusade from the far away Valoria that'll hopefully embroiden the RP.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-09-17 20:44 UTC, Optimism333 commented
Neat changes. Could you possibly also add Emir/Emira for the Zybantu noble?

2024-09-17 23:13 UTC, ThePainkiller requested changes

2024-09-17 23:13 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +	beltl = /obj/item/clothing/head/roguetown/helmet/heavy/crusader/t
```suggestion
	head = /obj/item/clothing/head/roguetown/helmet/heavy/crusader
```
Helmets will lose the capability to be worn on the hip due to issues.

2024-09-17 23:13 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +		backl = /obj/item/gun/ballistic/revolver/grenadelauncher/crossbow
```suggestion
```

2024-09-17 23:13 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +		backr = /obj/item/storage/backpack/rogue/satchel
```suggestion
		backr = /obj/item/gun/ballistic/revolver/grenadelauncher/crossbow
```
You already defined a satchel up above, why shuffle it around and define it again?

2024-09-17 23:13 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
>  	beltr = /obj/item/rogueweapon/sword/decorated
```suggestion
	beltl = /obj/item/rogueweapon/sword/silver
```

2024-09-17 23:13 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +		shoes = /obj/item/clothing/shoes/roguetown/boots/armor/light
```suggestion
		shoes = /obj/item/clothing/shoes/roguetown/boots/armor/light
		head = /obj/item/clothing/head/roguetown/helmet/heavy/crusader/t
```

2024-09-18 00:29 UTC, DovaKitty requested changes
Requesting that this class only changes their patron to Forgotten if they are not Astrata or Necra since in lore, the Totod worship is made up of followers of all three gods. The amulet will also have to change based on those patrons.

2024-09-18 00:29 UTC, DovaKitty commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +	H.patron = GLOB.patronlist[/datum/patron/forgotten]
I'd suggest only forcing forgotten patron if the character does not already have Astrata or Necra as a patron. The Totd order has all three.

2024-09-18 00:29 UTC, DovaKitty commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +	neck = /obj/item/clothing/neck/roguetown/psicross/silver
If Astrata/Necra are added as allowed patrons, this code will have to be changed to depend on patron, with the silver psycross being for the Forgotten worshipers.

2024-09-18 17:31 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +	neck = /obj/item/clothing/neck/roguetown/psicross/silver
This will have to do due to no third set of Crusader gear even though it's 3 patrons.

2024-09-18 17:31 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +	H.patron = GLOB.patronlist[/datum/patron/forgotten]
Updated.

2024-09-19 08:26 UTC, ThePainkiller requested changes

2024-09-19 14:28 UTC, NPC1314 commented
Still shows as changes requested but all marked as resolved, bit unclear.
Anyways, you happy with its current state? No more changes planned?

2024-09-19 14:57 UTC, BadAtThisGame302 commented
> Still shows as changes requested but all marked as resolved, bit unclear.
> 
> Anyways, you happy with its current state? No more changes planned?

No extra changes it's all good if everyone else is.

2024-09-19 17:57 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
>  	H.mind.adjust_skillrank(/datum/skill/combat/wrestling, 1, TRUE)
You can give them at least 2 on wrestling and unarmed as well, to fall in line with all limited classes

2024-09-19 18:07 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
> +	if(H.patron != /datum/patron/divine/necra)
I do feel like this line could be compacted into the one above, like:
`if(H.patron != /datum/patron/divine/astrata || H.patron != /datum/patron/divine/necra)`

2024-09-19 22:26 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
>  	H.mind.adjust_skillrank(/datum/skill/combat/wrestling, 1, TRUE)
Sure.

2024-09-21 18:38 UTC, NPC1314 approved these changes

2024-09-21 18:38 UTC, merged