Dark Elf mercenary with subclasses, Whip intent tweaks
Darkrp-community/OpenKeep pull request #742
Opened 2024-09-17 15:05 UTC by Cre77

## About The Pull Request

i have like a gajillion things to get done, so i'm posting this as a draft to start getting feedback early. Opening this up once I get the sprites plugged in and feedback is addressed.

Whips are now Great to hit hands and feet. Their Lash intent retains the old 2-tile reach, unparriability, but has a longer charge time to compensate. Their Crack intent has been downgraded to parriable, normal reach to serve as a quick, normal blunt attack.

Adds edgelord delf mercenaries in two subclasses based on gender: the male archer, based around ranger and garrison archer, and the female lashers that lean toward a more combat-oriented dungeoneer.
![image](https://github.com/user-attachments/assets/b7c4990d-475c-4aed-967f-a2a40cf545a0)

Female lashers come with a statline comparable to grenzelhoft mercenaries, decorative armor that leaves some pretty vital areas like the head, abdomen and legs open, but have a tower shield and leather whip equivalents.
Their mediocre speed makes dodging the go-to defense, and their intelligence malus leaves them succeptible to feints and unable to really get into utility skills.
Rewards good spacing, making use of the net to aid in that, and works well in tandem with the support-oriented archer.  Their gimmicky origin as secret police enables the torture verb. Coupled with their less-than-lethal loadout, they may be the first "independent" investigator, of sorts.

Male archers have swords and bow skills, a gambeson reskin, a short sword and a recurve bow.
They're more of a jack of all trades, assassin type, having good speed to kite and dodge in combat, but lacking any staying power or utility skills as good as the boltslinger or the steppesman. They still have a spread of 1-2s, mostly to sew their own and lasher's wounds, and to craft poison arrows to bring out the recurve bow's main strength.

## Why It's Good For The Game

Whips are a little more balanced now - preivously you could just turn Crack on and keep people perma-knocked down while staying out of their range completely. Making use of that is now more risky.
Lashers having torture will open up some interesting possibilities for non-court/temple parties seeking to find antags.
Lashers and archers covering for each others' weaknesses should enable some fun power couple roleplay, and they both bring new weapons and playstyles to the merc roster.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-09-17 17:30 UTC, Cre77 commented
Tested, everything works correctly. Opening it up for review
![image](https://github.com/user-attachments/assets/ed565d60-f76c-492a-87dc-8b6a1b1179a8)

2024-09-17 17:31 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/armor.dm
> +/obj/item/clothing/suit/roguetown/armor/plate/half/iron/shadowplate
Half-plate is being turned into heavy armor, once my PR goes through this'll have to be refactored.

2024-09-17 17:35 UTC, Cre77 commented on code/modules/clothing/rogueclothes/armor.dm
> +/obj/item/clothing/suit/roguetown/armor/plate/half/iron/shadowplate
should i switch it to some other piece of armor, like steel/iron chainmail? or will you do that later on your own PR?

2024-09-17 17:40 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/armor.dm
> +/obj/item/clothing/suit/roguetown/armor/plate/half/iron/shadowplate
I might have to do that later in my PR because it'll most likely require a TM first. Considering coverage and sprite, this will most likely be a cuirass children

2024-09-17 18:10 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/polearms, 1, TRUE)
Why so many weapons knowledge? Polearms and swords? Crossbows 2 despite not starting with one? Knives 2?

2024-09-17 18:19 UTC, Optimism333 commented
Decrease the number of weapon skills under the if(H.mind) umbrella, when gives skills based on male/female I would recommend  maybe 2 to be skilled (3), and one to be average (2).

2024-09-17 18:36 UTC, Cre77 commented
> ### Quick Feedback
> Decrease/remove weapon skills under the if(H.mind) umbrella, when the class is given skills based on male/female I would recommend maybe two to be skilled (3), and one to be average (2). Three skilled at most if one of those is shield.
> 
> Just as an example...
> 
> For Male:
> 
> * Skilled (3) bows
> * Skilled (3) swords
> * Average (2) knives
> 
> For Female:
> 
> * Skilled (3) whips/flails
> * Average (2) axes/maces
> * Skilled (3) shields
> 
> ### Edit
> Just saw your changes. Looks more reasonable now, thank you. I'll scrutinize this a bit more later.

commited a new version RIGHT as you edited that comment, oh my go-
As of the current version, they get what you mentioned, plus average crossbows for men - all the other skills they have are weak. I didn't even notice I gave them Expert bows, and not Skilled, initially. We can either roll with this or with the previous one, iunno

2024-09-17 18:47 UTC, Cre77 commented
the new stat spread is:
females get 3 shields, 3 whips, 2 axesmaces, 2 knives
males get 3 bows, 3 swords, 2 crossbows, 2 knives

2024-09-17 18:54 UTC, Optimism333 commented
I think that is an acceptable compromise.

2024-09-18 00:51 UTC, DovaKitty requested changes

2024-09-18 00:51 UTC, DovaKitty commented on code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
> +			H.verbs |= /mob/living/carbon/human/proc/torture_victim
This will either need to be expanded to both sexes or removed in my opinion.

2024-09-18 00:51 UTC, DovaKitty commented on code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/wrestling, 3, TRUE)
Should likely be lowered by 1, since female gets an extra +1 and male is closer to other sneaky classes like Rogue that get 2 wrestling. Saves effort of changing when wrestling skill gets buffed.

2024-09-18 00:53 UTC, DovaKitty commented on code/modules/jobs/job_types/roguetown/other/merc_classes/anthrax.dm
> +			H.verbs |= /mob/living/carbon/human/proc/torture_victim
Steelhearted should also likely be removed after being expanded to both sexes. Not all torture classes get steelhearted, including Hand and Dungoneer. Steelhearted has likely been over-given to new classes.

2024-09-18 02:03 UTC, DovaKitty approved these changes
Looks fine after changes. The icon changes means it will conflict with a lot of PRs and may not be easy to TM.

2024-09-18 19:05 UTC, Optimism333 commented
Unarmed and wrestling are standardized at 2 (average) and 3 (skilled) on most other mercs. Bumping that to 3 (skilled) and 4 (expert) on the female version of this merc is pushing it.

Drop the unarmed under if(H.mind) to average (2) at least, please.

2024-09-18 20:14 UTC, NPC1314 commented
IMO stat boost should be +4, same as town guard and underdweller, not +5, so femel drop str to +1 and remove -1 int,
and for the male drop speed to +1 and up con to +2

2024-09-18 21:11 UTC, Cre77 commented
> IMO stat boost should be +4, same as town guard and underdweller, not +5, so femel drop str to +1 and remove -1 int, and for the male drop speed to +1 and up con to +2

I don't get the dynamics of this - women have the exact same stats as grenzelhoft, but with maluses on top. They NEED Str and Con to do their non-lethal thing and restrain people, otherwise their kit falls flat and misses the mark completely, ending up being inferior to swords classes.
Males, too, have speed to excel at hit-and-run and dodging, with none of the PER or STR bonuses other ranged classes get - it's done so to set them apart, and give them a different playstyle as opposed to just steppesman 0.5. As far I'm concerned, no one else took issue with this spread either.

2024-09-18 21:12 UTC, Cre77 commented
> ## More Quick Critique
> * Unarmed and wrestling are standardized at 2 (average) and 3 (skilled) on most other mercs and basic combat classes
> * From the math I see here, you've bumped that to 3 (skilled) unarmed on both male and female and 4 (expert) wrestling on the female version of this merc
> * Please standardize that to 2 (average) unarmed and 3 (skilled) wrestling. These mercs already have very solid stats and weapon skill variety, no need to push it

They both get 2 unarmed and 3 wrestling now

2024-09-18 22:13 UTC, Cre77 commented
> IMO stat boost should be +4, same as town guard and underdweller, not +5, so femel drop str to +1 and remove -1 int, and for the male drop speed to +1 and up con to +2

Lasher dunked to 1 con instead of 2. Not gonna touch archer speed because, again, this will eliminate what sets them apart.

2024-09-18 22:20 UTC, Optimism333 approved these changes
I think this is acceptable in its current state, now that feedback has been addressed from multiple sources and adjustments have been made.

We can keep an eye on things and tweak up or down a bit in the future, but looks good to go to me.

2024-09-19 04:20 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/whips.dm
> +	canparry = FALSE //Has reach and can't be parried, but needs to be charged and punishes misses.
Why did you INVERT the intents?
Lash was supposed to be the weak and crack was supposed to be strong, and now they're the other way around because...?

2024-09-19 06:40 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/whips.dm
> +	canparry = FALSE //Has reach and can't be parried, but needs to be charged and punishes misses.
My bad oh god. I swear it used to be the other way around back when I tested Treasure Hunter.

2024-09-21 14:47 UTC, NPC1314 approved these changes
Request was for 2 devs to sign off on it, achieved.
Nothing to test really besides the whip stuff, seems safe to merge.

2024-09-21 14:47 UTC, merged