Armor naming semantics
Darkrp-community/OpenKeep pull request #813
Opened 2024-09-27 14:16 UTC by Cre77

## About The Pull Request

Changes some names and descriptions that were different-language at best, and made-up at worst. Fact-checked by a resident medieval armor enthusiast on discord. No more maille, haubergeon, halbert, or plate chausses.
![image](https://github.com/user-attachments/assets/e6c919ca-898f-4c74-a691-615ebbcefb58)

## Why It's Good For The Game

we got rid of "bervor", might as well shake the rest of the inconsistency off

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-09-27 15:27 UTC, SaintBurgher commented
Personally, I'd go with plate legs but either works

2024-09-27 17:17 UTC, ThePainkiller requested changes

2024-09-27 17:17 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/pants.dm
> +	name = "plated leggings"
```suggestion
	name = "plated chausses"
```
Literally every leg covering armor on Kingdom Come Deliverance is named plate chausses, I'm not budging from this one, I **know** this to be correct. Plated armor for the legs was composed by tassets for the upper thigh and cuisses for the rest of the thigh. Calling them "leggings" is leaning towards fetish territory.

2024-09-27 17:17 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/pants.dm
> +	desc = "Leggings made of plated steel, offering additional protection against blunt force."
```suggestion
	desc = "Cuisses made of plated steel, offering additional protection against blunt force."
```

2024-09-27 18:29 UTC, Cre77 commented on code/modules/clothing/rogueclothes/pants.dm
> +	name = "plated leggings"
can't be bothered to argue with you

2024-09-27 18:35 UTC, ThePainkiller approved these changes

2024-09-27 18:37 UTC, ThePainkiller commented
"Mail training" sounds funny to me, like being trained on delivering letters, but still makes sense, moving from the archaic shit we previously had (maille, sherpening wheel, etc)

2024-09-27 18:37 UTC, merged

2024-10-01 13:44 UTC, NPC1314 commented
Absolute garbage, the resident expert needs to go back to youtube or something.
Even wiki gives sources for maille and haubergon.