sprite and code update
Darkrp-community/OpenKeep pull request #828
Opened 2024-10-01 01:55 UTC by Dorodomki

## About The Pull Request

fixes some bugs with the items of the game, updates sprites to the date and adds a few things that need to be balanced 

## Why It's Good For The Game

more content to enjoy into the game

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-10-01 07:35 UTC, ThePainkiller requested changes

2024-10-01 07:35 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	force_wielded = 30
This is LITERALLY an eagle beak tier weapon. The numbers are all over the place and these can be SMITHED meaning they'll get modifiers. Either make these craftable or nerf them incredibly hard, they shouldn't be as strong as the greatest 2h mace we have on code when it's just a wooden pole with two steel reinforced bits at the ends.

2024-10-01 07:35 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	gripped_intents = list(/datum/intent/sword/cut, /datum/intent/sword/thrust)
If you don't give this weapon a chop intent instead of a thrust (which scimitars shouldn't have tbh since they're not made for STABBING), this weapon will suck.
Make this a steel cutlass child instead, so that people can opt between cutlass or scimitr for the same effect but different drip

2024-10-01 07:35 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/shields.dm
> +	resistance_flags = FLAMMABLE
```suggestion
	resistance_flags = FIRE_PROOF
```
It's made of iron ingot, not of wood

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/neck.dm
> +	armor = list("melee" = 45, "bullet" = 20, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 0)
```suggestion
	armor = list("melee" = 30, "bullet" = 15, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 0)
```
No.

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/clothing/rogueclothes/neck.dm
> +	armor = list("melee" = 30, "bullet" = 15, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 0)
```suggestion
	armor = list("melee" = 25, "bullet" = 10, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 0)
```

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lcarp.dm
> +	backr =/obj/item/rogueweapon/halberd/bardiche/woodcutter//an specialist in cut trees would have two axes to his name
```suggestion
	backr = /obj/item/rogueweapon/woodcut/steel
```
This is not a woodcutter. This is a carpenter. They get an axe for chopping up wood and a steel as an upgrade for being legendary, but not a literal combat bardiche. They are not Woodcutter+.

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lsmith.dm
> +	backr =	/obj/item/rogueweapon/hammer/sledgehammer
I suggest leaving this sledgehammer as their only hammer and replacing the small hammer with a lamptern tbh
Hell, get rid of the iron mask too while at it

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm
> +	backl =/obj/item/rogueweapon/halberd/bardiche/woodcutter//an specialist in cut trees would have two axes to his name
```suggestion
```
No. On Legendary woodcutter I'd let it be, but on a normal woodcutter, TWO axes? And a combat one at that? No way in hell.

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	recipe_name = "a couple knifes"
```suggestion
	recipe_name = "three peasantry knives"
```

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	recipe_name = "a militia lail"
```suggestion
	recipe_name = "a militia flail"
```

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	additional_items = list(/obj/item/grown/log/tree/stick)
```suggestion
	additional_items = list(/obj/item/grown/log/tree/small)
```

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	craftdiff = 2
```suggestion
	craftdiff = 1
```

2024-10-01 07:35 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/tools.dm
> +	max_integrity = 400
```suggestion
	max_integrity = 500
```

2024-10-01 07:56 UTC, NPC1314 commented
It's unfortunate you chose to disregard all my advice on atomizing this PR Dromki.
The scope of PRs is a choice, bundling all these together was a choice, and it suffers for it.

A bit limited time, but glancing at icon diff bot theres some great stuff but also some thats not really acceptable. Like the plough is super nice, but copying the tools over from the tool file to the modular one isn't ok. To achieve what you wanted (replace the tools with your sprites) just update the old tools.dmi to where you want it and edit the icon path, pointing them to the other icon file. We don't need copies of the same icon in several files, thats a terrible idea, and theres no need to overwrite in this way.

For armors/helmets, several are major resprites of the most common armors and at least seeing a before and after screenshot seems like the bare minmum when sending old sprites to the tomb and replacing with a brand new one.

I'll repeat my advice, make the armor and helmets its own PR, and add, make the tool stuff its own PR as well honestly, and also, please take some screenshots in game when deleting old sprites and replacing with new ones.

2024-10-01 14:58 UTC, Dorodomki commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	force_wielded = 30
this weapon takes the same ammount of materials to make and it doesn't have the smash intent of that weapon and 2 tile stab

2024-10-01 14:58 UTC, Dorodomki commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	gripped_intents = list(/datum/intent/sword/cut, /datum/intent/sword/thrust)
the weapon is intended to be an alt style for steel swords

2024-10-01 15:06 UTC, Dorodomki commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	additional_items = list(/obj/item/grown/log/tree/stick)
is using a stick like every other mace, is even a bit weaker than a mace

2024-10-01 17:04 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm
> +	backl =/obj/item/rogueweapon/halberd/bardiche/woodcutter//an specialist in cut trees would have two axes to his name
isn't a combat axe read the stats the axe deals 25 damage at two hands and has 1 charged attack at 2 tiles wich deals 10 ap more because is just swing a big axe really really hard, this axe also chops trees on one hit less

2024-10-01 17:05 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lcarp.dm
> +	backr =/obj/item/rogueweapon/halberd/bardiche/woodcutter//an specialist in cut trees would have two axes to his name
is an iron two handed axe that chop tress in 1 hit less than iron axes

2024-10-01 23:23 UTC, Dorodomki commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lsmith.dm
> +	backr =	/obj/item/rogueweapon/hammer/sledgehammer
legendary smith should have 2 hammers, one to break stones with ores and other to smith

2024-10-04 10:36 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree = 1)
Can you make it so that it requires a huntingknife (parent knife item) as a tool? I feel carving should take at least a knife

2024-10-04 10:37 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/rogueweapon/woodstaff/quarterstaff = 2, /obj/item/ingot/steel)
```suggestion
	reqs = list(/obj/item/rogueweapon/woodstaff/quarterstaff, /obj/item/ingot/steel = 2)
```
Should take 2 steel bars instead, to symbolize both ends of the staff, what would you even tie together two whole quarterstaves with?

2024-10-04 10:38 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "Steel quarterstaff (+2 staff)"
```suggestion
	name = "steel quarterstaff"
```
Crafting recipes from crafting menu never hint at the ingredients needed

2024-10-04 10:38 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	name = "Iron quarterstaff"
```suggestion
	name = "iron quarterstaff"
```

2024-10-04 10:41 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	force = 10
```suggestion
	force = 15
```

2024-10-04 10:43 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/flail.dm
>  	force = 20
```suggestion
	force = 30
```
Change the parent iron flail to 20, this is the steel version.

2024-10-04 10:43 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/flail.dm
> +	force = 30//same as the iron flails since is the same with different flavour
```suggestion
	force = 20 //same as the iron flails since is the same with different flavour
```

2024-10-04 10:44 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/flail.dm
> +	name = "Wooden flail"
```suggestion
	name = "wooden flail"
```

2024-10-04 10:44 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/flail.dm
> +	name = "Militia flail"
```suggestion
	name = "militia flail"
```

2024-10-04 10:44 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	name = "Spike"
```suggestion
	name = "impale"
```

2024-10-04 10:45 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	force_wielded = 25
```suggestion
	force_wielded = 20
```

2024-10-04 10:46 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	force = 16
```suggestion
	force = 15
```

2024-10-04 10:46 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/axes.dm
> +	force_wielded = 30
```suggestion
	force_wielded = 25
```

2024-10-04 10:49 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	name = "woodcutter great axe (+w)"
```suggestion
	name = "Woodcutter greataxe (+w)"
```

2024-10-04 10:50 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	name = "war axe (2) (+w)"
```suggestion
	name = "War axe (2) (+w)"
```

2024-10-04 10:51 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/tools.dm
> +	force_wielded = 25//same as any mace
```suggestion
	force_wielded = 30
```

2024-10-04 10:51 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/tools.dm
> +	wlength = 10
```suggestion
	wlength = 10
	wbalance = -1 // Heavy
```

2024-10-04 10:52 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/tools.dm
> +	force = 20
```suggestion
	force = 15
```

2024-10-04 10:54 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	name = "sledgehammer(+s)"
```suggestion
	name = "Sledgehammer(+s)"
```

2024-10-04 10:56 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	additional_items = list(/obj/item/grown/log/tree/stick)
Wood doesn't affect anything about weakness or anything, it's basically a lucerne

2024-10-04 10:56 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	additional_items = list(/obj/item/grown/log/tree/stick)
```suggestion
	additional_items = list(/obj/item/grown/log/tree/small)
```

2024-10-04 10:57 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/tools.dm
> +	gripped_intents = list(/datum/intent/mace/strike, /datum/intent/mace/smash)
```suggestion
	gripped_intents = list(/datum/intent/mace/heavy/strike, /datum/intent/mace/heavy/smash)
```
2hander

2024-10-04 10:58 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/tools.dm
> +	gripped_intents = list(/datum/intent/mace/strike, /datum/intent/mace/smash)
```suggestion
	gripped_intents = list(/datum/intent/mace/heavy/strike, /datum/intent/mace/heavy/smash)
```

2024-10-04 10:59 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/knives.dm
> +	force = 7
```suggestion
	force = 8
```
Lower the stone knife to 7 if you can as well.

2024-10-04 11:09 UTC, ThePainkiller commented
Once changes requested on the comments are addressed this will be good to merge

2024-10-04 14:46 UTC, NPC1314 commented
Certainly not good for a merge, the same problems of overwriting unique sprites with copies remain.

Instead of overwriting the odular/Neu_Farming/icons/farmtools.dmi and odular/Neu_Farming/icons/farmtools_big.dmi,
just add your updated sprites to the usual tool files you did previously. 32.dmi, 64.dmi, tools.dmi. Its trivial to point the tools back to those files for a test.

Just at a glance I can tell this will reintroduce the floating offset on pitchforks besides the above, the farming tools bit of this PR just needs to be its own PR simple as, its not good.

2024-10-04 18:31 UTC, Dorodomki commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree = 1)
adding the knife to the list + carpenter or smithy hammer to make the reinforced versions of iron and steel

2024-10-04 18:34 UTC, Dorodomki commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree = 1)
including a table too

2024-10-04 18:48 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/items.dm
> +	reqs = list(/obj/item/grown/log/tree = 1)
Table feels a bit overkill, but considering you need like craftdiff 1 to craft one, and you're doing something based on carpentry level, I don't think it's that bad, you should attempt these recipes if you're a skilled carpenter after all

2024-10-04 18:49 UTC, ThePainkiller commented
Well, thank you pig, I did not legit know it was an issue
Anyways, address pig's concerns for icons, and test pitchforks in game, and we'll be good on my end.

2024-10-05 00:02 UTC, ThePainkiller submitted a review, later dismissed

2024-10-05 00:02 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	name = "estoc"
```suggestion
	name = "Estoc"
```
Blacksmithing recipes are capitalized, crafting recipes are not

2024-10-05 00:02 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	name = "buckler shield"
```suggestion
	name = "Buckler"
```

2024-10-05 00:02 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	name = "warhammer(+s)"
```suggestion
	name = "Warhammer(+s)"
```

2024-10-05 00:02 UTC, ThePainkiller commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
> +	recipe_name = "a Zibantu Sword"
```suggestion
	recipe_name = "a Zybean Sword"
```

2024-10-05 21:46 UTC, Optimism333 reviewed
Personally I don't think the Garrison Fencer needs to have their starting weapon reduced to an iron estoc. I already downgraded their armor to studded leather and took their bracers away to give them incentive to visit the smith.

Other than that, there's a couple weapon descriptions that could use some edits. I'll try and send you a list later today.

2024-10-05 23:20 UTC, ThePainkiller commented
> Personally I don't think the Garrison Fencer needs to have their starting weapon reduced to an iron estoc

It's so that they have a reason to visit the smiths for an upgrade, otherwise weaponsmith will always be pointless :c

2024-10-06 01:00 UTC, Optimism333 commented
> > Personally I don't think the Garrison Fencer needs to have their starting weapon reduced to an iron estoc
> 
> It's so that they have a reason to visit the smiths for an upgrade, otherwise weaponsmith will always be pointless :c

I get that, but I don't think the class needs that sort of downgrade. They can still visit the weaponsmith for a better quality rapier, or a sabre if they want a different swift sword. They have pretty low armor compared to the rest of the garrison (only higher than archer), that's balanced by speed and a steel weapon.

2024-10-06 23:00 UTC, ThePainkiller requested changes

2024-10-06 23:00 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/swords.dm
> +	icon = 'icons/roguetown/weapons/32.dmi'
```suggestion
	icon = 'icons/roguetown/weapons/32.dmi'

```

2024-10-06 23:00 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/flail.dm
> +	icon = 'icons/roguetown/weapons/32.dmi'
```suggestion
	icon = 'icons/roguetown/weapons/32.dmi'

```

2024-10-06 23:00 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/melee/polearms.dm
> +	sellprice = 10
```suggestion
	sellprice = 10

```

2024-10-06 23:21 UTC, ThePainkiller submitted a review, later dismissed

2024-10-06 23:21 UTC, ThePainkiller commented on code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
> +mob/living/simple_animal/hostile/retaliate/rogue/wolf
```suggestion
/mob/living/simple_animal/hostile/retaliate/rogue/wolf
```

2024-10-06 23:21 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/leather.dm
> +datum/crafting_recipe/roguetown/leather/brimmedhat
```suggestion
/datum/crafting_recipe/roguetown/leather/brimmedhat
```

2024-10-06 23:21 UTC, ThePainkiller commented on code/modules/roguetown/roguecrafting/leather.dm
> +datum/crafting_recipe/roguetown/leather/leatherjacket
```suggestion
/datum/crafting_recipe/roguetown/leather/leatherjacket
```

2024-10-07 03:04 UTC, ThePainkiller approved these changes
In the near future, quarterstaves might receive their own skill datum so that monks aren't just good with spears as well, we'll see

2024-10-07 03:23 UTC, merged