The Magical Update
Darkrp-community/OpenKeep pull request #839
Opened 2024-10-01 17:13 UTC by BadAtThisGame302

## About The Pull Request

Ports this PR: https://github.com/Rotwood-Vale/Ratwood-Keep/pull/950

Magic-wielding roles now get Spellpoints when they join based on their Arcane skill (1 level, 1 point) and any job or age related spellpoint bonuses which they can use to customize their spell loadout, also adds various new spells and a loot item that can be placed in dungeons to grant spellpoints.

A few different spells now give XP based on their fatigue cost, so one could level up their Arcane skill mid-game but it is quite slow, spamming trying to spam spells non-stop while using mana potions and sleeping usually took around 20 minutes in local tests for a Mage Adventurer.

All the ranged spells will move slower, depending on how large they are, with the greater fireball being the slowest

FORCEWALL:
Puts up a 3x1 magical wall that the caster can pass through, centered on their position when cast. Not very durable, (a MAA with a cudgel broke a wall in three hits) and lasts 20 seconds.

The sprites for the walls are temporary, they are ugly, and we know it.

ENSNARE:
A 3x3 square of warning tendrils spawns on the targeted location, and after a brief delay it immobilizes anyone caught inside for a short time.

Spitfire:
Shoot out a low-powered ball of fire (20 burn damage) that shines brightly on impact, blinding a target.

MESSAGE:
Send out a message to anyone whom you know the name of, the target cannot answer back without casting their own Message spell.

REPULSE:
Throws everything including people in a 3x3 area around the caster, turning them prone and making them drop held items, watch for your allies.

BLADE BURST:
A 1x1 square spawns on the targeted tile, and after a short delay it deals 45 damage to whomever is still standing on that tile.

NONDETECTION:
Blow a handful of ash onto a target to render them immune to scrying abilities for an hour.

HASTE:
Enhance a target with +3 Speed for 1 minute.

FEATHERFALL:
Imbue yourself and all adjacent creatures with 1 minute of fall damage resistance. You can only fall safely from one Z-level

DARKVISION:
Touch a target to grant them enhanced vision in darkness for 10 minutes, 2 minute cooldown.

Prestidigitation:
Light up a light with a spark, make a wisp above your head, or clean that dirty floor with a flick of your hand. The most basic of spells, or party trick. Depending on who you ask.

Arcane Bolt
Shoot your favorite magic missile at people, it does 30 brute damage but gets stopped by armor. Very good for long-range assaults, or accidentally shooting a towner and getting killed.

SPELL | COST
-- | --
Fireball | 4
Bolt of Lightning | 3
Spitfire | 3
Forcewall | 3
Ensnare | 3
Repulse | 3
Haste | 3
Fetch | 2
Message | 2
Blade Burst | 2
Darkvision | 2
Arcane Bolt | 2
Nondetection | 1
prestidigitation | 1
Featherfall | 1

</markdown-accessiblity-table>
</body>
</html>

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-10-01 17:25 UTC, sanshoom commented
Welcome back Dungeons and Dragons

2024-10-02 03:35 UTC, 0nemore commented
peak.

2024-10-02 09:33 UTC, Cre77 commented
please nuke repulse out of this one, as well, it'll just make this'll just make repulse widely-available and twice as obnoxious

2024-10-03 20:02 UTC, BadAtThisGame302 commented
> please nuke repulse out of this one, as well, the current point-buy will just make repulse widely-available and twice as obnoxious

I could make it more expensive point wise?

2024-10-03 20:16 UTC, BadAtThisGame302 commented
Whenever you join as Court Mage or try to ready up as Court Mage the game freezes indefinitely, no idea why.

2024-10-03 20:22 UTC, ThePainkiller commented
> Whenever you join as Court Mage or try to ready up as Court Mage the game freezes indefinitely, no idea why.

If you're able to, check for runtimes on the debugger, this is usually caused by a stack overflow due to a loop without a break condition

2024-10-06 22:35 UTC, Cre77 commented
> > please nuke repulse out of this one, as well, the current point-buy will just make repulse widely-available and twice as obnoxious
> 
> I could make it more expensive point wise?

make it nuked? it's anti-fun, uncounterable stun combat, something pretty much everyone agreed on in the original PR. this overall pointbuy pr also effectively addresses optimism's request of "replace it with something" - there's now a plethora of other spells to choose from, some of these filling the same CC niche without being busted

2024-10-06 23:27 UTC, ThePainkiller requested changes

2024-10-06 23:27 UTC, ThePainkiller commented on code/game/objects/items/granters.dm
> +    desc = "A scroll of potential known only to those that can decipher its secrets."
```suggestion
	desc = "A scroll of potential known only to those that can decipher its secrets."
```

2024-10-06 23:27 UTC, ThePainkiller commented on code/game/objects/items/granters.dm
> +    icon = 'icons/roguetown/items/misc.dmi'
```suggestion
	icon = 'icons/roguetown/items/misc.dmi'
```

2024-10-06 23:27 UTC, ThePainkiller commented on code/game/objects/items/granters.dm
> +    oneuse = TRUE
```suggestion
	oneuse = TRUE
```

2024-10-06 23:27 UTC, ThePainkiller commented on code/game/objects/items/granters.dm
> +    drop_sound = 'sound/foley/dropsound/paper_drop.ogg'
```suggestion
	drop_sound = 'sound/foley/dropsound/paper_drop.ogg'
```

2024-10-06 23:27 UTC, ThePainkiller commented on code/game/objects/items/granters.dm
> +    pickup_sound =  'sound/blank.ogg'
```suggestion
	pickup_sound =  'sound/blank.ogg'
```

2024-10-07 19:19 UTC, Tipy1802 commented
While I like the idea, court mage being limted to 2-3 spells sounds like a very huge nerf which is unwrranted.
Also what happens to spells like knock or jaunt? Are they getting deleted? Not a fan if so
I also disagree with the need to remove jaunt, especially with court mage getting already shafted big time by this PR if I am reading it well

2024-10-07 21:32 UTC, BadAtThisGame302 commented
Right the PR worked fine and I fixed the Mage issue but now these fucking linters that recently got added are messing it up.

2024-10-08 01:03 UTC, ThePainkiller commented on code/modules/spells/spell.dm
> +	if(xp_gain)
Again, even linters are telling you this is poorly handled, I suggest handling exp gain differently than this

2024-10-08 17:45 UTC, BadAtThisGame302 commented on code/modules/spells/spell.dm
> +	if(xp_gain)
Any suggestions or something? Everything else I tried got me the same results.

2024-10-12 12:37 UTC, BadAtThisGame302 commented on code/modules/spells/spell.dm
> +	if(xp_gain)
Just removed it.

2024-10-20 20:31 UTC, Optimism333 reviewed
Will give this a test, see what the reception is.

Here we go...

2024-10-24 18:51 UTC, Optimism333 reviewed
No longer locked up by the briar pr. Once this doesn't conflict, it can go in for a test merge.

2024-10-26 04:58 UTC, NameChangeStonekeep commented
these are spells from ratwood if i recall.

2024-10-26 07:45 UTC, BadAtThisGame302 commented
> these are spells from ratwood if i recall.

Yes, the PR is ported from Ratwood.

2024-10-26 08:48 UTC, Genevesh commented
Other codes made plenty of funky non-combat spells I think would really make wizards more of the jack of all trades they were always meant to be instead of just funny magic men throwing big boom fireballs.

You could prolly yoink that

2024-10-26 21:21 UTC, NameChangeStonekeep commented
I don't mind new spells i am just iffy on the things as someone thinks it's a good idea to port blackstone/ratwood stuff while its not even meant to be used for stonekeep as the code is different and the intention of gameplay is different as usually with their code it's god awful and not even properly coded or just buggy as heck I think we should just wait for custom spells in the future then potentially risk issues with ratwood/blackstone code as its usually just awful in the end. and I don't think it be a nice view if people confuse stonekeep for blackstone code

I don't dissaprove of custom spells but why not make our own and just have a little patience then porting potential broke/unworking stuff from theirs?

No disrespect to this PR though :)

2024-10-27 06:02 UTC, Dagonlives commented
Can we have options to pick knock and jaunt? Those were both very fun spells that didn't overly break the game unlike repulse.  I could see reason to restrict jaunt to court mage only, but it seems a shame to have them lose both those spells.

2024-10-27 07:36 UTC, Gunnarrecall commented
> I don't mind new spells i am just iffy on the things as someone thinks it's a good idea to port blackstone/ratwood stuff while its not even meant to be used for stonekeep as the code is different and the intention of gameplay is different as usually with their code it's god awful and not even properly coded or just buggy as heck I think we should just wait for custom spells in the future then potentially risk issues with ratwood/blackstone code as its usually just awful in the end. and I don't think it be a nice view if people confuse stonekeep for blackstone code
> 
> I don't dissaprove of custom spells but why not make our own and just have a little patience then porting potential broke/unworking stuff from theirs?
> 
> No disrespect to this PR though :)

I'm not a coder, but I'll respond to this as a court mage main and say that from a game design perspective I really like the **_principle_** of this update. The RP spells in particular are extremely welcome, particularly giving mages message and things like prestidigitation while also giving us support spells. Makes us less of one-man nukes (which seems to be a huge point of critique and contention in the discord and community) and more of a wizard in a sort of fantasy party setting. If anyone would like to expand on this with more RP/utility spells, it'd be HIGHLY welcome.

2024-10-27 07:37 UTC, Gunnarrecall commented
> Can we have options to pick knock and jaunt? Those were both very fun spells that didn't overly break the game unlike repulse. I could see reason to restrict jaunt to court mage only, but it seems a shame to have them lose both those spells.

Jaunt, knock, and prestidigitation seem to all be baseline spells for court mage at least with others being chosen from the point buy system listed in the PR.

2024-10-27 12:19 UTC, Cre77 commented
sorceress (female adv mage) has old spells and no pointbuy
could just btfo them and make mages available to women

2024-10-27 15:54 UTC, BadAtThisGame302 commented
> Can we have options to pick knock and jaunt? Those were both very fun spells that didn't overly break the game unlike repulse. I could see reason to restrict jaunt to court mage only, but it seems a shame to have them lose both those spells.

Jaunt and knock will be OP in the hands of the average Mage, so no. Same as repulse and greater fireball, they are not accessible.

2024-10-27 15:54 UTC, BadAtThisGame302 commented
> Forcewall and featherfall both appear bugged.
> 
> Caster is unable to move through forcewall despite the spell description when choosing it.
> 
> Featherfall's AoE effect to buff nearby players also seems to be non-functioning.

These at least from how I see it will work now, if there are further issues let me know.

2024-10-27 18:31 UTC, Cre77 commented on code/modules/spells/roguetown/wizard.dm
> +	for(var/mob/living/simple_animal/hostile/animal in range(area_of_effect, T))
ensnare (unless it's already been fixed) doesn't stun simplemobs, at least those present in the map and ambushes. could it be because they're /mob/living/simple_animal/hostile/retaliate/rogue/[insertanimal], instead of /mob/living/simple_animal/hostile/animal like referenced here?

2024-10-27 19:09 UTC, BadAtThisGame302 commented on code/modules/spells/roguetown/wizard.dm
> +	for(var/mob/living/simple_animal/hostile/animal in range(area_of_effect, T))
You're so right, sexy.

2024-10-28 03:57 UTC, sanshoom commented
why is fetch 2 points lmao

2024-10-29 22:33 UTC, NPC1314 approved these changes

2024-10-29 22:33 UTC, merged