Hand Buffs (Tis peak)
Darkrp-community/OpenKeep pull request #851
Opened 2024-10-02 14:51 UTC by BadAtThisGame302

## About The Pull Request

Gives the so called Spymaster more Rogue skills... like SNEAKING.... one extra climbing and one extra on crossbows.

Also gives him the ability to see prices of items, nudging him towards the Steward/Courtier angle aswell.

And removes the unused walls key 

## Why It's Good For The Game

The so called and constantly shouted at Spymaster when even a beggar has more sneaking than him... tis peak!! Not to mention the see prices fluff and the extra crossbow/climbing for that Royal Rogue vibe people keep screaming about.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-10-02 21:00 UTC, ThePainkiller requested changes

2024-10-02 21:00 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/nobility/hand.dm
> +		H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 3, TRUE)
```suggestion
		H.mind.adjust_skillrank(/datum/skill/combat/crossbows, 2, TRUE)
```
Not a combat unit, no.

2024-10-07 06:30 UTC, Optimism333 reviewed
Role might have been a bit overly nerfed. I think it will need a more thorough look at some point... but this is fine in the meantime. 

Will give it a day to see if there's any more objections or feedback.

2024-10-07 08:51 UTC, NPC1314 commented
Sneaky hand makes sense but I will say this, stats on roles keep changing and theres no system to it.
The old rule of thumb gives the statline as +9 post these changes, from +6 before (str and speed count as 2)

Is that reasonable? I dont know.

2024-10-09 18:31 UTC, Optimism333 approved these changes
No blatant opposition, even after a couple days.

Stats are a bit high, but not insane for a single-slot role that is supposed to be the King's best buddy. Let's see how this goes.

2024-10-09 18:42 UTC, merged