Blowguns
Darkrp-community/OpenKeep pull request #858
Opened 2024-10-03 09:55 UTC by WWWWW-Git

Or, "We cavemen now"

## About The Pull Request

Adds a craftable blowgun as well as darts to the game. Fundamentally it is similar to the crossbow in that you have to click it to ready it to be fired before you can fire it. Its ammo type is the dart, a new kind of projectile that can be crafted like the blowgun. The blowgun can be made using a stick while the dart for the blowgun can be made using a thorn and a stick.
![556456](https://github.com/user-attachments/assets/581f2a83-40b1-4d10-8370-c7ae9813224f)
![331456](https://github.com/user-attachments/assets/da03f043-8213-4a6f-8eed-f6e00f77c157)

## Why It's Good For The Game

I believe that more ranged weapon variety is a plus, especially with other ideas in mind such as slings for throwing stones. Balance wise I want the blowgun to be less effective than either the bow or crossbow but easier to get a hold of. Its also worth pointing out that it uses the crossbow skill, as I did not want to add an entirely new skill just for one weapon. In the future it could be built upon to allow poison darts or darts with other properties, so for now this is somewhat of a testbed.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-10-03 10:25 UTC, ThePainkiller commented
Make poisonous darts recipes I BEG OF YOU.

2024-10-03 11:37 UTC, ThePainkiller requested changes

2024-10-03 11:37 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/ranged/blowgun.dm
> +	chargedrain = 0 //no drain to aim a gun
Considering you're blowing air into a blowgun and holding your breath to shoot, I suggest using bow datum intents for these.
The reason is simple: They drain stamina the longer you're holding left click, which simulates holding your breath. If you do it until your stamina is exhausted, your character will heavy, out of wanting to "breathe again". It's foolproof!

2024-10-03 11:37 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/ranged/blowgun.dm
> +/datum/intent/shoot/musket
You're re-defining the musket attack datums rather than making a new intent exclusive for blowpipes
Copypasting isn't bad, but make sure you edit what you paste!

2024-10-07 03:26 UTC, ThePainkiller requested changes

2024-10-07 03:26 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/ranged/blowgun.dm
> +		newtime = newtime - (mastermob.STASTR * (10/20))
```suggestion
		newtime = newtime - (mastermob.STAEND * (10/20)) // Hold your breath...
```

2024-10-07 03:26 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/ranged/blowgun.dm
> +		mastermob.visible_message("<span class='warning'>[mastermob] takes a deep breath [masteritem]!</span>")
The reason for this is so that it doesn't show `"takes a deep breath blowgun!"`

2024-10-07 03:26 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/ranged/blowgun.dm
> +		newtime = newtime - (mastermob.STASTR * (10/20))
```suggestion
		newtime = newtime - (mastermob.STAEND * (10/20))
```

2024-10-07 03:26 UTC, ThePainkiller commented on code/game/objects/items/rogueweapons/ranged/blowgun.dm
> +			to_chat(user, "<span class='info'>I raise the blowgun...</span>")
Still feel like blowguns should get more akin to bows than to crossbows, you're holding your breath (expending stamina for every second you hold left click) and then release, rather than just raising it like a crossbow.

2024-10-07 07:58 UTC, NPC1314 commented on code/game/objects/items/rogueweapons/ranged/blowgun.dm
> +			to_chat(user, "<span class='info'>I raise the blowgun...</span>")
agreed, its going to feel more right when using it I think using bow function

2024-10-07 15:50 UTC, closed without merging