Weaver & Woodcutter Hotfix
Darkrp-community/OpenKeep pull request #87
Opened 2024-05-30 19:58 UTC by Max-023

## About The Pull Request
Apparently weaver and woodcutter were displayed as combat classes, so this PR should fix that.

## Why It's Good For The Game
They aren't combat classes lol.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

2024-06-04 23:41 UTC, Max-023 commented
> merge conflict

Revolved!

2024-06-08 00:42 UTC, ThePainkiller requested changes

2024-06-08 00:42 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/weaver.dm
> +	allowed_sexes = list("male", "female")
```suggestion
	allowed_sexes = list(MALE, FEMALE)
```
For further reference for any coders, capitalizing the words with no quotation marks is better for standardization.

2024-06-08 00:42 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/weaver.dm
>  	ispilgrim = FALSE
```suggestion
	ispilgrim = TRUE
```

2024-06-08 00:50 UTC, ThePainkiller approved these changes
All good now.

2024-06-14 18:15 UTC, ThePainkiller requested changes

2024-06-14 18:15 UTC, ThePainkiller commented on code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm
> +	allowed_sexes = list("male", "female")
```suggestion
	allowed_sexes = list(MALE, FEMALE)
```

2024-06-15 00:35 UTC, ThePainkiller approved these changes

2024-06-22 23:50 UTC, Stutternov approved these changes

2024-06-22 23:50 UTC, merged