my friend plank and some tools
Darkrp-community/OpenKeep pull request #931
Opened 2024-10-12 04:30 UTC by cornercube

## About The Pull Request
adds planks, saws, chisels, stone blocks

## Why It's Good For The Game
requested by optimism
will make carpenters more important

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-11-12 04:56 UTC, Dorodomki commented
please merg

2024-11-13 03:40 UTC, cornercube commented
> please merg

almost ready

2024-11-19 11:15 UTC, NPC1314 commented
Got some conflicts, needs fixing before it can be tested.

2024-11-20 03:21 UTC, cornercube commented
> Got some conflicts, needs fixing before it can be tested.

pain
but I think I got all of the conflicts

2024-11-21 20:47 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 2,
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:47 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 2)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 requested changes

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 2)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank=3)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank=2)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank=2,
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank=2)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 1,
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/structure.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 1,
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 2)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 1)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:49 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguecrafting/turfs.dm
> +	reqs = list(/datum/crafting_recipe/roguetown/plank = 2)
Spoiler alert, someone didn't text their work. This is the wooden plank CRAFTING RECIPE not the WOODEN PLANK itself.

2024-11-21 20:51 UTC, Dorodomki commented
noticed the mason doesn't spawn with a chisel to make stone bricks, somewhat the bolt door isn't aviable to craft either, no tables or other stuff is aviable to craft

2024-11-21 21:05 UTC, Dorodomki commented
also the small wooden planks aren't craftable or stackable

2024-11-22 03:29 UTC, cornercube commented
> noticed the mason doesn't spawn with a chisel to make stone bricks, somewhat the bolt door isn't aviable to craft either, no tables or other stuff is aviable to craft

should be fixed now

2024-11-23 08:08 UTC, NPC1314 commented
Allright, let me know when the new conflict due to the code cleanup is handled, should be minor, so we can do another test of this

2024-11-23 23:14 UTC, NPC1314 commented
Until you actually test the PR and provide a video of it working this PR is a leper, second time it breaks crafting.

2024-11-23 23:35 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
> +	recipe_name = " handsaw"
Wrong recipe name

2024-11-23 23:36 UTC, BadAtThisGame302 requested changes
I think adding a stone saw perhaps, to allow for easier access to planks and creating buildings outside of forcing someone to smith even when there might not be one, would be great.

2024-11-24 10:51 UTC, NPC1314 commented
The core issue is it introduces a new system without proper information and setup to allow players to adapt to it and use it.
It needs a companion manual book or something giving some hints, along with a summary of the recipe changes in the PR description, for starters.

2024-11-24 14:32 UTC, cornercube commented
> I think adding a stone saw perhaps, to allow for easier access to planks and creating buildings outside of forcing someone to smith even when there might not be one, would be great.

added a saw made out of stone and bone, only needs a knife to carve it

2024-11-26 17:20 UTC, BadAtThisGame302 requested changes

2024-11-26 17:20 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/craftsman/tools.dm
> +	desc = "an iron saw for sawing wood."
Capitalize the An.

2024-11-26 17:20 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/craftsman/tools.dm
> +	desc = "a serrated piece of flint with a bone handle."
Capitalize the A.

2024-11-26 17:20 UTC, BadAtThisGame302 commented on code/modules/roguetown/roguejobs/craftsman/tools.dm
> +	desc = "a smooth wooden plank that has been cut short."
Capitalize the A.

2024-11-26 17:20 UTC, BadAtThisGame302 commented on code/modules/cargo/packsrogue/tools.dm
> +	/obj/item/rogueweapon/chisel)
Two chisels?

2024-11-27 02:59 UTC, cornercube commented on code/modules/cargo/packsrogue/tools.dm
> +	/obj/item/rogueweapon/chisel)
yeah, they are smaller items compared to the handsaw, so figured you could get more than one like with daggers

2024-12-01 10:46 UTC, BadAtThisGame302 reviewed
I think we can TM it for now and see how it goes once again?

2024-12-05 03:44 UTC, cornercube commented
can we test this out again?
every new PR thats merged makes it harder to update this

2024-12-05 09:01 UTC, NPC1314 commented
Which recipes that can be made now without tools now need the processed material?
How do people get the tools for processing them?
Why dye_bin recipe renamed to _bin?
If you got answers we can TM.

2024-12-05 10:25 UTC, cornercube commented
> Which recipes that can be made now without tools now need the processed material?
twig floors for wood
rough stone floors for stone

> How do people get the tools for processing them?
blacksmith can make the saw and chisel out of iron and sticks
you can make a crude saw out of bone and stone

> Why dye_bin recipe renamed to _bin?
that was fixed, its dye_bin

2024-12-08 09:20 UTC, NPC1314 commented
Got issues at the entry level implementation, locking quite a few recipes behind tools you need to scavenge or hunt to make.
Idea of planks and bricks itself is pretty neat.

2024-12-14 14:00 UTC, NPC1314 approved these changes

2024-12-14 14:00 UTC, merged