Sleeping bags! Sleepcloths!
Darkrp-community/OpenKeep pull request #96
Opened 2024-05-31 22:02 UTC by casualspacestation14enjoyer

## About The Pull Request

Sleepcloths! You can now sew bedsheets and sleepcloths. A sleepcloth is basically a sleeping bag which you can roll up to carry around with you. For the added convenience it's also very uncomfortable to sleep on, causing you to get a mood debuff. An even  bigger one if you're of noble blood.

## Why It's Good For The Game

Convenience! And a better camping experience.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-06-01 08:23 UTC, NPC1314 approved these changes
Looks good, better gameplay than carpenting wooden beds in the forest.

2024-06-06 14:10 UTC, casualspacestation14enjoyer commented
merge  conflict fixed

2024-06-09 05:08 UTC, ThePainkiller requested changes

2024-06-09 05:34 UTC, casualspacestation14enjoyer commented on code/game/objects/structures/beds_chairs/roguechair.dm
> +	..()
attack_hand replaced by middleclick for consistency since you use middleclick to unroll it so why not for unrolling

2024-06-09 05:50 UTC, ThePainkiller commented on code/game/objects/structures/beds_chairs/roguechair.dm
> +	..()
Trust me on this one, I thought about middleclick too, but it's better to make it right click for uh... _reasons._

2024-06-09 06:25 UTC, merged

2024-06-09 10:50 UTC, casualspacestation14enjoyer commented on code/game/objects/structures/beds_chairs/roguechair.dm
> +	..()
> Trust me on this one, I thought about middleclick too, but it's better to make it right click for uh... _reasons._

oh for fucks sake you wanna fuck dont you (middleclick the woman not the bed dumbfuck)