Race stat final sorting
Darkrp-community/OpenKeep pull request #970
Opened 2024-10-17 22:59 UTC by NPC1314

## About The Pull Request

We had one or two PRs fixing a few of the issues but no comprehensive overview. Did that, summarized and set the new default at +3 and adjusted accordingly within the current framework. Some are unchanged like dark elves, the biggest winner by far is dwarves, second is humens, see the summary pic and it will be clear what and why.

Also adds in the Humen racial trait of +1 Fortune as placeholder.
All as discussed previously.

![nerfracism](https://github.com/user-attachments/assets/fcacdf0c-daff-4257-bea6-2d3ef91bf942)

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-10-17 23:34 UTC, Coastfront commented
Half-elf seemingly just becoming objectively-worse humen is hilarious

2024-10-17 23:57 UTC, Optimism333 commented
I think it's reasonable to give each half-elf a point of speed back. 

-1 Int and -1 End for both male and female, +1 speed for each.

2024-10-18 00:21 UTC, sanshoom commented
holy shit aasimar getting +3 constitution. i kneel.

Anyways, why do the children of the main honcho god lose their fortune?

2024-10-18 01:16 UTC, DovaKitty requested changes
Gem PR I fear. Huge dwarf buff, which they need. Make the suggsted change and things should be good until I circle back to buff Humen with stat-select as their unique feature.

2024-10-18 01:16 UTC, DovaKitty commented on code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
Please make the changes requested by Optimism here. -1 int and -1 end for +1 speed to both.

2024-10-18 01:52 UTC, SELFHELL reviewed
Heres my initial review.. but you seem to be REALLY creeping the stats

2024-10-18 01:52 UTC, SELFHELL commented on code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
> +	specstats = list("strength" = 0, "perception" = 0, "intelligence" = 0, "constitution" = 1, "endurance" = 2, "speed" = 0, "fortune" = 1)
I dont think giving humans a net +4 in stats is good.

2024-10-18 01:52 UTC, SELFHELL commented on code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
> +	specstats = list("strength" = 0, "perception" = 1, "intelligence" = 1, "constitution" = 0, "endurance" = 1, "speed" = 0, "fortune" = 0)
same here.. net +3 isnt good

2024-10-18 01:54 UTC, SELFHELL commented
Might just be me.. but giving pure positives with no negatives is icky.

2024-10-18 01:55 UTC, messagecypher commented on code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
> +	specstats = list("strength" = 0, "perception" = 1, "intelligence" = 1, "constitution" = 0, "endurance" = 1, "speed" = 0, "fortune" = 0)
feel like, for the half elves at least, they're just trying to compromise removing all their speed

2024-10-18 02:07 UTC, Optimism333 commented on code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
> +	specstats = list("strength" = 0, "perception" = 0, "intelligence" = 0, "constitution" = 1, "endurance" = 2, "speed" = 0, "fortune" = 1)
All the other races in this template that are being held to a +3 standard have a unique feature (Dorf poison resistance, elf nite vision, aasimar pain and bleed resistance). Since humens do not have any unique features, they get a little +1 to fortune.

Whether that will remain their unique feature or be replaced? We'll see. But I think it's fair.

2024-10-18 02:42 UTC, Optimism333 commented
> holy shit aasimar getting +3 constitution. i kneel.
> 
> Anyways, why do the children of the main honcho god lose their fortune?

They were bred for a war with no choice in the matter by an abusive parent, then left to face the ravages of time with no assurance of a future as their numbers slowly erode away and they go extinct. If anything the question ought to be why they don't lose MORE fortune.

I ain't no fortunate one...

2024-10-18 07:38 UTC, Optimism333 approved these changes
With the half-elf speed at +1 again, this looks good to go. Will more than likely need further adjustments down the line, but at least we have a template of sorts now.

And dorfs desperately needed a little leg up, so congratulations to them.

2024-10-18 07:40 UTC, merged