Mining and ore import update
Darkrp-community/OpenKeep pull request #973
Opened 2024-10-18 04:46 UTC by Dorodomki

## About The Pull Request

Hello smith, take 30 iron ore, make fullplate for garrison, glory to enigma.

adds more chances to get an random ore on high rarity ore turfs, a 10% more so is an 60% in total, adds gemeralds into the list of things to drop, making them finally obtainable ranging from COAL to DIAMONDS!

then adds a proper balance among the iron and copper imports, making 50 mammons the import of copper for 5 ores, a total of 10 mammons per ore when you can buy a bar for 10 at the stockpile, proteccionist economic measures for the island are real... yes.

the silver and gold drop rates get reduced since previously they were overabundant to get on rare ore piles, leading to the players to visit mt decap just for gold and silver and buy the iron and coal exports for a very cheap price

then lowers the ammount of iron import to 4 instead of 5 ores, this means the import of ore won't be a lot of iron to produce into valious steel to speedarm the garrison and king, they can produce a max of 4 steel bars (enough for a king Fullplate) and 1 iron bar that can be made into 4 iron if a miner worked the ground with just 2 pieces more, the cost is also drastically increased since is too easy obtain mammons by gamey mechanics like the royal treasury, i hope this leads to more mining expeditions to supply the town and trade

## Why It's Good For The Game

our players deserve challenge and fun, unchallenged easy fun isn't good

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2024-10-18 04:57 UTC, ThePainkiller submitted a review, later dismissed

2024-10-18 04:57 UTC, ThePainkiller commented on code/game/objects/items/rogueitems/gems.dm
> +/obj/item/roguegem/random/Initialize()
```suggestion
/obj/item/roguegem/random/Initialize()
	..()
```

2024-10-26 14:35 UTC, NPC1314 commented
Looks reasonable to me. TM?

2024-10-26 15:09 UTC, Gunnarrecall commented
Just to add to the thread here discussion I had mentioned in the discord. While I understand the motivation behind the changes, a compromise for Underdwellers/Miners/Smithies would be nice. Mining subclasses with a bit more potential in smithing their own components by hand or giving the smithies average or skilled mining instead of weak would make the gameplay loop in the absence of the opposite job role much, MUCH less painful.

2024-10-26 15:12 UTC, Gunnarrecall commented
Copy and pasting from another thread that is similarly relevant with the stockpile changes.

Just to add to the thread here discussion I had mentioned in the discord. While I understand the motivation behind the changes, a compromise for Underdwellers/Miners/Smithies would be nice. Mining subclasses with a bit more potential in smithing their own components by hand or giving the smithies average or skilled mining instead of weak would make the gameplay loop in the absence of the opposite job role much, MUCH less painful.

2024-10-26 17:05 UTC, NPC1314 commented
> Copy and pasting from another thread that is similarly relevant with the stockpile changes.
> 
> Just to add to the thread here discussion I had mentioned in the discord. While I understand the motivation behind the changes, a compromise for Underdwellers/Miners/Smithies would be nice. Mining subclasses with a bit more potential in smithing their own components by hand or giving the smithies average or skilled mining instead of weak would make the gameplay loop in the absence of the opposite job role much, MUCH less painful.

A bit of cross pollination doesnt seem like a bad idea to make it less painful lowpop, +1 level mining to smiths and +1 level smithing to miner perhaps? Someone with more experience in the miner loop can weigh in.

2024-10-27 14:17 UTC, NPC1314 commented
In for a test then!

2024-10-28 20:40 UTC, ThePainkiller commented on code/game/turfs/closed/minerals.dm
> +	mineralSpawnChanceList = list(/turf/closed/mineral/rogue/gold = 5 , /turf/closed/mineral/rogue/iron = 25, /turf/closed/mineral/rogue/silver = 5, /turf/closed/mineral/rogue/gemeralds = 5)
This will make gold and silver insanely rarer. This is the ONLY spawner for them.

2024-10-29 04:17 UTC, ThePainkiller requested changes
I believe this might be a bit harsh but we can't have gold+silver being as close as gems in terms of rarity, right? Balance is hard...

2024-10-29 04:17 UTC, ThePainkiller commented on code/game/turfs/closed/minerals.dm
> +	mineralSpawnChanceList = list(/turf/closed/mineral/rogue/gold = 15 , /turf/closed/mineral/rogue/iron = 25, /turf/closed/mineral/rogue/silver = 15, /turf/closed/mineral/rogue/gemeralds = 10)
```suggestion
	mineralSpawnChanceList = list(/turf/closed/mineral/rogue/gold = 15 , /turf/closed/mineral/rogue/iron = 25, /turf/closed/mineral/rogue/silver = 15, /turf/closed/mineral/rogue/gemeralds = 5)
```

2024-10-29 04:18 UTC, Dorodomki commented on code/game/turfs/closed/minerals.dm
> +	mineralSpawnChanceList = list(/turf/closed/mineral/rogue/gold = 15 , /turf/closed/mineral/rogue/iron = 25, /turf/closed/mineral/rogue/silver = 15, /turf/closed/mineral/rogue/gemeralds = 10)
1984 a total dictatorship, you are ruining the fun of mine gems and find coal

2024-10-29 04:22 UTC, ThePainkiller commented
Sorry, revert that last change please (I said this on the Code channel but I wanna leave a public comment here regretting my own decision), we'll see how this goes testmerged on live and if gems are becoming quite common to get we might nerf it down to 8 rather than 5

2024-10-30 09:05 UTC, NPC1314 commented
As was explained by Dromki this is meant to fit the remaps in #996 and since that did not work this should not stay in testing until that one is ready again.

2024-11-01 08:09 UTC, NPC1314 approved these changes

2024-11-01 08:09 UTC, merged